#!/usr/bin/env python3
"""Generate the KV-cache quantizers for the quantized attention configs.

usage: gen_kvq.py kmean|kq8 [out.loom]

yah_kmean: per-channel mean of this layer's f16 K over the prompt tokens,
  m[kv_head * 256 + d] (f32). Subtracting any per-channel constant from K
  shifts every score of a query row by the same q . m, so softmax is unchanged
  (exact); the mean centres K before quantization (SageAttention's smoothing:
  K's outlier channels are mostly a per-channel offset). Deterministic: one
  workgroup per KV head, 32 column chunks x 8 row groups, fixed-order LDS sum.
  grid (4, 1, 1) x 256.

yah_kq8: int8 K with one scale per (token, kv head, 128-dim half), the split
  the attention's wave pairs use: k8 = rne((k - m) / s), s = amax / 127
  (amax 0 -> s = 1). Output kq8[token][1024] (int8), ks[token][8] (f32,
  index head * 2 + half). 16 lanes per half, 8 dims per lane, amax by xor
  shuffles. grid (ceil(cap / 2), 1, 1) x 256 (two tokens per workgroup);
  tokens >= token_count are written as zeros.
"""
import os
import sys

V8 = "vector<8xf32>"
V8H = "vector<8xf16>"
V8I = "vector<8xi8>"


def gen_kmean():
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (kmean) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@kvq_w32) @yah_kmean() {")
    e("  %c1 = index.constant 1 : index")
    e("  %c4 = index.constant 4 : index")
    e("  %c256 = index.constant 256 : index")
    e("  kernel.launch.config workgroups(%c4, %c1, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %mean: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 8, 32, 256, 1024):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok0 = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %ntok = index.min %ntok0, %cap : index")
    e("  %stot = index.mul %cap, %c1024 : index")
    e("  %s_na, %m_na = buffer.assume.noalias %src, %mean : buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %m_flat = buffer.view %m_na[%base] : buffer -> view<1024xf32>")
    e("  %pb = index.constant 8192 : offset")
    e("  %pool = buffer.alloca<workgroup> align(16) %pb : buffer")
    e("  %pv = buffer.view %pool[%base] : buffer -> view<8x256xf32>")
    e("  %head = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %chunk = index.rem %tid, %c32 : index")
    e("  %grp = index.div %tid, %c32 : index")
    e("  %col8 = index.mul %chunk, %c8 : index")
    e("  %hb = index.mul %head, %c256 : index")
    e("  %col = index.add %hb, %col8 : index")
    e(f"  %z8 = vector.constant 0.0 : {V8}")
    e(f"  %acc = scf.for %r = [%grp to %ntok step %c8](%a = %z8 : {V8}) -> ({V8}) {{")
    e("    %ra = index.mul %r, %c1024 : index")
    e("    %ad = index.add %ra, %col : index")
    e(f"    %x = vector.load %s_flat[%ad] : view<[%stot]xf16> -> {V8H}")
    e(f"    %xf = vector.extf %x : {V8H} to {V8}")
    e(f"    %an = vector.addf %a, %xf : {V8}")
    e(f"    scf.yield %an : {V8}")
    e("  }")
    e(f"  vector.store %acc, %pv[%grp, %col8] : {V8}, view<8x256xf32>")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("  %zero = scalar.constant 0.0 : f32")
    cur = "%zero"
    for g in range(8):
        e(f"  %gi{g} = index.constant {g} : index")
        e(f"  %gv{g} = view.load %pv[%gi{g}, %tid] : view<8x256xf32> -> f32")
        e(f"  %gs{g} = scalar.addf {cur}, %gv{g} : f32")
        cur = f"%gs{g}"
    e("  %ntoki = index.cast %ntok : index to i32")
    e("  %ntokf = scalar.sitofp %ntoki : i32 to f32")
    e(f"  %mv = scalar.divf {cur}, %ntokf : f32")
    e("  %mo = index.add %hb, %tid : index")
    e("  view.store %mv, %m_flat[%mo] : f32, view<1024xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_kq8():
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (kq8) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@kvq_w32) @yah_kq8() {")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %c1 = index.constant 1 : index")
    e("  %c2 = index.constant 2 : index")
    e("  %c256 = index.constant 256 : index")
    e("  %t0 = index.add %cap, %c1 : index")
    e("  %wgs = index.div %t0, %c2 : index")
    e("  kernel.launch.config workgroups(%wgs, %c1, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %mean: buffer, %dst: buffer, %scale: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 4, 8, 16, 128, 1024):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok0 = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %ntok = index.min %ntok0, %cap : index")
    e("  %stot = index.mul %cap, %c1024 : index")
    e("  %sctot = index.mul %cap, %c8 : index")
    e("  %s_na, %m_na, %d_na, %c_na = buffer.assume.noalias %src, %mean, %dst, %scale : buffer, buffer, buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %m_flat = buffer.view %m_na[%base] : buffer -> view<1024xf32>")
    e("  %d_flat = buffer.view %d_na[%base] : buffer -> view<[%stot]xi8>")
    e("  %c_flat = buffer.view %c_na[%base] : buffer -> view<[%sctot]xf32>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %tsub = index.div %tid, %c128 : index")           # token within the workgroup
    e("  %t2 = index.mul %wg, %c2 : index")
    e("  %tok = index.add %t2, %tsub : index")
    e("  %cap1 = index.sub %cap, %c1 : index")
    e("  %tokc = index.min %tok, %cap1 : index")
    e("  %live = index.cmp ult, %tok, %ntok : index")
    e("  %lt = index.rem %tid, %c128 : index")
    e("  %col = index.mul %lt, %c8 : index")              # 8 dims per lane
    e("  %ra = index.mul %tokc, %c1024 : index")
    e("  %ad = index.add %ra, %col : index")
    e(f"  %x = vector.load %s_flat[%ad] : view<[%stot]xf16> -> {V8H}")
    e(f"  %xf = vector.extf %x : {V8H} to {V8}")
    e(f"  %m = vector.load %m_flat[%col] : view<1024xf32> -> {V8}")
    e(f"  %xc = vector.subf %xf, %m : {V8}")
    e(f"  %xa = vector.absf %xc : {V8}")
    e("  %zero = scalar.constant 0.0 : f32")
    e(f"  %amax0 = vector.reduce<maxnumf> %xa, %zero : {V8}, f32")
    cur = "%amax0"
    e("  %x32 = scalar.constant 32 : i32")
    for k in (1, 2, 4, 8):   # 16 lanes per (head, half): lanes 16j..16j+15
        e(f"  %xk{k} = scalar.constant {k} : i32")
        e(f"  %ab{k} = scalar.bitcast {cur} : f32 to i32")
        e(f"  %as{k}, %av{k} = kernel.subgroup.shuffle<xor> %ab{k}, %xk{k}, %x32 : i32, i32, i32")
        e(f"  %af{k} = scalar.bitcast %as{k} : i32 to f32")
        e(f"  %am{k} = scalar.maxnumf {cur}, %af{k} : f32")
        cur = f"%am{k}"
    e("  %r127 = scalar.constant 127.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e(f"  %s0 = scalar.divf {cur}, %r127 : f32")
    e("  %spos = scalar.cmpf ogt, %s0, %zero : f32")
    e("  %s = scf.select %spos, %s0, %one : f32")
    e("  %inv = scalar.divf %one, %s : f32")
    e(f"  %inv8 = vector.splat %inv : {V8}")
    e(f"  %xq = vector.mulf %xc, %inv8 : {V8}")
    e(f"  %xr = vector.roundevenf %xq : {V8}")
    e(f"  %xi = vector.fptosi %xr : {V8} to {V8I}")
    e(f"  %zi = vector.constant 0 : {V8I}")
    e(f"  %xo = scf.select %live, %xi, %zi : {V8I}")
    e(f"  vector.store %xo, %d_flat[%ad] : {V8I}, view<[%stot]xi8>")
    # scale: lane 16j of each half writes ks[token][head * 2 + half]
    e("  %hh = index.div %lt, %c16 : index")             # head * 2 + half
    e("  %first = index.rem %lt, %c16 : index")
    e("  %isf = index.cmp eq, %first, %c0 : index")
    e("  %so = scf.select %live, %s, %zero : f32")
    e("  %sa0 = index.mul %tokc, %c8 : index")
    e("  %sa = index.add %sa0, %hh : index")
    e("  scf.if %isf {")
    e("    view.store %so, %c_flat[%sa] : f32, view<[%sctot]xf32>")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_vstat():
    """yah_vstat: per-channel centre c = (max + min) / 2 and scale
    s = (max - min) / 254 (0 -> 1) of this layer's f16 V over the prompt:
    out[0..1023] = c, out[1024..2047] = s. Same deterministic layout as
    yah_kmean (one workgroup per kv head)."""
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (vstat) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@kvq_w32) @yah_vstat() {")
    e("  %c1 = index.constant 1 : index")
    e("  %c4 = index.constant 4 : index")
    e("  %c256 = index.constant 256 : index")
    e("  kernel.launch.config workgroups(%c4, %c1, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %stat: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 8, 32, 256, 1024):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok0 = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %ntok = index.min %ntok0, %cap : index")
    e("  %stot = index.mul %cap, %c1024 : index")
    e("  %s_na, %t_na = buffer.assume.noalias %src, %stat : buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %t_flat = buffer.view %t_na[%base] : buffer -> view<2048xf32>")
    e("  %pb = index.constant 16384 : offset")
    e("  %pool = buffer.alloca<workgroup> align(16) %pb : buffer")
    e("  %pmax = buffer.view %pool[%base] : buffer -> view<8x256xf32>")
    e("  %po = index.constant 8192 : offset")
    e("  %pmin = buffer.view %pool[%po] : buffer -> view<8x256xf32>")
    e("  %head = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %chunk = index.rem %tid, %c32 : index")
    e("  %grp = index.div %tid, %c32 : index")
    e("  %col8 = index.mul %chunk, %c8 : index")
    e("  %hb = index.mul %head, %c256 : index")
    e("  %col = index.add %hb, %col8 : index")
    e("  %big = scalar.constant 3.4028234663852886e+38 : f32")
    e("  %nbig = scalar.constant -3.4028234663852886e+38 : f32")
    e(f"  %lo0 = vector.splat %big : {V8}")
    e(f"  %hi0 = vector.splat %nbig : {V8}")
    e(f"  %hi, %lo = scf.for %r = [%grp to %ntok step %c8](%h = %hi0 : {V8}, %l = %lo0 : {V8}) -> ({V8}, {V8}) {{")
    e("    %ra = index.mul %r, %c1024 : index")
    e("    %ad = index.add %ra, %col : index")
    e(f"    %x = vector.load %s_flat[%ad] : view<[%stot]xf16> -> {V8H}")
    e(f"    %xf = vector.extf %x : {V8H} to {V8}")
    e(f"    %hn = vector.maxnumf %h, %xf : {V8}")
    e(f"    %ln = vector.minnumf %l, %xf : {V8}")
    e(f"    scf.yield %hn, %ln : {V8}, {V8}")
    e("  }")
    e(f"  vector.store %hi, %pmax[%grp, %col8] : {V8}, view<8x256xf32>")
    e(f"  vector.store %lo, %pmin[%grp, %col8] : {V8}, view<8x256xf32>")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    ch, cl = "%nbig", "%big"
    for g in range(8):
        e(f"  %gi{g} = index.constant {g} : index")
        e(f"  %gh{g} = view.load %pmax[%gi{g}, %tid] : view<8x256xf32> -> f32")
        e(f"  %gl{g} = view.load %pmin[%gi{g}, %tid] : view<8x256xf32> -> f32")
        e(f"  %mh{g} = scalar.maxnumf {ch}, %gh{g} : f32")
        e(f"  %ml{g} = scalar.minnumf {cl}, %gl{g} : f32")
        ch, cl = f"%mh{g}", f"%ml{g}"
    e("  %half = scalar.constant 0.5 : f32")
    e("  %r254 = scalar.constant 254.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e("  %zero = scalar.constant 0.0 : f32")
    e(f"  %sum = scalar.addf {ch}, {cl} : f32")
    e("  %cen = scalar.mulf %sum, %half : f32")
    e(f"  %rng = scalar.subf {ch}, {cl} : f32")
    e("  %sc0 = scalar.divf %rng, %r254 : f32")
    e("  %spos = scalar.cmpf ogt, %sc0, %zero : f32")
    e("  %sc = scf.select %spos, %sc0, %one : f32")
    e("  %mo = index.add %hb, %tid : index")
    e("  %mo2 = index.add %mo, %c1024 : index")
    e("  view.store %cen, %t_flat[%mo] : f32, view<2048xf32>")
    e("  view.store %sc, %t_flat[%mo2] : f32, view<2048xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_vq8():
    """yah_vq8: f16 V [token][1024] -> V^T uint8 blocked like yah_transpose_v16,
    [4 kv heads][ceil(cap/16) tiles][256 dims][16 keys], u = rne((v - c)/s) + 128
    (c, s from yah_vstat), tokens >= token_count -> 128 (value c; the softmax
    gives them p = 0). 32 x 32 tiles through LDS; grid (32, pitch/32)."""
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (vq8) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@kvq_w32) @yah_vq8() {")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %c1 = index.constant 1 : index")
    e("  %c31 = index.constant 31 : index")
    e("  %c32 = index.constant 32 : index")
    e("  %c256 = index.constant 256 : index")
    e("  %t0 = index.add %cap, %c31 : index")
    e("  %tiles = index.div %t0, %c32 : index")
    e("  kernel.launch.config workgroups(%c32, %tiles, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %stat: buffer, %dst: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 4, 8, 15, 16, 32, 256, 1024, 4096):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok0 = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %ntok = index.min %ntok0, %cap : index")
    e("  %p15 = index.add %cap, %c15 : index")
    e("  %p16 = index.div %p15, %c16 : index")
    e("  %pitch = index.mul %p16, %c16 : index")
    e("  %stot = index.mul %cap, %c1024 : index")
    e("  %dtot = index.mul %pitch, %c256 : index")       # dwords: pitch * 1024 B / 4
    e("  %s_na, %t_na, %d_na = buffer.assume.noalias %src, %stat, %dst : buffer, buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %t_flat = buffer.view %t_na[%base] : buffer -> view<2048xf32>")
    e("  %d_flat = buffer.view %d_na[%base] : buffer -> view<[%dtot]xi32>")
    e("  %tb = index.constant 2304 : offset")
    e("  %tile = buffer.alloca<workgroup> align(16) %tb : buffer")
    e("  %tv = buffer.view %tile[%base] : buffer -> view<32x36xf16>")
    e("  %cb = kernel.workgroup.id<x> : index")
    e("  %tbk = kernel.workgroup.id<y> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %col0 = index.mul %cb, %c32 : index")
    e("  %tok0 = index.mul %tbk, %c32 : index")
    e("  %r = index.div %tid, %c8 : index")
    e("  %sg0 = index.rem %tid, %c8 : index")
    e("  %sg = index.mul %sg0, %c4 : index")
    e("  %tok = index.add %tok0, %r : index")
    e("  %cap1 = index.sub %cap, %c1 : index")
    e("  %tokc = index.min %tok, %cap1 : index")
    e("  %sa0 = index.mul %tokc, %c1024 : index")
    e("  %sa1 = index.add %sa0, %col0 : index")
    e("  %sa = index.add %sa1, %sg : index")
    e("  %raw = vector.load %s_flat[%sa] : view<[%stot]xf16> -> vector<4xf16>")
    e("  vector.store %raw, %tv[%r, %sg] : vector<4xf16>, view<32x36xf16>")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("  %col = index.add %col0, %r : index")
    e("  %cen = view.load %t_flat[%col] : view<2048xf32> -> f32")
    e("  %colsc = index.add %col, %c1024 : index")
    e("  %sc = view.load %t_flat[%colsc] : view<2048xf32> -> f32")
    e("  %one = scalar.constant 1.0 : f32")
    e("  %inv = scalar.divf %one, %sc : f32")
    e("  %c128f = scalar.constant 128.0 : f32")
    e("  %dt = index.add %tok0, %sg : index")
    us = []
    for j in range(4):
        e(f"  %tj{j}c = index.constant {j} : index")
        e(f"  %tj{j} = index.add %sg, %tj{j}c : index")
        e(f"  %x{j} = view.load %tv[%tj{j}, %r] : view<32x36xf16> -> f16")
        e(f"  %xf{j} = scalar.extf %x{j} : f16 to f32")
        e(f"  %xc{j} = scalar.subf %xf{j}, %cen : f32")
        e(f"  %xs{j} = scalar.mulf %xc{j}, %inv : f32")
        e(f"  %xr{j} = scalar.roundevenf %xs{j} : f32")
        e(f"  %xo{j} = scalar.addf %xr{j}, %c128f : f32")
        e(f"  %tk{j} = index.add %dt, %tj{j}c : index")
        e(f"  %lv{j} = index.cmp ult, %tk{j}, %ntok : index")
        e(f"  %xl{j} = scf.select %lv{j}, %xo{j}, %c128f : f32")
        e(f"  %xu{j} = scalar.fptoui %xl{j} : f32 to i8")
        us.append(f"%xu{j}")
    # token order t0, t2, t1, t3 in the dword: the attention unpacks key pairs
    # (t0, t1) and (t2, t3) with one mask each (f16 0x6400 | u)
    e(f"  %pk = vector.from_elements {us[0]}, {us[2]}, {us[1]}, {us[3]} : vector<4xi8>")
    e("  %pkw = vector.bitcast %pk : vector<4xi8> to vector<1xi32>")
    e("  %pkd = vector.extract %pkw[0] : vector<1xi32> -> i32")
    e("  %dlive = index.cmp ult, %dt, %pitch : index")
    # dword address: ((kvh * tiles + dt/16) * 4096 + d * 16 + dt%16) / 4
    e("  %kvh = index.div %col, %c256 : index")
    e("  %dd = index.rem %col, %c256 : index")
    e("  %dtl = index.div %dt, %c16 : index")
    e("  %dj = index.rem %dt, %c16 : index")
    e("  %da0 = index.mul %kvh, %p16 : index")
    e("  %da1 = index.add %da0, %dtl : index")
    e("  %da2 = index.mul %da1, %c1024 : index")
    e("  %da3 = index.mul %dd, %c4 : index")
    e("  %da4 = index.add %da2, %da3 : index")
    e("  %dj4 = index.div %dj, %c4 : index")
    e("  %da5 = index.add %da4, %dj4 : index")
    e("  %dlim = index.sub %dtot, %c1 : index")
    e("  %da = index.min %da5, %dlim : index")
    e("  scf.if %dlive {")
    e("    view.store %pkd, %d_flat[%da] : i32, view<[%dtot]xi32>")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def main():
    which = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else f"yah_{which}.loom"
    open(out, "w").write({"kmean": gen_kmean, "kq8": gen_kq8, "vstat": gen_vstat, "vq8": gen_vq8}[which]())
    print(out)


if __name__ == "__main__":
    main()
