#!/usr/bin/env python3
"""Decode (one query token) attention over the paged fp16 KV cache.

Layout (the prefill's YAH_KV_PAGED pools, one layer):
  K pool    [pool_rows][1024] f16, logical position p in row ptab[p / 256] * 256 + p % 256
  V^T pool  [4 kv heads][pool_rows / 16 tiles][256 dims][16 keys] f16, same physical row
            (tile = row / 16, key = row % 16)
The current position comes from a device i32 (pos); keys 0..pos are visible.

Kernels (gen(which, T) with T = pool rows, a multiple of 256):
  kvappend  write the new token's K (roped, f32) and V (f32) into its row: grid 4 x 256
  part      one workgroup per (page s, kv head): the page's 256 keys against the
            six query heads of the GQA group. Scores (thread = key, from its K row),
            per-head block max / sum, p in LDS, then P.V (thread = dim, the page's V^T
            slab of 16 tiles x 256 dims x 16 keys is contiguous per kv head).
            Writes acc[s][head][256], m[s][head], l[s][head]. Grid (pages used, 4).
  reduce    one workgroup per head, thread = dim: merge the pages,
            out = (sum_s e^(m_s - M) acc_s) / (sum_s e^(m_s - M) l_s) * sigmoid(gate).
Math as QwenDecodeOnlineAttentionHalfKernel (score = q.k / 16, softmax, gate), with
the softmax in two levels instead of online.
"""
import sys

KVW = 1024          # 4 kv heads x 256
NH, NKV, HD = 24, 4, 256
G = NH // NKV       # query heads per kv head


def gen_kvappend(T):
    npg = T // 256
    L = []
    e = L.append
    e("// GENERATED by tools/gen_decode_attn.py (kvappend) -- edit the generator.")
    e("amdgpu.target<gfx1151> @da32 {subgroup_size = 32}")
    e("kernel.def target(@da32) @yah_dattn_kvappend() {")
    e("  %u1 = index.constant 1 : index")
    e("  %c4 = index.constant 4 : index")
    e("  %c256 = index.constant 256 : index")
    e("  kernel.launch.config workgroups(%c4, %u1, %u1) workgroup_size(%c256, %u1, %u1) : index")
    e("} launch(%k: buffer, %v: buffer, %kp: buffer, %vtp: buffer, %ptab: buffer, %pos: buffer) {")
    e("  %base = index.constant 0 : offset")
    e("  %c0 = index.constant 0 : index")
    e("  %c16 = index.constant 16 : index")
    e("  %c256 = index.constant 256 : index")
    e(f"  %cT = index.constant {T} : index")
    e(f"  %cpg = index.constant {npg - 1} : index")
    e(f"  %ctl = index.constant {T // 16} : index")
    e(f"  %ckw = index.constant {KVW} : index")
    e("  %k_na, %v_na, %kp_na, %vtp_na, %pt_na, %pos_na = buffer.assume.noalias %k, %v, %kp, %vtp, %ptab, %pos : buffer, buffer, buffer, buffer, buffer, buffer")
    e(f"  %kv = buffer.view %k_na[%base] : buffer -> view<{KVW}xf32>")
    e(f"  %vv = buffer.view %v_na[%base] : buffer -> view<{KVW}xf32>")
    e(f"  %kpv = buffer.view %kp_na[%base] : buffer -> view<{T * KVW}xf16>")
    e(f"  %vtv = buffer.view %vtp_na[%base] : buffer -> view<{T * KVW}xf16>")
    e(f"  %ptv = buffer.view %pt_na[%base] : buffer -> view<{npg}xi32>")
    e("  %posv = buffer.view %pos_na[%base] : buffer -> view<1xi32>")
    e("  %h = kernel.workgroup.id<x> : index")
    e("  %d = kernel.workitem.id<x> : index")
    e("  %pi = view.load %posv[%c0] : view<1xi32> -> i32")
    e("  %p0 = index.cast %pi : i32 to index")
    e(f"  %pz = index.max %p0, %c0 : index")
    e(f"  %pmax = index.constant {T - 1} : index")
    e("  %p = index.min %pz, %pmax : index")
    e("  %lp0 = index.div %p, %c256 : index")
    e("  %lp = index.min %lp0, %cpg : index")
    e("  %pgi = view.load %ptv[%lp] : view<" + str(npg) + "xi32> -> i32")
    e("  %pg0 = index.cast %pgi : i32 to index")
    e("  %pgz = index.max %pg0, %c0 : index")
    e("  %pg = index.min %pgz, %cpg : index")
    e("  %pgb = index.mul %pg, %c256 : index")
    e("  %po = index.rem %p, %c256 : index")
    e("  %row = index.add %pgb, %po : index")
    e("  %hd0 = index.mul %h, %c256 : index")
    e("  %col = index.add %hd0, %d : index")
    e("  %kx = view.load %kv[%col] : view<" + str(KVW) + "xf32> -> f32")
    e("  %vx = view.load %vv[%col] : view<" + str(KVW) + "xf32> -> f32")
    e("  %kh = scalar.fptrunc %kx : f32 to f16")
    e("  %vh = scalar.fptrunc %vx : f32 to f16")
    e("  %ka0 = index.mul %row, %ckw : index")
    e("  %ka = index.add %ka0, %col : index")
    e(f"  view.store %kh, %kpv[%ka] : f16, view<{T * KVW}xf16>")
    # V^T: ((h * tiles + row / 16) * 256 + d) * 16 + row % 16
    e("  %vt0 = index.mul %h, %ctl : index")
    e("  %tile = index.div %row, %c16 : index")
    e("  %vt1 = index.add %vt0, %tile : index")
    e("  %vt2 = index.mul %vt1, %c256 : index")
    e("  %vt3 = index.add %vt2, %d : index")
    e("  %vt4 = index.mul %vt3, %c16 : index")
    e("  %key = index.rem %row, %c16 : index")
    e("  %va = index.add %vt4, %key : index")
    e(f"  view.store %vh, %vtv[%va] : f16, view<{T * KVW}xf16>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_part(T):
    npg = T // 256
    L = []
    e = L.append
    e("// GENERATED by tools/gen_decode_attn.py (part) -- edit the generator.")
    e("amdgpu.target<gfx1151> @da32 {subgroup_size = 32}")
    e("kernel.def target(@da32) @yah_dattn_part() {")
    e("  %u1 = index.constant 1 : index")
    e("  %c4 = index.constant 4 : index")
    e("  %c256 = index.constant 256 : index")
    e(f"  %cnp = index.constant {npg} : index")
    # grid x = pages; the host dispatches only the pages in use (ceil((pos + 1) / 256))
    e("  kernel.launch.config workgroups(%cnp, %c4, %u1) workgroup_size(%c256, %u1, %u1) : index")
    e("} launch(%q: buffer, %kp: buffer, %vtp: buffer, %ptab: buffer, %pos: buffer, %acc: buffer, %ml: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 4, 8, 16, 32, 256):
        e(f"  %c{v} = index.constant {v} : index")
    e(f"  %cpg = index.constant {npg - 1} : index")
    e(f"  %ctl = index.constant {T // 16} : index")
    e(f"  %ckw = index.constant {KVW} : index")
    e(f"  %cG = index.constant {G} : index")
    e("  %zf = scalar.constant 0.0 : f32")
    e("  %ninf = scalar.constant -3.4028234663852886e+38 : f32")
    e("  %scl = scalar.constant 0.0625 : f32")
    e("  %q_na, %kp_na, %vtp_na, %pt_na, %pos_na, %acc_na, %ml_na = buffer.assume.noalias %q, %kp, %vtp, %ptab, %pos, %acc, %ml : buffer, buffer, buffer, buffer, buffer, buffer, buffer")
    e(f"  %qv = buffer.view %q_na[%base] : buffer -> view<{NH * HD}xf32>")
    e(f"  %kpv = buffer.view %kp_na[%base] : buffer -> view<{T * KVW}xf16>")
    e(f"  %vtv = buffer.view %vtp_na[%base] : buffer -> view<{T * KVW}xf16>")
    e(f"  %ptv = buffer.view %pt_na[%base] : buffer -> view<{npg}xi32>")
    e("  %posv = buffer.view %pos_na[%base] : buffer -> view<1xi32>")
    e(f"  %accv = buffer.view %acc_na[%base] : buffer -> view<{npg * NH * HD}xf32>")
    e(f"  %mlv = buffer.view %ml_na[%base] : buffer -> view<{npg * NH * 2}xf32>")
    # LDS: q [6][256] f32 | p [6][256] f32 | wave partials [8][6] f32 (max), [8][6] (sum)
    nlds = G * HD * 2 + 8 * G * 2
    e(f"  %ldsb = index.constant {nlds * 4} : offset")
    e("  %ldsp = buffer.alloca<workgroup> align(16) %ldsb : buffer")
    e(f"  %lds = buffer.view %ldsp[%base] : buffer -> view<{nlds}xf32>")
    e("  %s = kernel.workgroup.id<x> : index")
    e("  %h = kernel.workgroup.id<y> : index")
    e("  %t = kernel.workitem.id<x> : index")
    e("  %wv = index.div %t, %c32 : index")
    e("  %ln = index.rem %t, %c32 : index")
    e("  %pi = view.load %posv[%c0] : view<1xi32> -> i32")
    e("  %p0 = index.cast %pi : i32 to index")
    e("  %pz = index.max %p0, %c0 : index")
    e(f"  %pmax = index.constant {T - 1} : index")
    e("  %posx = index.min %pz, %pmax : index")
    e("  %n = index.add %posx, %c1 : index")
    e("  %sc = index.min %s, %cpg : index")
    e(f"  %pgi = view.load %ptv[%sc] : view<{npg}xi32> -> i32")
    e("  %pg0 = index.cast %pgi : i32 to index")
    e("  %pgz = index.max %pg0, %c0 : index")
    e("  %pg = index.min %pgz, %cpg : index")
    # q of the G heads of kv head h -> LDS (thread t: dims t of each head)
    e("  %qh0 = index.mul %h, %cG : index")
    for j in range(G):
        e(f"  %cj{j} = index.constant {j} : index")
        e(f"  %qhh{j} = index.add %qh0, %cj{j} : index")
        e(f"  %qa{j}a = index.mul %qhh{j}, %c256 : index")
        e(f"  %qa{j} = index.add %qa{j}a, %t : index")
        e(f"  %qx{j} = view.load %qv[%qa{j}] : view<{NH * HD}xf32> -> f32")
        e(f"  %ql{j}a = index.constant {j * HD} : index")
        e(f"  %ql{j} = index.add %ql{j}a, %t : index")
        e(f"  view.store %qx{j}, %lds[%ql{j}] : f32, view<{G * HD * 2 + 8 * G * 2}xf32>")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    LV = f"view<{G * HD * 2 + 8 * G * 2}xf32>"
    # ---- scores: thread t = key s*256 + t, physical row pg*256 + t ----
    e("  %key0 = index.mul %s, %c256 : index")
    e("  %key = index.add %key0, %t : index")
    e("  %valid = index.cmp ult, %key, %n : index")
    e("  %row0 = index.mul %pg, %c256 : index")
    e("  %row = index.add %row0, %t : index")
    e("  %kr0 = index.mul %row, %ckw : index")
    e("  %kh0 = index.mul %h, %c256 : index")
    e("  %kr = index.add %kr0, %kh0 : index")
    e(f"  %klim = index.constant {T * KVW - 8} : index")
    e("  %zv8 = vector.constant 0.0 : vector<8xf32>")
    inits = ", ".join(f"%sa{j} = %zv8 : vector<8xf32>" for j in range(G))
    res = ", ".join(f"%sr{j}" for j in range(G))
    e(f"  {res} = scf.for %c = [%c0 to %c32 step %c1]({inits}) -> ({', '.join(['vector<8xf32>'] * G)}) {{")
    e("    %d8 = index.mul %c, %c8 : index")
    e("    %ka0 = index.add %kr, %d8 : index")
    e("    %ka = index.min %ka0, %klim : index")
    e(f"    %kh = vector.load %kpv[%ka] : view<{T * KVW}xf16> -> vector<8xf16>")
    e("    %kf = vector.extf %kh : vector<8xf16> to vector<8xf32>")
    nxt = []
    for j in range(G):
        e(f"    %qo{j}a = index.constant {j * HD} : index")
        e(f"    %qo{j} = index.add %qo{j}a, %d8 : index")
        e(f"    %qq{j} = vector.load %lds[%qo{j}] : {LV} -> vector<8xf32>")
        e(f"    %sn{j} = vector.fmaf %qq{j}, %kf, %sa{j} : vector<8xf32>")
        nxt.append(f"%sn{j}")
    e(f"    scf.yield {', '.join(nxt)} : {', '.join(['vector<8xf32>'] * G)}")
    e("  }")
    for j in range(G):
        e(f"  %sd{j} = vector.reduce<addf> %sr{j}, %zf : vector<8xf32>, f32")
        e(f"  %ss{j} = scalar.mulf %sd{j}, %scl : f32")
        e(f"  %sc{j} = scf.if %valid -> (f32) {{")
        e(f"    scf.yield %ss{j} : f32")
        e("  } else {")
        e("    scf.yield %ninf : f32")
        e("  }")
    # block max per head: wave reduce -> LDS partials -> every thread reads 8
    mo = G * HD * 2
    for j in range(G):
        e(f"  %wm{j} = kernel.subgroup.reduce<maxnumf> %sc{j} : f32")
    e("  %is_l0 = index.cmp eq, %ln, %c0 : index")
    e("  scf.if %is_l0 {")
    for j in range(G):
        e(f"    %wmo{j}a = index.mul %wv, %cG : index")
        e(f"    %wmo{j}b = index.add %wmo{j}a, %cj{j} : index")
        e(f"    %wmo{j}c = index.constant {mo} : index")
        e(f"    %wmo{j} = index.add %wmo{j}b, %wmo{j}c : index")
        e(f"    view.store %wm{j}, %lds[%wmo{j}] : f32, {LV}")
    e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    for j in range(G):
        cur = "%ninf"
        for w in range(8):
            e(f"    %bmx{j}_{w}i = index.constant {mo + w * G + j} : index")
            e(f"    %bmx{j}_{w} = view.load %lds[%bmx{j}_{w}i] : {LV} -> f32")
            e(f"    %bm{j}_{w} = scalar.maxnumf {cur}, %bmx{j}_{w} : f32")
            cur = f"%bm{j}_{w}"
        e(f"  %M{j} = scalar.addf {cur}, %zf : f32")
        e(f"  %dm{j} = scalar.subf %sc{j}, %M{j} : f32")
        e(f"  %pr{j} = scalar.expf<afn> %dm{j} : f32")
        e(f"  %pl{j} = scf.if %valid -> (f32) {{")
        e(f"    scf.yield %pr{j} : f32")
        e("  } else {")
        e("    scf.yield %zf : f32")
        e("  }")
        e(f"  %po{j}a = index.constant {G * HD + j * HD} : index")
        e(f"  %po{j} = index.add %po{j}a, %t : index")
        e(f"  view.store %pl{j}, %lds[%po{j}] : f32, {LV}")
        e(f"  %ws{j} = kernel.subgroup.reduce<addf> %pl{j} : f32")
    so = mo + 8 * G
    e("  scf.if %is_l0 {")
    for j in range(G):
        e(f"    %wso{j}a = index.mul %wv, %cG : index")
        e(f"    %wso{j}b = index.add %wso{j}a, %cj{j} : index")
        e(f"    %wso{j}c = index.constant {so} : index")
        e(f"    %wso{j} = index.add %wso{j}b, %wso{j}c : index")
        e(f"    view.store %ws{j}, %lds[%wso{j}] : f32, {LV}")
    e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # m, l out (thread 0)
    e("  %is_t0 = index.cmp eq, %t, %c0 : index")
    e("  scf.if %is_t0 {")
    for j in range(G):
        cur = "%zf"
        for w in range(8):
            e(f"    %bsx{j}_{w}i = index.constant {so + w * G + j} : index")
            e(f"    %bsx{j}_{w} = view.load %lds[%bsx{j}_{w}i] : {LV} -> f32")
            e(f"    %bs{j}_{w} = scalar.addf {cur}, %bsx{j}_{w} : f32")
            cur = f"%bs{j}_{w}"
        # ml[s][head][2]
        e(f"    %mlh{j} = index.add %qh0, %cj{j} : index")
        e(f"    %mls{j} = index.constant {NH} : index")
        e(f"    %mlr{j} = index.mul %sc, %mls{j} : index")
        e(f"    %mlx{j} = index.add %mlr{j}, %mlh{j} : index")
        e(f"    %mla{j} = index.mul %mlx{j}, %c2 : index")
        e(f"    %mlb{j} = index.add %mla{j}, %c1 : index")
        e(f"    view.store %M{j}, %mlv[%mla{j}] : f32, view<{npg * NH * 2}xf32>")
        e(f"    view.store {cur}, %mlv[%mlb{j}] : f32, view<{npg * NH * 2}xf32>")
    e("  }")
    # ---- P.V: thread t = dim; the page's 16 tiles of kv head h ----
    # V^T element ((h * tiles + pg * 16 + i) * 256 + t) * 16 + k
    e("  %vt0 = index.mul %h, %ctl : index")
    e("  %vt1 = index.mul %pg, %c16 : index")
    e("  %vtb = index.add %vt0, %vt1 : index")
    e(f"  %vlim = index.constant {T * KVW - 16} : index")
    e("  %zv16 = vector.constant 0.0 : vector<16xf32>")
    inits = ", ".join(f"%oa{j} = %zv16 : vector<16xf32>" for j in range(G))
    res = ", ".join(f"%or{j}" for j in range(G))
    e(f"  {res} = scf.for %i = [%c0 to %c16 step %c1]({inits}) -> ({', '.join(['vector<16xf32>'] * G)}) {{")
    e("    %ti = index.add %vtb, %i : index")
    e("    %tr = index.mul %ti, %c256 : index")
    e("    %td = index.add %tr, %t : index")
    e("    %va0 = index.mul %td, %c16 : index")
    e("    %va = index.min %va0, %vlim : index")
    e(f"    %vh = vector.load %vtv[%va] : view<{T * KVW}xf16> -> vector<16xf16>")
    e("    %vf = vector.extf %vh : vector<16xf16> to vector<16xf32>")
    e("    %k16 = index.mul %i, %c16 : index")
    nxt = []
    for j in range(G):
        e(f"    %pp{j}a = index.constant {G * HD + j * HD} : index")
        e(f"    %pp{j} = index.add %pp{j}a, %k16 : index")
        e(f"    %pv{j} = vector.load %lds[%pp{j}] : {LV} -> vector<16xf32>")
        e(f"    %on{j} = vector.fmaf %pv{j}, %vf, %oa{j} : vector<16xf32>")
        nxt.append(f"%on{j}")
    e(f"    scf.yield {', '.join(nxt)} : {', '.join(['vector<16xf32>'] * G)}")
    e("  }")
    for j in range(G):
        e(f"  %ov{j} = vector.reduce<addf> %or{j}, %zf : vector<16xf32>, f32")
        e(f"  %ah{j} = index.add %qh0, %cj{j} : index")
        e(f"  %ao{j}a = index.constant {NH} : index")
        e(f"  %ao{j}b = index.mul %sc, %ao{j}a : index")
        e(f"  %ao{j}c = index.add %ao{j}b, %ah{j} : index")
        e(f"  %ao{j}d = index.mul %ao{j}c, %c256 : index")
        e(f"  %ao{j} = index.add %ao{j}d, %t : index")
        e(f"  view.store %ov{j}, %accv[%ao{j}] : f32, view<{npg * NH * HD}xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_reduce(T):
    npg = T // 256
    L = []
    e = L.append
    e("// GENERATED by tools/gen_decode_attn.py (reduce) -- edit the generator.")
    e("amdgpu.target<gfx1151> @da32 {subgroup_size = 32}")
    e("kernel.def target(@da32) @yah_dattn_reduce() {")
    e("  %u1 = index.constant 1 : index")
    e(f"  %cnh = index.constant {NH} : index")
    e("  %c256 = index.constant 256 : index")
    e("  kernel.launch.config workgroups(%cnh, %u1, %u1) workgroup_size(%c256, %u1, %u1) : index")
    e("} launch(%acc: buffer, %ml: buffer, %gate: buffer, %pos: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 256):
        e(f"  %c{v} = index.constant {v} : index")
    e(f"  %cnh = index.constant {NH} : index")
    e(f"  %cpg = index.constant {npg} : index")
    e("  %zf = scalar.constant 0.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e("  %ninf = scalar.constant -3.4028234663852886e+38 : f32")
    e("  %acc_na, %ml_na, %g_na, %pos_na, %o_na = buffer.assume.noalias %acc, %ml, %gate, %pos, %out : buffer, buffer, buffer, buffer, buffer")
    e(f"  %accv = buffer.view %acc_na[%base] : buffer -> view<{npg * NH * HD}xf32>")
    e(f"  %mlv = buffer.view %ml_na[%base] : buffer -> view<{npg * NH * 2}xf32>")
    e(f"  %gv = buffer.view %g_na[%base] : buffer -> view<{NH * HD}xf32>")
    e("  %posv = buffer.view %pos_na[%base] : buffer -> view<1xi32>")
    e(f"  %ov = buffer.view %o_na[%base] : buffer -> view<{NH * HD}xf32>")
    e("  %hh = kernel.workgroup.id<x> : index")
    e("  %t = kernel.workitem.id<x> : index")
    e("  %pi = view.load %posv[%c0] : view<1xi32> -> i32")
    e("  %p0 = index.cast %pi : i32 to index")
    e("  %pz = index.max %p0, %c0 : index")
    e(f"  %pmax = index.constant {T - 1} : index")
    e("  %posx = index.min %pz, %pmax : index")
    e("  %np0 = index.div %posx, %c256 : index")
    e("  %np = index.add %np0, %c1 : index")       # pages in use
    # pass 1: M = max_s m_s
    e("  %M = scf.for %s = [%c0 to %np step %c1](%mc = %ninf : f32) -> (f32) {")
    e("    %r0 = index.mul %s, %cnh : index")
    e("    %r1 = index.add %r0, %hh : index")
    e("    %mi = index.mul %r1, %c2 : index")
    e(f"    %ms = view.load %mlv[%mi] : view<{npg * NH * 2}xf32> -> f32")
    e("    %mn = scalar.maxnumf %mc, %ms : f32")
    e("    scf.yield %mn : f32")
    e("  }")
    e("  %Ls, %As = scf.for %s = [%c0 to %np step %c1](%lc = %zf : f32, %ac = %zf : f32) -> (f32, f32) {")
    e("    %r0 = index.mul %s, %cnh : index")
    e("    %r1 = index.add %r0, %hh : index")
    e("    %mi = index.mul %r1, %c2 : index")
    e("    %li = index.add %mi, %c1 : index")
    e(f"    %ms = view.load %mlv[%mi] : view<{npg * NH * 2}xf32> -> f32")
    e(f"    %ls = view.load %mlv[%li] : view<{npg * NH * 2}xf32> -> f32")
    e("    %dm = scalar.subf %ms, %M : f32")
    e("    %w = scalar.expf<afn> %dm : f32")
    e("    %ai0 = index.mul %r1, %c256 : index")
    e("    %ai = index.add %ai0, %t : index")
    e(f"    %as = view.load %accv[%ai] : view<{npg * NH * HD}xf32> -> f32")
    e("    %ln = scalar.fmaf %w, %ls, %lc : f32")
    e("    %an = scalar.fmaf %w, %as, %ac : f32")
    e("    scf.yield %ln, %an : f32, f32")
    e("  }")
    e("  %inv = scalar.divf %one, %Ls : f32")
    e("  %ctx = scalar.mulf %As, %inv : f32")
    e("  %oi0 = index.mul %hh, %c256 : index")
    e("  %oi = index.add %oi0, %t : index")
    e(f"  %g = view.load %gv[%oi] : view<{NH * HD}xf32> -> f32")
    e("  %ng = scalar.negf %g : f32")
    e("  %eg = scalar.expf<afn> %ng : f32")
    e("  %dg = scalar.addf %eg, %one : f32")
    e("  %sg = scalar.divf %one, %dg : f32")
    e("  %o = scalar.mulf %ctx, %sg : f32")
    e(f"  view.store %o, %ov[%oi] : f32, view<{NH * HD}xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen(which, T):
    assert T % 256 == 0
    return {"kvappend": gen_kvappend, "part": gen_part, "reduce": gen_reduce}[which](T)


if __name__ == "__main__":
    which, T, outp = sys.argv[1], int(sys.argv[2]), sys.argv[3]
    open(outp, "w").write(gen(which, T))
    print(outp)
