#!/usr/bin/env python3
"""Generate the KV-cache quantizers for the quantized attention configs.

usage: gen_kvq.py kmean|kq8 [out.loom]

yah_kmean: per-channel mean of this layer's f16 K over the prompt tokens,
  m[kv_head * 256 + d] (f32). Subtracting any per-channel constant from K
  shifts every score of a query row by the same q . m, so softmax is unchanged
  (exact); the mean centres K before quantization (SageAttention's smoothing:
  K's outlier channels are mostly a per-channel offset). Deterministic: one
  workgroup per KV head, 32 column chunks x 8 row groups, fixed-order LDS sum.
  grid (4, 1, 1) x 256.

yah_kq8: int8 K with one scale per (token, kv head, 128-dim half), the split
  the attention's wave pairs use: k8 = rne((k - m) / s), s = amax / 127
  (amax 0 -> s = 1). Output kq8[token][1024] (int8), ks[token][8] (f32,
  index head * 2 + half). 16 lanes per half, 8 dims per lane, amax by xor
  shuffles. grid (ceil(cap / 2), 1, 1) x 256 (two tokens per workgroup);
  tokens >= token_count are written as zeros.
"""
import os
import sys

V8 = "vector<8xf32>"
V8H = "vector<8xf16>"
V8I = "vector<8xi8>"


def gen_kmean():
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (kmean) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@kvq_w32) @yah_kmean() {")
    e("  %c1 = index.constant 1 : index")
    e("  %c4 = index.constant 4 : index")
    e("  %c256 = index.constant 256 : index")
    e("  kernel.launch.config workgroups(%c4, %c1, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %mean: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 8, 32, 256, 1024):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok0 = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %ntok = index.min %ntok0, %cap : index")
    e("  %stot = index.mul %cap, %c1024 : index")
    e("  %s_na, %m_na = buffer.assume.noalias %src, %mean : buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %m_flat = buffer.view %m_na[%base] : buffer -> view<1024xf32>")
    e("  %pb = index.constant 8192 : offset")
    e("  %pool = buffer.alloca<workgroup> align(16) %pb : buffer")
    e("  %pv = buffer.view %pool[%base] : buffer -> view<8x256xf32>")
    e("  %head = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %chunk = index.rem %tid, %c32 : index")
    e("  %grp = index.div %tid, %c32 : index")
    e("  %col8 = index.mul %chunk, %c8 : index")
    e("  %hb = index.mul %head, %c256 : index")
    e("  %col = index.add %hb, %col8 : index")
    e(f"  %z8 = vector.constant 0.0 : {V8}")
    e(f"  %acc = scf.for %r = [%grp to %ntok step %c8](%a = %z8 : {V8}) -> ({V8}) {{")
    e("    %ra = index.mul %r, %c1024 : index")
    e("    %ad = index.add %ra, %col : index")
    e(f"    %x = vector.load %s_flat[%ad] : view<[%stot]xf16> -> {V8H}")
    e(f"    %xf = vector.extf %x : {V8H} to {V8}")
    e(f"    %an = vector.addf %a, %xf : {V8}")
    e(f"    scf.yield %an : {V8}")
    e("  }")
    e(f"  vector.store %acc, %pv[%grp, %col8] : {V8}, view<8x256xf32>")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("  %zero = scalar.constant 0.0 : f32")
    cur = "%zero"
    for g in range(8):
        e(f"  %gi{g} = index.constant {g} : index")
        e(f"  %gv{g} = view.load %pv[%gi{g}, %tid] : view<8x256xf32> -> f32")
        e(f"  %gs{g} = scalar.addf {cur}, %gv{g} : f32")
        cur = f"%gs{g}"
    e("  %ntoki = index.cast %ntok : index to i32")
    e("  %ntokf = scalar.sitofp %ntoki : i32 to f32")
    e(f"  %mv = scalar.divf {cur}, %ntokf : f32")
    e("  %mo = index.add %hb, %tid : index")
    e("  view.store %mv, %m_flat[%mo] : f32, view<1024xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_kq8():
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (kq8) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@kvq_w32) @yah_kq8() {")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %c1 = index.constant 1 : index")
    e("  %c2 = index.constant 2 : index")
    e("  %c256 = index.constant 256 : index")
    e("  %t0 = index.add %cap, %c1 : index")
    e("  %wgs = index.div %t0, %c2 : index")
    e("  kernel.launch.config workgroups(%wgs, %c1, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %mean: buffer, %dst: buffer, %scale: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 4, 8, 16, 128, 1024):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok0 = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %ntok = index.min %ntok0, %cap : index")
    e("  %stot = index.mul %cap, %c1024 : index")
    e("  %sctot = index.mul %cap, %c8 : index")
    e("  %s_na, %m_na, %d_na, %c_na = buffer.assume.noalias %src, %mean, %dst, %scale : buffer, buffer, buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %m_flat = buffer.view %m_na[%base] : buffer -> view<1024xf32>")
    e("  %d_flat = buffer.view %d_na[%base] : buffer -> view<[%stot]xi8>")
    e("  %c_flat = buffer.view %c_na[%base] : buffer -> view<[%sctot]xf32>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %tsub = index.div %tid, %c128 : index")           # token within the workgroup
    e("  %t2 = index.mul %wg, %c2 : index")
    e("  %tok = index.add %t2, %tsub : index")
    e("  %cap1 = index.sub %cap, %c1 : index")
    e("  %tokc = index.min %tok, %cap1 : index")
    e("  %live = index.cmp ult, %tok, %ntok : index")
    e("  %lt = index.rem %tid, %c128 : index")
    e("  %col = index.mul %lt, %c8 : index")              # 8 dims per lane
    e("  %ra = index.mul %tokc, %c1024 : index")
    e("  %ad = index.add %ra, %col : index")
    e(f"  %x = vector.load %s_flat[%ad] : view<[%stot]xf16> -> {V8H}")
    e(f"  %xf = vector.extf %x : {V8H} to {V8}")
    e(f"  %m = vector.load %m_flat[%col] : view<1024xf32> -> {V8}")
    e(f"  %xc = vector.subf %xf, %m : {V8}")
    e(f"  %xa = vector.absf %xc : {V8}")
    e("  %zero = scalar.constant 0.0 : f32")
    e(f"  %amax0 = vector.reduce<maxnumf> %xa, %zero : {V8}, f32")
    cur = "%amax0"
    e("  %x32 = scalar.constant 32 : i32")
    for k in (1, 2, 4, 8):   # 16 lanes per (head, half): lanes 16j..16j+15
        e(f"  %xk{k} = scalar.constant {k} : i32")
        e(f"  %ab{k} = scalar.bitcast {cur} : f32 to i32")
        e(f"  %as{k}, %av{k} = kernel.subgroup.shuffle<xor> %ab{k}, %xk{k}, %x32 : i32, i32, i32")
        e(f"  %af{k} = scalar.bitcast %as{k} : i32 to f32")
        e(f"  %am{k} = scalar.maxnumf {cur}, %af{k} : f32")
        cur = f"%am{k}"
    e("  %r127 = scalar.constant 127.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e(f"  %s0 = scalar.divf {cur}, %r127 : f32")
    e("  %spos = scalar.cmpf ogt, %s0, %zero : f32")
    e("  %s = scf.select %spos, %s0, %one : f32")
    e("  %inv = scalar.divf %one, %s : f32")
    e(f"  %inv8 = vector.splat %inv : {V8}")
    e(f"  %xq = vector.mulf %xc, %inv8 : {V8}")
    e(f"  %xr = vector.roundevenf %xq : {V8}")
    e(f"  %xi = vector.fptosi %xr : {V8} to {V8I}")
    e(f"  %zi = vector.constant 0 : {V8I}")
    e(f"  %xo = scf.select %live, %xi, %zi : {V8I}")
    e(f"  vector.store %xo, %d_flat[%ad] : {V8I}, view<[%stot]xi8>")
    # scale: lane 16j of each half writes ks[token][head * 2 + half]
    e("  %hh = index.div %lt, %c16 : index")             # head * 2 + half
    e("  %first = index.rem %lt, %c16 : index")
    e("  %isf = index.cmp eq, %first, %c0 : index")
    e("  %so = scf.select %live, %s, %zero : f32")
    e("  %sa0 = index.mul %tokc, %c8 : index")
    e("  %sa = index.add %sa0, %hh : index")
    e("  scf.if %isf {")
    e("    view.store %so, %c_flat[%sa] : f32, view<[%sctot]xf32>")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_vstat():
    """yah_vstat: per-channel centre c = (max + min) / 2 and scale
    s = (max - min) / 254 (0 -> 1) of this layer's f16 V over the prompt:
    out[0..1023] = c, out[1024..2047] = s. Same deterministic layout as
    yah_kmean (one workgroup per kv head)."""
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (vstat) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@kvq_w32) @yah_vstat() {")
    e("  %c1 = index.constant 1 : index")
    e("  %c4 = index.constant 4 : index")
    e("  %c256 = index.constant 256 : index")
    e("  kernel.launch.config workgroups(%c4, %c1, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %stat: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 8, 32, 256, 1024):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok0 = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %ntok = index.min %ntok0, %cap : index")
    e("  %stot = index.mul %cap, %c1024 : index")
    e("  %s_na, %t_na = buffer.assume.noalias %src, %stat : buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %t_flat = buffer.view %t_na[%base] : buffer -> view<2048xf32>")
    e("  %pb = index.constant 16384 : offset")
    e("  %pool = buffer.alloca<workgroup> align(16) %pb : buffer")
    e("  %pmax = buffer.view %pool[%base] : buffer -> view<8x256xf32>")
    e("  %po = index.constant 8192 : offset")
    e("  %pmin = buffer.view %pool[%po] : buffer -> view<8x256xf32>")
    e("  %head = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %chunk = index.rem %tid, %c32 : index")
    e("  %grp = index.div %tid, %c32 : index")
    e("  %col8 = index.mul %chunk, %c8 : index")
    e("  %hb = index.mul %head, %c256 : index")
    e("  %col = index.add %hb, %col8 : index")
    e("  %big = scalar.constant 3.4028234663852886e+38 : f32")
    e("  %nbig = scalar.constant -3.4028234663852886e+38 : f32")
    e(f"  %lo0 = vector.splat %big : {V8}")
    e(f"  %hi0 = vector.splat %nbig : {V8}")
    e(f"  %hi, %lo = scf.for %r = [%grp to %ntok step %c8](%h = %hi0 : {V8}, %l = %lo0 : {V8}) -> ({V8}, {V8}) {{")
    e("    %ra = index.mul %r, %c1024 : index")
    e("    %ad = index.add %ra, %col : index")
    e(f"    %x = vector.load %s_flat[%ad] : view<[%stot]xf16> -> {V8H}")
    e(f"    %xf = vector.extf %x : {V8H} to {V8}")
    e(f"    %hn = vector.maxnumf %h, %xf : {V8}")
    e(f"    %ln = vector.minnumf %l, %xf : {V8}")
    e(f"    scf.yield %hn, %ln : {V8}, {V8}")
    e("  }")
    e(f"  vector.store %hi, %pmax[%grp, %col8] : {V8}, view<8x256xf32>")
    e(f"  vector.store %lo, %pmin[%grp, %col8] : {V8}, view<8x256xf32>")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    ch, cl = "%nbig", "%big"
    for g in range(8):
        e(f"  %gi{g} = index.constant {g} : index")
        e(f"  %gh{g} = view.load %pmax[%gi{g}, %tid] : view<8x256xf32> -> f32")
        e(f"  %gl{g} = view.load %pmin[%gi{g}, %tid] : view<8x256xf32> -> f32")
        e(f"  %mh{g} = scalar.maxnumf {ch}, %gh{g} : f32")
        e(f"  %ml{g} = scalar.minnumf {cl}, %gl{g} : f32")
        ch, cl = f"%mh{g}", f"%ml{g}"
    e("  %half = scalar.constant 0.5 : f32")
    e("  %r254 = scalar.constant 254.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e("  %zero = scalar.constant 0.0 : f32")
    e(f"  %sum = scalar.addf {ch}, {cl} : f32")
    e("  %cen = scalar.mulf %sum, %half : f32")
    e(f"  %rng = scalar.subf {ch}, {cl} : f32")
    e("  %sc0 = scalar.divf %rng, %r254 : f32")
    e("  %spos = scalar.cmpf ogt, %sc0, %zero : f32")
    e("  %sc = scf.select %spos, %sc0, %one : f32")
    e("  %mo = index.add %hb, %tid : index")
    e("  %mo2 = index.add %mo, %c1024 : index")
    e("  view.store %cen, %t_flat[%mo] : f32, view<2048xf32>")
    e("  view.store %sc, %t_flat[%mo2] : f32, view<2048xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_vq8():
    """yah_vq8: f16 V [token][1024] -> V^T uint8 blocked like yah_transpose_v16,
    [4 kv heads][ceil(cap/16) tiles][256 dims][16 keys], u = rne((v - c)/s) + 128
    (c, s from yah_vstat), tokens >= token_count -> 128 (value c; the softmax
    gives them p = 0). 32 x 32 tiles through LDS; grid (32, pitch/32)."""
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (vq8) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@kvq_w32) @yah_vq8() {")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %c1 = index.constant 1 : index")
    e("  %c31 = index.constant 31 : index")
    e("  %c32 = index.constant 32 : index")
    e("  %c256 = index.constant 256 : index")
    e("  %t0 = index.add %cap, %c31 : index")
    e("  %tiles = index.div %t0, %c32 : index")
    e("  kernel.launch.config workgroups(%c32, %tiles, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %stat: buffer, %dst: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 4, 8, 15, 16, 32, 256, 1024, 4096):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok0 = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %ntok = index.min %ntok0, %cap : index")
    e("  %p15 = index.add %cap, %c15 : index")
    e("  %p16 = index.div %p15, %c16 : index")
    e("  %pitch = index.mul %p16, %c16 : index")
    e("  %stot = index.mul %cap, %c1024 : index")
    e("  %dtot = index.mul %pitch, %c256 : index")       # dwords: pitch * 1024 B / 4
    e("  %s_na, %t_na, %d_na = buffer.assume.noalias %src, %stat, %dst : buffer, buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %t_flat = buffer.view %t_na[%base] : buffer -> view<2048xf32>")
    e("  %d_flat = buffer.view %d_na[%base] : buffer -> view<[%dtot]xi32>")
    e("  %tb = index.constant 2304 : offset")
    e("  %tile = buffer.alloca<workgroup> align(16) %tb : buffer")
    e("  %tv = buffer.view %tile[%base] : buffer -> view<32x36xf16>")
    e("  %cb = kernel.workgroup.id<x> : index")
    e("  %tbk = kernel.workgroup.id<y> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %col0 = index.mul %cb, %c32 : index")
    e("  %tok0 = index.mul %tbk, %c32 : index")
    e("  %r = index.div %tid, %c8 : index")
    e("  %sg0 = index.rem %tid, %c8 : index")
    e("  %sg = index.mul %sg0, %c4 : index")
    e("  %tok = index.add %tok0, %r : index")
    e("  %cap1 = index.sub %cap, %c1 : index")
    e("  %tokc = index.min %tok, %cap1 : index")
    e("  %sa0 = index.mul %tokc, %c1024 : index")
    e("  %sa1 = index.add %sa0, %col0 : index")
    e("  %sa = index.add %sa1, %sg : index")
    e("  %raw = vector.load %s_flat[%sa] : view<[%stot]xf16> -> vector<4xf16>")
    e("  vector.store %raw, %tv[%r, %sg] : vector<4xf16>, view<32x36xf16>")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("  %col = index.add %col0, %r : index")
    e("  %cen = view.load %t_flat[%col] : view<2048xf32> -> f32")
    e("  %colsc = index.add %col, %c1024 : index")
    e("  %sc = view.load %t_flat[%colsc] : view<2048xf32> -> f32")
    e("  %one = scalar.constant 1.0 : f32")
    e("  %inv = scalar.divf %one, %sc : f32")
    e("  %c128f = scalar.constant 128.0 : f32")
    e("  %dt = index.add %tok0, %sg : index")
    us = []
    for j in range(4):
        e(f"  %tj{j}c = index.constant {j} : index")
        e(f"  %tj{j} = index.add %sg, %tj{j}c : index")
        e(f"  %x{j} = view.load %tv[%tj{j}, %r] : view<32x36xf16> -> f16")
        e(f"  %xf{j} = scalar.extf %x{j} : f16 to f32")
        e(f"  %xc{j} = scalar.subf %xf{j}, %cen : f32")
        e(f"  %xs{j} = scalar.mulf %xc{j}, %inv : f32")
        e(f"  %xr{j} = scalar.roundevenf %xs{j} : f32")
        e(f"  %xo{j} = scalar.addf %xr{j}, %c128f : f32")
        e(f"  %tk{j} = index.add %dt, %tj{j}c : index")
        e(f"  %lv{j} = index.cmp ult, %tk{j}, %ntok : index")
        e(f"  %xl{j} = scf.select %lv{j}, %xo{j}, %c128f : f32")
        e(f"  %xu{j} = scalar.fptoui %xl{j} : f32 to i8")
        us.append(f"%xu{j}")
    # token order t0, t2, t1, t3 in the dword: the attention unpacks key pairs
    # (t0, t1) and (t2, t3) with one mask each (f16 0x6400 | u)
    e(f"  %pk = vector.from_elements {us[0]}, {us[2]}, {us[1]}, {us[3]} : vector<4xi8>")
    e("  %pkw = vector.bitcast %pk : vector<4xi8> to vector<1xi32>")
    e("  %pkd = vector.extract %pkw[0] : vector<1xi32> -> i32")
    e("  %dlive = index.cmp ult, %dt, %pitch : index")
    # dword address: ((kvh * tiles + dt/16) * 4096 + d * 16 + dt%16) / 4
    e("  %kvh = index.div %col, %c256 : index")
    e("  %dd = index.rem %col, %c256 : index")
    e("  %dtl = index.div %dt, %c16 : index")
    e("  %dj = index.rem %dt, %c16 : index")
    e("  %da0 = index.mul %kvh, %p16 : index")
    e("  %da1 = index.add %da0, %dtl : index")
    e("  %da2 = index.mul %da1, %c1024 : index")
    e("  %da3 = index.mul %dd, %c4 : index")
    e("  %da4 = index.add %da2, %da3 : index")
    e("  %dj4 = index.div %dj, %c4 : index")
    e("  %da5 = index.add %da4, %dj4 : index")
    e("  %dlim = index.sub %dtot, %c1 : index")
    e("  %da = index.min %da5, %dlim : index")
    e("  scf.if %dlive {")
    e("    view.store %pkd, %d_flat[%da] : i32, view<[%dtot]xi32>")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"

def gen_kq4():
    """yah_kq4 (kv4 configs): signed int4 K of H128 (k - m), H128 the
    orthonormal Walsh-Hadamard transform per 128-dim half (the attention rotates
    Q the same way, so q.k is unchanged; the rotation spreads outlier channels:
    attention error 3.2e-2 -> 2.1e-2 on layer 3). One scale per (token, kv head,
    half): s = amax / 7, q = rne(x / s) in [-7, 7].
    Output kq4[token][512 B]: lane (head, half, 8 dims) -> one dword whose byte j
    is (q_j & 15) | (q_{j+4} << 4), so the xor-0x88888888 + two-mask unpack
    yields dims in order; ks[token][8] f32 as yah_kq8. Lane map as yah_kq8."""
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (kq4) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@kvq_w32) @yah_kq4() {")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %c1 = index.constant 1 : index")
    e("  %c2 = index.constant 2 : index")
    e("  %c256 = index.constant 256 : index")
    e("  %t0 = index.add %cap, %c1 : index")
    e("  %wgs = index.div %t0, %c2 : index")
    e("  kernel.launch.config workgroups(%wgs, %c1, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %mean: buffer, %dst: buffer, %scale: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 4, 8, 16, 128, 1024):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok0 = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %ntok = index.min %ntok0, %cap : index")
    e("  %stot = index.mul %cap, %c1024 : index")
    e("  %dtot = index.mul %cap, %c128 : index")
    e("  %sctot = index.mul %cap, %c8 : index")
    e("  %s_na, %m_na, %d_na, %c_na = buffer.assume.noalias %src, %mean, %dst, %scale : buffer, buffer, buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %m_flat = buffer.view %m_na[%base] : buffer -> view<1024xf32>")
    e("  %d_flat = buffer.view %d_na[%base] : buffer -> view<[%dtot]xi32>")
    e("  %c_flat = buffer.view %c_na[%base] : buffer -> view<[%sctot]xf32>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %tsub = index.div %tid, %c128 : index")
    e("  %t2 = index.mul %wg, %c2 : index")
    e("  %tok = index.add %t2, %tsub : index")
    e("  %cap1 = index.sub %cap, %c1 : index")
    e("  %tokc = index.min %tok, %cap1 : index")
    e("  %live = index.cmp ult, %tok, %ntok : index")
    e("  %lt = index.rem %tid, %c128 : index")
    e("  %l16 = index.rem %lt, %c16 : index")
    e("  %col = index.mul %lt, %c8 : index")
    e("  %ra = index.mul %tokc, %c1024 : index")
    e("  %ad = index.add %ra, %col : index")
    e(f"  %x = vector.load %s_flat[%ad] : view<[%stot]xf16> -> {V8H}")
    e(f"  %xf = vector.extf %x : {V8H} to {V8}")
    e(f"  %m = vector.load %m_flat[%col] : view<1024xf32> -> {V8}")
    e(f"  %xc = vector.subf %xf, %m : {V8}")
    # YAH_ATTN_FA_KROT=1: rotate by H128 per half (default off: plain centred
    # int4; measured: attention error 3.2e-2 -> 2.1e-2 with the rotation)
    rotate = os.environ.get("YAH_ATTN_FA_KROT", "0") == "1"
    e(f"  %zero8 = vector.constant 0.0 : {V8}")
    # in-lane butterflies (dims 1, 2, 4 apart)
    xs = []
    for i in range(8):
        e(f"  %h0_{i} = vector.extract %xc[{i}] : {V8} -> f32")
        xs.append(f"%h0_{i}")
    st = 0
    for h in ((1, 2, 4) if rotate else ()):
        st += 1
        nx = []
        for i in range(8):
            j = i ^ h
            if i & h:
                e(f"  %h{st}_{i} = scalar.subf {xs[j]}, {xs[i]} : f32")
            else:
                e(f"  %h{st}_{i} = scalar.addf {xs[i]}, {xs[j]} : f32")
            nx.append(f"%h{st}_{i}")
        xs = nx
    e(f"  %hv{st} = vector.from_elements {', '.join(xs)} : {V8}")
    cur = f"%hv{st}"
    e("  %x32 = scalar.constant 32 : i32")
    # cross-lane butterflies (dims 8, 16, 32, 64 apart = lane xor 1, 2, 4, 8)
    for k in (1, 2, 4, 8):
        e(f"  %xk{k} = scalar.constant {k} : i32")
        if not rotate:
            continue
        e(f"  %sh{k}, %shv{k} = kernel.subgroup.shuffle<xor> {cur}, %xk{k}, %x32 : {V8}, i32, i32")
        e(f"  %ck{k}c = index.constant {k} : index")
        e(f"  %lb{k}a = index.div %l16, %ck{k}c : index")
        e(f"  %lb{k}b = index.rem %lb{k}a, %c2 : index")
        e(f"  %up{k} = index.cmp eq, %lb{k}b, %c1 : index")
        e(f"  %bs{k} = vector.addf {cur}, %sh{k} : {V8}")
        e(f"  %bd{k} = vector.subf %sh{k}, {cur} : {V8}")
        e(f"  %bf{k} = scf.select %up{k}, %bd{k}, %bs{k} : {V8}")
        cur = f"%bf{k}"
    if rotate:
        e("  %rsq = scalar.constant 0.08838834764831845 : f32")   # 1 / sqrt(128)
        e(f"  %rsq8 = vector.splat %rsq : {V8}")
        e(f"  %xr = vector.mulf {cur}, %rsq8 : {V8}")
    else:
        e(f"  %xr = vector.addf %xc, %zero8 : {V8}")
    e(f"  %xa = vector.absf %xr : {V8}")
    e("  %zero = scalar.constant 0.0 : f32")
    e(f"  %amax0 = vector.reduce<maxnumf> %xa, %zero : {V8}, f32")
    am = "%amax0"
    for k in (1, 2, 4, 8):
        e(f"  %ab{k} = scalar.bitcast {am} : f32 to i32")
        e(f"  %as{k}, %av{k} = kernel.subgroup.shuffle<xor> %ab{k}, %xk{k}, %x32 : i32, i32, i32")
        e(f"  %af{k} = scalar.bitcast %as{k} : i32 to f32")
        e(f"  %am{k} = scalar.maxnumf {am}, %af{k} : f32")
        am = f"%am{k}"
    e("  %r7 = scalar.constant 7.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e(f"  %s0 = scalar.divf {am}, %r7 : f32")
    e("  %spos = scalar.cmpf ogt, %s0, %zero : f32")
    e("  %s = scf.select %spos, %s0, %one : f32")
    e("  %inv = scalar.divf %one, %s : f32")
    e(f"  %inv8 = vector.splat %inv : {V8}")
    e(f"  %xq = vector.mulf %xr, %inv8 : {V8}")
    e(f"  %xn = vector.roundevenf %xq : {V8}")
    e("  %m15 = scalar.constant 15 : i32")
    nib = []
    for i in range(8):
        e(f"  %qe{i} = vector.extract %xn[{i}] : {V8} -> f32")
        e(f"  %qi{i} = scalar.fptosi %qe{i} : f32 to i32")
        e(f"  %qn{i} = scalar.andi %qi{i}, %m15 : i32")
        nib.append(f"%qn{i}")
    acc = None
    for j in range(4):
        e(f"  %sl{j}c = scalar.constant {8 * j} : i32")
        e(f"  %sh{j}c = scalar.constant {8 * j + 4} : i32")
        e(f"  %pl{j} = scalar.shli {nib[j]}, %sl{j}c : i32")
        e(f"  %ph{j} = scalar.shli {nib[j + 4]}, %sh{j}c : i32")
        e(f"  %pb{j} = scalar.ori %pl{j}, %ph{j} : i32")
        if acc is None:
            acc = f"%pb{j}"
        else:
            e(f"  %pa{j} = scalar.ori {acc}, %pb{j} : i32")
            acc = f"%pa{j}"
    e("  %zi = scalar.constant 0 : i32")
    e(f"  %wo = scf.select %live, {acc}, %zi : i32")
    e("  %da0 = index.mul %tokc, %c128 : index")
    e("  %da = index.add %da0, %lt : index")
    e("  view.store %wo, %d_flat[%da] : i32, view<[%dtot]xi32>")
    e("  %hh = index.div %lt, %c16 : index")
    e("  %isf = index.cmp eq, %l16, %c0 : index")
    e("  %so = scf.select %live, %s, %zero : f32")
    e("  %sa0 = index.mul %tokc, %c8 : index")
    e("  %sa = index.add %sa0, %hh : index")
    e("  scf.if %isf {")
    e("    view.store %so, %c_flat[%sa] : f32, view<[%sctot]xf32>")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_vq4():
    """yah_vq4 (kv4 configs): V^T as 15-level nibbles per channel per 16-token
    tile (per-channel per-tile range: attention error 3.5e-2 -> 2.1e-2 vs
    per-channel over the prompt): u = rne((v - c) / s) + 7, c = midrange,
    s = range / 14 (0 -> 1).
    Output vq4 [kv head][tile][256 dims] x 8 B (16 keys; in each dword nibble p
    holds key 2p (p < 4) or 2(p - 4) + 1, so (w >> 4k) & 0x000f000f | 0x64006400
    is the f16 pair 1024 + u for keys 2k, 2k + 1) and vqs [kv head][tile][256]
    (16 s, c - 23 s) as f16 pairs (one-fma dequant). Tokens >= token_count do not enter the range (keys the
    softmax masks). grid (4, ceil(cap / 16)) x 256 (lane = dim)."""
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (vq4) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@kvq_w32) @yah_vq4() {")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %c1 = index.constant 1 : index")
    e("  %c4 = index.constant 4 : index")
    e("  %c15 = index.constant 15 : index")
    e("  %c16 = index.constant 16 : index")
    e("  %c256 = index.constant 256 : index")
    e("  %t0 = index.add %cap, %c15 : index")
    e("  %tiles = index.div %t0, %c16 : index")
    e("  kernel.launch.config workgroups(%c4, %tiles, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %dst: buffer, %stat: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 15, 16, 256, 1024):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok0 = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %ntok = index.min %ntok0, %cap : index")
    e("  %p15 = index.add %cap, %c15 : index")
    e("  %tiles = index.div %p15, %c16 : index")
    e("  %stot = index.mul %cap, %c1024 : index")
    e("  %ttot0 = index.mul %tiles, %c1024 : index")      # 4 heads x 256 dims per tile
    e("  %dtot = index.mul %ttot0, %c2 : index")          # 2 dwords each
    e("  %s_na, %d_na, %t_na = buffer.assume.noalias %src, %dst, %stat : buffer, buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %d_flat = buffer.view %d_na[%base] : buffer -> view<[%dtot]xi32>")
    e("  %t_flat = buffer.view %t_na[%base] : buffer -> view<[%ttot0]xi32>")
    e("  %head = kernel.workgroup.id<x> : index")
    e("  %tile = kernel.workgroup.id<y> : index")
    e("  %d = kernel.workitem.id<x> : index")
    e("  %hb = index.mul %head, %c256 : index")
    e("  %col = index.add %hb, %d : index")
    e("  %t16 = index.mul %tile, %c16 : index")
    e("  %cap1 = index.sub %cap, %c1 : index")
    e("  %ntok1 = index.sub %ntok, %c1 : index")
    vals = []
    for j in range(16):
        e(f"  %tk{j}c = index.constant {j} : index")
        e(f"  %tk{j} = index.add %t16, %tk{j}c : index")
        e(f"  %tl{j} = index.min %tk{j}, %ntok1 : index")      # past the prompt: repeat its last token
        e(f"  %tc{j} = index.min %tl{j}, %cap1 : index")
        e(f"  %tm{j} = index.mul %tc{j}, %c1024 : index")
        e(f"  %ta{j} = index.add %tm{j}, %col : index")
        e(f"  %vh{j} = view.load %s_flat[%ta{j}] : view<[%stot]xf16> -> f16")
        e(f"  %v{j} = scalar.extf %vh{j} : f16 to f32")
        vals.append(f"%v{j}")
    mx, mn = vals[0], vals[0]
    for j in range(1, 16):
        e(f"  %mx{j} = scalar.maxnumf {mx}, {vals[j]} : f32")
        e(f"  %mn{j} = scalar.minnumf {mn}, {vals[j]} : f32")
        mx, mn = f"%mx{j}", f"%mn{j}"
    e("  %half = scalar.constant 0.5 : f32")
    e("  %r14 = scalar.constant 14.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e("  %zero = scalar.constant 0.0 : f32")
    e(f"  %sm = scalar.addf {mx}, {mn} : f32")
    e("  %cen = scalar.mulf %sm, %half : f32")
    e(f"  %rg = scalar.subf {mx}, {mn} : f32")
    e("  %s0 = scalar.divf %rg, %r14 : f32")
    e("  %spos = scalar.cmpf ogt, %s0, %zero : f32")
    e("  %s = scf.select %spos, %s0, %one : f32")
    # round the stats to f16 first: the attention dequantizes with the f16 values
    e("  %sh = scalar.fptrunc %s : f32 to f16")
    e("  %ch = scalar.fptrunc %cen : f32 to f16")
    e("  %sf = scalar.extf %sh : f16 to f32")
    e("  %cf = scalar.extf %ch : f16 to f32")
    e("  %inv = scalar.divf %one, %sf : f32")
    e("  %r7 = scalar.constant 7.0 : f32")
    e("  %r0 = scalar.constant 0.0 : f32")
    e("  %m15 = scalar.constant 15 : i32")
    us = []
    for j in range(16):
        e(f"  %xc{j} = scalar.subf {vals[j]}, %cf : f32")
        e(f"  %xs{j} = scalar.mulf %xc{j}, %inv : f32")
        e(f"  %xr{j} = scalar.roundevenf %xs{j} : f32")
        e(f"  %xo{j} = scalar.addf %xr{j}, %r7 : f32")
        e(f"  %xl{j} = scalar.maxnumf %xo{j}, %r0 : f32")
        e(f"  %xm{j} = scalar.minnumf %xl{j}, %r14 : f32")
        e(f"  %xu{j} = scalar.fptosi %xm{j} : f32 to i32")
        us.append(f"%xu{j}")
    words = []
    for w in range(2):
        acc = None
        for p in range(8):
            key = 8 * w + (2 * p if p < 4 else 2 * (p - 4) + 1)
            e(f"  %np{w}{p}c = scalar.constant {4 * p} : i32")
            e(f"  %np{w}{p} = scalar.shli {us[key]}, %np{w}{p}c : i32")
            if acc is None:
                acc = f"%np{w}{p}"
            else:
                e(f"  %na{w}{p} = scalar.ori {acc}, %np{w}{p} : i32")
                acc = f"%na{w}{p}"
        words.append(acc)
    e("  %ti0 = index.mul %head, %tiles : index")
    e("  %ti1 = index.add %ti0, %tile : index")
    e("  %ti2 = index.mul %ti1, %c256 : index")
    e("  %ti = index.add %ti2, %d : index")             # [head][tile][dim]
    e("  %da0 = index.mul %ti, %c2 : index")
    e("  %da1 = index.add %da0, %c1 : index")
    e(f"  view.store {words[0]}, %d_flat[%da0] : i32, view<[%dtot]xi32>")
    e(f"  view.store {words[1]}, %d_flat[%da1] : i32, view<[%dtot]xi32>")
    # the attention reads (S, C') = (16 s, c - 23 s): f16 1 + u/16 (bits
    # 0x3c00 | u << 6) times S plus C' is (u - 7) s + c in one fma
    e("  %r16 = scalar.constant 16.0 : f32")
    e("  %m23 = scalar.constant -23.0 : f32")
    e("  %S = scalar.mulf %sf, %r16 : f32")
    e("  %Cp = scalar.fmaf %sf, %m23, %cf : f32")
    e("  %Sh = scalar.fptrunc %S : f32 to f16")
    e("  %Cph = scalar.fptrunc %Cp : f32 to f16")
    e("  %pk = vector.from_elements %Sh, %Cph : vector<2xf16>")
    e("  %pkw = vector.bitcast %pk : vector<2xf16> to vector<1xi32>")
    e("  %pkd = vector.extract %pkw[0] : vector<1xi32> -> i32")
    e("  view.store %pkd, %t_flat[%ti] : i32, view<[%ttot0]xi32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def main():
    which = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else f"yah_{which}.loom"
    open(out, "w").write({"kmean": gen_kmean, "kq8": gen_kq8, "vstat": gen_vstat, "vq8": gen_vq8,
                          "kq4": gen_kq4, "vq4": gen_vq4}[which]())
    print(out)


if __name__ == "__main__":
    main()
