#!/usr/bin/env python3
"""Generate the tile GEMM: wave32, many waves, both operands staged in LDS.

usage: gen_gemm_tile.py <fmt> [out.loom]     env: YAH_TG_KIND=kstore|kres
                                                  YAH_TG_KSUB (default per format)

Same ABI, launch footprint (64 rows x 256 tokens per workgroup, dispatch.txt
"256 4 <B/256>") and output as gen_gemm_shared.py's kernels, and the same
decode arithmetic and per-accumulator MMA sequence, so the output is meant to be
bit-identical to them. What changes is the latency structure.

An ATT trace of the shared kStore put 70% of wave time in s_waitcnt: each wave
owns a 64x128 tile (32 wave64 accumulators, ~220 VGPRs), so only ~2 waves fit
per SIMD, and its MMA loop waits on its own activation loads from global memory
every K step. Here, as in HIP's HalfPrefillGemmKernel:

  * 8 wave32 waves per workgroup (2 along rows x 4 along tokens), each owning a
    32-row x 64-token tile: 8 wave32 accumulators;
  * per K phase the decoded weight tile (64 x KSUB) AND the activation tile
    (256 tokens x KSUB) sit in LDS, so the MMA loop reads only LDS;
  * the activation tile is loaded from global one phase ahead into registers
    (one 128-byte token row per lane), like the weight bytes, and stored to LDS
    at the start of the next phase.

MEASURED, NOT WIRED IN. Bit-identical (hidden f837e614ff55d1d1), 149 VGPRs, no
spills, 4 wave32 waves/SIMD by registers -- and slower than the shared kernel:
IQ4_XS kStore, 40 dispatches at pp2048, 366 ms shared vs 488 ms tile (1088-row
gate 15.7 -> 21.3 ms/dispatch; only the 1024-row shape improved, 2.5 -> 1.6).
With unroll(%c2) schedule(recurrence) on the K step: 457 ms. Its ATT trace moved
the stall from global to LDS: 62% of wave time in lgkmcnt waits right after the
fragment ds_load_b128s (12 per K step for 8 WMMAs, wave32 fragments carrying
duplicated half-waves), 15% at barriers. The skeleton is kept for the next
attempt: larger per-wave tiles, fewer duplicate LDS reads, or LDS-resident
weights with register-direct activations at wave32.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_gemm_shared as G  # noqa: E402

BN = 256          # tokens per workgroup
BM = 64           # rows per workgroup
WM, WN = 2, 4     # waves along rows x tokens
TM, TN = BM // WM, BN // WN   # per-wave tile: 32 rows x 64 tokens
FM, FN = TM // 16, TN // 16   # fragments per wave: 2 x 4
NWAVE = WM * WN
LANES = 32 * NWAVE
APAD = int(os.environ.get("YAH_TG_APAD", "8"))
# inner K-step loop policy, e.g. "unroll(%c2) schedule(recurrence)"
KPOL = os.environ.get("YAH_TG_KPOL", "")
# groups decoded per decoding lane (q4k's even/odd pairing needs 2)
GPL_OF = {"q4k": 2, "q5k": 2}
KSUB_OF = {"q4k": 128, "q5k": 128}


def configure(fmt):
    ksub = int(os.environ.get("YAH_TG_KSUB", KSUB_OF.get(fmt, 64)))
    G.KSUB = ksub
    G.PAD = 0
    G.ROWP = ksub
    G.PH = 256 // ksub
    G.GPP = ksub // 32
    G.GPL = GPL_OF.get(fmt, 1)
    G.LR = BM
    G.NW = NWAVE // 2          # table-staging stride 64*NW = LANES
    assert G.GPP % G.GPL == 0
    return ksub


def gen(fmt, kind="kstore"):
    F = G.FMTS[fmt]
    ksub = configure(fmt)
    bb, (loads, compute) = F["bb"], F["decode"]
    kr = kind == "kres"
    bufs = ["weight"] + F["extra"] + ["input"] + (["resid"] if kr else []) + ["wstage", "ostage", "output"]
    sym = f"yah_ffn_gemm_{fmt}" + ("_kres" if kr else "")
    slots = G.GPP // G.GPL          # decoding lane groups of 64 per phase
    arow = ksub + APAD              # f16 per LDS activation row
    aseg = ksub // 8                # 16-byte segments per token row
    V8 = "vector<8xf32>"
    VF = "vector<16xf16>"
    L = []
    e = L.append
    e(f"// GENERATED by tools/gen_gemm_tile.py {fmt} {kind} (KSUB={ksub}) -- edit the generator.")
    e("//")
    e(f"// Tile GEMM for {fmt}: 8 wave32 waves over a 64 x 256 tile, 32 x 64 per wave,")
    e("// decoded weights and staged activations both in LDS. See the generator.")
    e("amdgpu.target<gfx11-generic> @yah_tile_w32 {subgroup_size = 32}")
    e("")
    for c in ("m_tiles", "k_blocks", "token_tiles"):
        e(f"config.decl @{sym}.{c} : %value: index where [range(%value, 1, 4096)]")
    e("")
    e(f"kernel.def target(@yah_tile_w32) @{sym}() {{")
    e("  %unit = index.constant 1 : index")
    e(f"  %m_tiles = config.get @{sym}.m_tiles : index")
    e(f"  %token_tiles = config.get @{sym}.token_tiles : index")
    e(f"  %wgs = index.constant {LANES} : index")
    e("  %rowgrp = index.constant 4 : index")
    e("  %m_groups = index.div %m_tiles, %rowgrp : index")
    e("  kernel.launch.config workgroups(%m_groups, %token_tiles, %unit) workgroup_size(%wgs, %unit, %unit) : index")
    e("} launch(" + ", ".join(f"%{b}: buffer" for b in bufs) + ") {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 4, 6, 7, 8, 16, 32, 48, 63, 64, 80, 96, 112, 127, 128, 224, 255, 256, 512):
        e(f"  %c{v} = index.constant {v} : index")
    for v in (0, 1, 2, 3, 4, 5, 6, 7, 8, 14, 15, 16, 21, 24, 28, 32, 48, 63, 64, 66, 74, 104, 106, 127, 128, 192, 255):
        e(f"  %c{v}i = scalar.constant {v} : i32")
    e(f"  %cbb = index.constant {bb} : index")
    e(f"  %cbbh = index.constant {bb // 2} : index")
    e(f"  %cbbi = scalar.constant {bb} : i32")
    e(f"  %cwtok = index.constant {BN} : index")
    e(f"  %cksub = index.constant {ksub} : index")
    e(f"  %cph = index.constant {G.PH} : index")
    e(f"  %ccolmax = index.constant {ksub - 32} : index")
    e(f"  %cgppi = scalar.constant {G.GPP} : i32")
    e("  %m = index.constant 16 : index")
    e("  %n = index.constant 16 : index")
    e("  %k = index.constant 16 : index")
    e(f"  %m_tiles = config.get @{sym}.m_tiles : index")
    e(f"  %k_blocks = config.get @{sym}.k_blocks : index")
    e(f"  %token_tiles = config.get @{sym}.token_tiles : index")
    e("  %ktot = index.mul %k_blocks, %c256 : index")
    e("  %tokens = index.mul %token_tiles, %cwtok : index")
    e("  %m_rows = index.mul %m_tiles, %c16 : index")
    e("  %bpr = index.mul %k_blocks, %cbb : index")
    e("  %hpr = index.mul %k_blocks, %cbbh : index")
    e("  %w_bytes = index.mul %m_rows, %bpr : index")
    e("  %w_halfs = index.mul %m_rows, %hpr : index")
    e("  %w_last = index.sub %w_bytes, %c1 : index")
    e("  %w_lim = index.sub %w_bytes, %c16 : index")
    for nb in (4, 8, 16):
        e(f"  %cw{nb} = index.constant {nb} : index")
        e(f"  %w_lim{nb} = index.sub %w_bytes, %cw{nb} : index")
    e("  %w_half_last = index.sub %w_halfs, %c1 : index")
    e("  %out_total = index.mul %m_rows, %tokens : index")
    e("  %a_total = index.mul %tokens, %ktot : index")
    e("  %a_last8 = index.sub %a_total, %c8 : index")
    e("  %a_layout = encoding.layout.strided [%c1, %ktot] : encoding<layout>")
    e("  " + ", ".join(f"%{b}_na" for b in bufs) + " = buffer.assume.noalias "
      + ", ".join(f"%{b}" for b in bufs) + " : " + ", ".join(["buffer"] * len(bufs)))
    e("  %w_view = buffer.view %weight_na[%base] : buffer -> view<[%w_bytes]xi8>")
    e("  %w_f16_view = buffer.view %weight_na[%base] : buffer -> view<[%w_halfs]xf16>")
    e("  %a_flat = buffer.view %input_na[%base] : buffer -> view<[%a_total]xf16>")
    # LDS: decoded weight tile and staged activation tile
    e(f"  %wl_bytes = index.constant {BM * ksub * 2} : offset")
    e("  %wl = buffer.alloca<workgroup> align(16) %wl_bytes : buffer")
    e(f"  %wl_view = buffer.view %wl[%base] : buffer -> view<{BM}x{ksub}xf16>")
    e(f"  %al_bytes = index.constant {BN * arow * 2} : offset")
    e("  %al = buffer.alloca<workgroup> align(16) %al_bytes : buffer")
    e(f"  %al_rows = buffer.view %al[%base] : buffer -> view<{BN}x{arow}xf16>")
    e(f"  %carow = index.constant {arow} : index")
    e(f"  %cksubi = index.constant {ksub} : index")
    e("  %al_layout = encoding.layout.strided [%c1, %carow] : encoding<layout>")
    e(f"  %al_t = buffer.view %al[%base] : buffer -> view<{ksub}x{BN}xf16, %al_layout>")
    e("  %wg_x = kernel.workgroup.id<x> : index")
    e("  %wg_y = kernel.workgroup.id<y> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %wave = index.div %tid, %c32 : index")
    e(f"  %cwn = index.constant {WN} : index")
    e("  %wr = index.div %wave, %cwn : index")
    e("  %wt = index.rem %wave, %cwn : index")
    e("  %wg_row = index.mul %wg_x, %c64 : index")
    e(f"  %ctm = index.constant {TM} : index")
    e(f"  %ctn = index.constant {TN} : index")
    e("  %wr_off = index.mul %wr, %ctm : index")
    e("  %wt_off = index.mul %wt, %ctn : index")
    e("  %m_origin = index.add %wg_row, %wr_off : index")
    e("  %wtb = index.mul %wg_y, %cwtok : index")
    e("  %token_base = index.add %wtb, %wt_off : index")
    # decode lane map: lane tid -> weight row tid % 64, slot tid / 64 decodes
    # groups [slot*GPL, slot*GPL+GPL) of the phase; slots >= GPP/GPL idle.
    e("  %l64 = index.rem %tid, %c64 : index")
    e("  %slot = index.div %tid, %c64 : index")
    e("  %drow = index.min %l64, %c63 : index")
    e("  %drow_i = index.cast %drow : index to i32")
    e("  %wg_row_i = index.cast %wg_row : index to i32")
    e("  %grow_i = scalar.addi %wg_row_i, %drow_i : i32")
    e("  %k_blocks_i = index.cast %k_blocks : index to i32")
    e("  %bpr_i = scalar.muli %k_blocks_i, %cbbi : i32")
    e("  %row_off_i = scalar.muli %grow_i, %bpr_i : i32")
    e(f"  %cslots = index.constant {slots} : index")
    e("  %slot_c = index.min %slot, %cslots : index")
    e("  %decoder = index.cmp ult, %slot, %cslots : index")
    e("  %slot_i = index.cast %slot_c : index to i32")
    e(f"  %cgpl = scalar.constant {G.GPL} : i32")
    e("  %gl_i = scalar.muli %slot_i, %cgpl : i32")
    e("  %kphases = index.mul %k_blocks, %cph : index")
    # activation staging map: lane tid owns token row tid of the tile
    e(f"  %atok = index.min %tid, %c{BN - 1} : index")
    e("  %atok_g = index.add %wtb, %atok : index")
    e("  %arow_g = index.mul %atok_g, %ktot : index")
    L.extend(F["setup"]())
    e("  %z8s = scalar.constant 0 : i8")
    e("  %z8v = vector.splat %z8s : vector<8xi8>")
    e("  %zeros = vector.constant 0.0 : vector<8xf32>")
    e(f"  %init = vector.fragment<init> %zeros shape [%m, %n] : {V8}")
    NA = FM * FN
    types = ", ".join([V8] * NA)

    def a_loads(p, kbase):
        """This lane's token row of the next phase's activation tile, as aseg
        16-byte vectors (clamped: the extra iteration's loads are in bounds)."""
        vals = []
        for sg in range(aseg):
            e(f"    %{p}ao{sg} = index.add %arow_g, {kbase} : index")
            e(f"    %{p}ac{sg}0 = index.constant {8 * sg} : index")
            e(f"    %{p}aq{sg} = index.add %{p}ao{sg}, %{p}ac{sg}0 : index")
            e(f"    %{p}aqc{sg} = index.min %{p}aq{sg}, %a_last8 : index")
            e(f"    %{p}av{sg} = vector.load %a_flat[%{p}aqc{sg}] : view<[%a_total]xf16> -> vector<8xf16>")
            vals.append((f"%{p}av{sg}", "vector<8xf16>"))
        return vals

    # prefetch phase 0: weight bytes and activation row
    L0, wv0 = loads("pf_", "%row_off_i", "%gl_i")
    L.extend(L0)
    orig0 = wv0
    wv0 = G.pack_vals(e, wv0, "0")
    av0 = a_loads("pa_", "%c0")
    carried = wv0 + av0
    ca = ", ".join(f"%a{i} = %init : {V8}" for i in range(NA))
    ca += ", " + ", ".join(f"%cv{x} = {nm} : {ty}" for x, (nm, ty) in enumerate(carried))
    carried_t = types + ", " + ", ".join(ty for _, ty in carried)
    res = ", ".join(f"%acc{i}" for i in range(NA)) + ", " + ", ".join(f"%cvo{x}" for x in range(len(carried)))
    e("  " + res + f" = scf.for %kp = [%c0 to %kphases step %c1]({ca}) -> ({carried_t}) {{")
    e("    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("    %kb = index.div %kp, %cph : index")
    e("    %ph = index.rem %kp, %cph : index")
    e("    %ph_i = index.cast %ph : index to i32")
    e("    %phg_i = scalar.muli %ph_i, %cgppi : i32")
    e("    %gb_i = scalar.addi %phg_i, %gl_i : i32")
    e("    %kb_k = index.mul %kp, %cksub : index")
    cur_w = [(f"%cv{x}", ty) for x, (_, ty) in enumerate(wv0)]
    cur_a = [f"%cv{len(wv0) + x}" for x in range(len(av0))]
    # decode (only the decoding slots) into the weight tile
    e("    scf.if %decoder {")
    names = G.unpack_vals(e, cur_w, orig0)
    L.extend(compute(names, "%gb_i"))
    e("    }")
    # stage the activation row into the LDS activation tile
    for sg, nm in enumerate(cur_a):
        e(f"    %as{sg} = index.constant {8 * sg} : index")
        e(f"    vector.store {nm}, %al_rows[%atok, %as{sg}] : vector<8xf16>, view<{BN}x{arow}xf16>")
    # next phase's loads
    e("    %kp_n0 = index.add %kp, %c1 : index")
    e("    %kp_last = index.sub %kphases, %c1 : index")
    e("    %kp_n = index.min %kp_n0, %kp_last : index")
    e("    %kb_n = index.div %kp_n, %cph : index")
    e("    %ph_n = index.rem %kp_n, %cph : index")
    e("    %kb_ni = index.cast %kb_n : index to i32")
    e("    %ph_ni = index.cast %ph_n : index to i32")
    e("    %blk_off0n = scalar.muli %kb_ni, %cbbi : i32")
    e("    %blk_n = scalar.addi %row_off_i, %blk_off0n : i32")
    e("    %phg_n = scalar.muli %ph_ni, %cgppi : i32")
    e("    %gb_n = scalar.addi %phg_n, %gl_i : i32")
    Ln, nxt = loads("nx_", "%blk_n", "%gb_n")
    L.extend(Ln)
    nxt = G.pack_vals(e, nxt, "n")
    e("    %kk_n = index.mul %kp_n, %cksub : index")
    anx = a_loads("na_", "%kk_n")
    e("    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    cb = ", ".join(f"%b{i} = %a{i} : {V8}" for i in range(NA))
    e("    " + ", ".join(f"%r{i}" for i in range(NA)) + f" = scf.for %ks = [%c0 to %cksub step %c16]({cb}) -> ({types}) {KPOL} {{")
    for i in range(FM):
        e(f"      %lr{i} = index.add %wr_off, %c{16 * i} : index")
        e(f"      %lhs{i} = vector.fragment.load<lhs> %wl_view[%lr{i}, %ks] shape [%m, %k] : view<{BM}x{ksub}xf16> -> {VF}")
    for j in range(FN):
        e(f"      %tc{j} = index.add %wt_off, %c{16 * j} : index")
        e(f"      %rhs{j} = vector.fragment.load<rhs> %al_t[%ks, %tc{j}] shape [%k, %n] : view<{ksub}x{BN}xf16, %al_layout> -> {VF}")
    for i in range(FM):
        for j in range(FN):
            n = i * FN + j
            e(f"      %n{n} = vector.mma %lhs{i}, %rhs{j}, %b{n} : {VF}, {VF}, {V8}")
    e("      scf.yield " + ", ".join(f"%n{i}" for i in range(NA)) + f" : {types}")
    e("    }")
    e("    scf.yield " + ", ".join(f"%r{i}" for i in range(NA)) + ", "
      + ", ".join(nm for nm, _ in nxt + anx) + f" : {carried_t}")
    e("  }")
    e("  %out_layout = encoding.layout.strided [%c1, %m_rows] : encoding<layout>")
    e("  %out_t_view = buffer.view %output_na[%base] : buffer -> view<[%m_rows]x[%tokens]xf32, %out_layout>")
    if kr:
        e("  %res_t_view = buffer.view %resid_na[%base] : buffer -> view<[%m_rows]x[%tokens]xf32, %out_layout>")
    for i in range(FM):
        e(f"  %or{i} = index.add %m_origin, %c{16 * i} : index")
    for j in range(FN):
        e(f"  %ot{j} = index.add %token_base, %c{16 * j} : index")
    for i in range(FM):
        for j in range(FN):
            a = i * FN + j
            val = f"%acc{a}"
            if kr:
                e(f"  %rf{a} = vector.fragment.load<result> %res_t_view[%or{i}, %ot{j}] shape [%m, %n] : view<[%m_rows]x[%tokens]xf32, %out_layout> -> {V8}")
                e(f"  %rs{a} = vector.addf %rf{a}, %acc{a} : {V8}")
                val = f"%rs{a}"
            e(f"  vector.fragment.store<result> {val}, %out_t_view[%or{i}, %ot{j}] shape [%m, %n] : {V8}, view<[%m_rows]x[%tokens]xf32, %out_layout>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def main():
    fmt = sys.argv[1]
    kind = os.environ.get("YAH_TG_KIND", "kstore")
    out = sys.argv[2] if len(sys.argv) > 2 else f"yah_tile_{fmt}_{kind}.loom"
    open(out, "w").write(gen(fmt, kind))
    print(out)


if __name__ == "__main__":
    main()
