#!/usr/bin/env python3
"""Generate the fully unrolled fp16 output norm (the fused=0 form of
yah_half_norm_f16.loom) for one row width.

usage: gen_half_norm.py [out.loom] [dim=5120]

Same ABI, config and arithmetic as yah_half_norm_f16.loom with fused=0, in the
same order, so the output is bit-identical: one wave32 per row, lane l owns
elements l, l+32, ..., the sum of squares is ((0 + v0*v0) + v1*v1) + ... per
lane (mulf then addf, not fma) followed by the same subgroup reduction, and the
output is f16((v * inv) * w).

What differs is the schedule. The loop form issues a load, squares it and adds
it before the next iteration's load, then walks the row a second time; with one
wave per row that is ~160 dependent round trips per lane, and the kernel ran at
about half of HIP's HalfNorm5120, which moves 63 MB per 2048-row call at ~217 GB/s.
Unrolled, each lane issues all dim/32 loads up front, keeps the values in
registers (160 VGPRs at dim=5120, fine for a one-wave workgroup), and the second
pass reads nothing but the weight.
"""
import sys


def gen(dim=5120):
    assert dim % 32 == 0
    n = dim // 32
    L = []
    e = L.append
    e(f"// GENERATED by tools/gen_half_norm.py (dim={dim}) -- edit the generator.")
    e("// Fully unrolled fused=0 form of yah_half_norm_f16.loom; see the generator.")
    e("amdgpu.target<gfx11-generic> @yah_wave32 {subgroup_size = 32}")
    e("")
    e("config.decl @yah_half_norm.rows : %value: index where [range(%value, 1, 65536)]")
    e(f"config.decl @yah_half_norm.dim : %value: index where [range(%value, {dim}, {dim})]")
    e("config.def @yah_half_norm.eps = 0.0 : f32")
    e("config.def @yah_half_norm.fused = 0 : index")
    e("")
    e("kernel.def target(@yah_wave32) @yah_half_norm() {")
    e("  %unit = index.constant 1 : index")
    e("  %rows = config.get @yah_half_norm.rows : index")
    e("  %c32 = index.constant 32 : index")
    e("  kernel.launch.config workgroups(%rows, %unit, %unit) workgroup_size(%c32, %unit, %unit) : index")
    e("} launch(%x: buffer, %residual: buffer, %weight: buffer, %sum_out: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    e("  %zero = scalar.constant 0.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e(f"  %dim = index.constant {dim} : index")
    e("  %eps = config.get @yah_half_norm.eps : f32")
    e("  %rows = config.get @yah_half_norm.rows : index")
    e("  %total_elems = index.mul %rows, %dim : index")
    e("  %x_na, %weight_na, %out_na = buffer.assume.noalias %x, %weight, %out : buffer, buffer, buffer")
    e("  %x_view = buffer.view %x_na[%base] : buffer -> view<[%total_elems]xf32>")
    e("  %weight_view = buffer.view %weight_na[%base] : buffer -> view<[%dim]xf32>")
    e("  %out_view = buffer.view %out_na[%base] : buffer -> view<[%total_elems]xf16>")
    e("  %row = kernel.workgroup.id<x> : index")
    e("  %lane = kernel.workitem.id<x> : index")
    e("  %row_base = index.mul %row, %dim : index")
    e("  %lane_base = index.add %row_base, %lane : index")
    for k in range(n):
        e(f"  %o{k} = index.constant {32 * k} : index")
        e(f"  %a{k} = index.add %lane_base, %o{k} : index")
        e(f"  %x{k} = view.load %x_view[%a{k}] : view<[%total_elems]xf32> -> f32")
    s = "%zero"
    for k in range(n):
        e(f"  %q{k} = scalar.mulf %x{k}, %x{k} : f32")
        e(f"  %s{k} = scalar.addf {s}, %q{k} : f32")
        s = f"%s{k}"
    e(f"  %sum_sq = kernel.subgroup.reduce<addf> {s} : f32")
    e(f"  %dim_i = scalar.constant {dim} : i32")
    e("  %dim_f = scalar.sitofp %dim_i : i32 to f32")
    e("  %mean = scalar.divf %sum_sq, %dim_f : f32")
    e("  %shifted = scalar.addf %mean, %eps : f32")
    e("  %root = scalar.sqrtf %shifted : f32")
    e("  %inv = scalar.divf %one, %root : f32")
    # hold the first `keep` row values across the reduction and reload the
    # rest for the output pass (compile-report suggest: 230 VGPRs). Standalone
    # 2048x5120: all held 0.357 ms, keep 64 0.333, 56 0.328, 48 0.334 (192
    # VGPRs, the next tier), 32 0.340; a fence before the reloads 0.37-0.38.
    keep = int(__import__("os").environ.get("YAH_NORM_KEEP", "56" if dim == 5120 else str(n)))
    if keep < n and __import__("os").environ.get("YAH_NORM_FENCE", "0") == "1":
        e("  scf.schedule.fence")  # keep the reloads below the reduction
    for k in range(n):
        e(f"  %wi{k} = index.add %lane, %o{k} : index")
        e(f"  %w{k} = view.load %weight_view[%wi{k}] : view<[%dim]xf32> -> f32")
        xk = f"%x{k}"
        if k >= keep:
            # reloaded instead of held across the reduction (fewer VGPRs, one
            # more wave per SIMD: compile-report suggest); same value
            e(f"  %xr{k} = view.load %x_view[%a{k}] : view<[%total_elems]xf32> -> f32")
            xk = f"%xr{k}"
        e(f"  %nm{k} = scalar.mulf {xk}, %inv : f32")
        e(f"  %wt{k} = scalar.mulf %nm{k}, %w{k} : f32")
        e(f"  %h{k} = scalar.fptrunc %wt{k} : f32 to f16")
        e(f"  view.store %h{k}, %out_view[%a{k}] : f16, view<[%total_elems]xf16>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "yah_half_norm_unrolled.loom"
    dim = int(sys.argv[2]) if len(sys.argv) > 2 else 5120
    open(out, "w").write(gen(dim))
    print(out)


if __name__ == "__main__":
    main()
