#!/usr/bin/env python3
"""Generate yah_deltanet_regtile_f32.loom: the DeltaNet recurrence with the state
row resident in registers across the token loop.

usage: gen_deltanet_regtile.py            (writes ../yah_deltanet_regtile_f32.loom)

Same ABI, launch geometry (num_heads workgroups x 128 lanes, one lane per state
row) and f32 operation order as yah_deltanet_rowsplit_f32.loom, so the output is
meant to be bit-identical to it. What changes is where the state lives:

  rowsplit: the row is re-read and re-written every token, from global memory
            or (deltanet_lds_rewrite) from a 64 KiB LDS block -- two 128-step
            memory round trips per token on a one-wave-per-SIMD launch, ~51 ms
            per layer at B=2048.
  regtile:  the row is eight vector<16xf32> values carried by the token loop.
            It is loaded once before the loop and stored once after it; per token
            only k, q (as 16-wide vector loads) and the scalars touch memory.

The earlier register-resident attempt (deltanet_lds_rewrite's docstring) held
128 scalars and ran out of SGPRs giving each its own address; eight vectors need
eight addresses.

Order preservation, element by element:
  readout  u = ((0 + sa0*k0) + sa1*k1) + ...   sa_i = s_i*alpha, sequential in i
  update   s_i' = (s_i*alpha) + (dk*k_i)
The readout sum is spelled out as 128 scalar.addf in i order, because a vector
reduction would reassociate it. The elementwise products are vector ops, which
round each lane exactly as the scalar op does.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "yah_deltanet_regtile_f32.loom")
SRC = os.path.join(os.path.dirname(HERE), "yah_deltanet_rowsplit_f32.loom")
# Chunk width. k and q are wave-uniform, so a vector load of them lowers to a
# scalar load into W SGPRs; the scheduler issues several chunks' loads at once,
# and at W=16 that exhausted the 106-SGPR budget (peak 157) at B=512.
W = int(os.environ.get("YAH_DN_W", "8"))
CH = 128 // W
# Chunks per scalar-load group (0 = load each chunk right before its use).
# G=2: 43 -> 27 full lgkmcnt drains per token, 6.85 -> 5.58 ms per layer at
# pp2048, bit-identical; G=4 and up spill.
G = int(os.environ.get("YAH_DN_G", "2"))
VT = f"vector<{W}xf32>"

HEADER = """\
// GENERATED by tools/gen_deltanet_regtile.py -- edit the generator, not this file.
//
// YAH DeltaNet recurrence, register-resident state row. Same ABI, launch
// geometry, check cases and f32 operation order as yah_deltanet_rowsplit_f32.loom
// (whose header documents the arithmetic); the difference is that each lane's
// 128-key state row is carried through the token loop as eight vector<16xf32>
// values, loaded once before the loop and stored once after it, instead of being
// re-read and re-written through memory on every token.
//
// The readout sums are spelled out as scalar adds in key order so they round
// exactly as the rowsplit kernel's sequential loop does; the elementwise
// products and the state update are vector ops, which round per element exactly
// as the scalar ops do.
amdgpu.target<gfx11-generic> @yah_wave32 {subgroup_size = 32}

config.decl @yah_deltanet.batch : %value: index where [range(%value, 1, 1048576)]
config.decl @yah_deltanet.qkv_size : %value: index where [range(%value, 128, 1048576)]
config.decl @yah_deltanet.inner_size : %value: index where [range(%value, 128, 1048576)]
config.decl @yah_deltanet.num_key_heads : %value: index where [range(%value, 1, 4096)]
config.decl @yah_deltanet.num_heads : %value: index where [range(%value, 1, 4096)]

kernel.def target(@yah_wave32) @yah_deltanet() {
  %unit = index.constant 1 : index
  %c128 = index.constant 128 : index
  %num_heads = config.get @yah_deltanet.num_heads : index
  kernel.launch.config workgroups(%num_heads, %unit, %unit) workgroup_size(%c128, %unit, %unit) : index
} launch(%conv: buffer, %kq: buffer, %ab: buffer, %state: buffer, %out: buffer) {
  %base = index.constant 0 : offset
  %c0 = index.constant 0 : index
  %c1 = index.constant 1 : index
  %c2 = index.constant 2 : index
  %c3 = index.constant 3 : index
  %c128 = index.constant 128 : index
  %c16384 = index.constant 16384 : index
  %zero = scalar.constant 0.0 : f32
  %batch = config.get @yah_deltanet.batch : index
  %qkv_size = config.get @yah_deltanet.qkv_size : index
  %inner_size = config.get @yah_deltanet.inner_size : index
  %num_key_heads = config.get @yah_deltanet.num_key_heads : index
  %num_heads = config.get @yah_deltanet.num_heads : index
  %conv_total = index.mul %batch, %qkv_size : index
  %kq_total = index.mul %batch, %num_key_heads : index
  %kq_total3 = index.mul %kq_total, %c3 : index
  %ab_total = index.mul %batch, %num_heads : index
  %ab_total2 = index.mul %ab_total, %c2 : index
  %state_total = index.mul %num_heads, %c16384 : index
  %out_total = index.mul %batch, %inner_size : index
  %conv_noalias, %kq_noalias, %ab_noalias, %state_noalias, %out_noalias = buffer.assume.noalias %conv, %kq, %ab, %state, %out : buffer, buffer, buffer, buffer, buffer
  %conv_view = buffer.view %conv_noalias[%base] : buffer -> view<[%conv_total]xf32>
  %kq_view = buffer.view %kq_noalias[%base] : buffer -> view<[%kq_total3]xf32>
  %ab_view = buffer.view %ab_noalias[%base] : buffer -> view<[%ab_total2]xf32>
  %state_view = buffer.view %state_noalias[%base] : buffer -> view<[%state_total]xf32>
  %out_view = buffer.view %out_noalias[%base] : buffer -> view<[%out_total]xf32>
  %h = kernel.workgroup.id<x> : index
  %row = kernel.workitem.id<x> : index
  %kh = index.rem %h, %num_key_heads : index
  %state_base0 = index.mul %h, %c16384 : index
  %row_k = index.mul %row, %c128 : index
  %state_row = index.add %state_base0, %row_k : index
"""


def gen():
    L = []
    e = L.append
    for c in range(CH):
        e(f"  %co{c} = index.constant {c * W} : index")
    for c in range(CH):
        e(f"  %sa{c} = index.add %state_row, %co{c} : index")
        e(f"  %s_init{c} = vector.load %state_view[%sa{c}] : view<[%state_total]xf32> -> {VT}")
    carried = ", ".join(f"%s{c} = %s_init{c} : {VT}" for c in range(CH))
    results = ", ".join(f"%f{c}" for c in range(CH))
    types = ", ".join([VT] * CH)
    e(f"  {results} = scf.for %t = [%c0 to %batch step %c1]({carried}) -> ({types}) {{")
    body = f"""\
    %conv_t = index.mul %t, %qkv_size : index
    %q_row = index.mul %kh, %c128 : index
    %q_off = index.add %conv_t, %q_row : index
    %k_head = index.add %num_key_heads, %kh : index
    %k_row = index.mul %k_head, %c128 : index
    %k_off = index.add %conv_t, %k_row : index
    %v_heads = index.mul %num_key_heads, %c2 : index
    %v_head = index.add %v_heads, %h : index
    %v_row0 = index.mul %v_head, %c128 : index
    %v_off = index.add %conv_t, %v_row0 : index
    %v_off_row = index.add %v_off, %row : index
    %ab_t = index.mul %t, %num_heads : index
    %ab_h = index.add %ab_t, %h : index
    %ab_off = index.mul %ab_h, %c2 : index
    %ab_off1 = index.add %ab_off, %c1 : index
    %alpha = view.load %ab_view[%ab_off] : view<[%ab_total2]xf32> -> f32
    %beta = view.load %ab_view[%ab_off1] : view<[%ab_total2]xf32> -> f32
    %kq_t = index.mul %t, %num_key_heads : index
    %kq_base = index.add %kq_t, %kh : index
    %kq_off = index.mul %kq_base, %c3 : index
    %kq_off1 = index.add %kq_off, %c1 : index
    %kq_off2 = index.add %kq_off, %c2 : index
    %inv_k = view.load %kq_view[%kq_off] : view<[%kq_total3]xf32> -> f32
    %q_scale = view.load %kq_view[%kq_off1] : view<[%kq_total3]xf32> -> f32
    %kq3 = view.load %kq_view[%kq_off2] : view<[%kq_total3]xf32> -> f32
    %kq_dot = scalar.mulf %inv_k, %q_scale : f32
    %kq_dot2 = scalar.mulf %kq_dot, %kq3 : f32
    %v = view.load %conv_view[%v_off_row] : view<[%conv_total]xf32> -> f32
    %alpha_v = vector.splat %alpha : {VT}"""
    L.extend(body.split("\n"))
    # readout: products as vectors, sums as scalars in key order
    u, p = "%zero", "%zero"

    def rd_load(c):
        e(f"    %ko{c} = index.add %k_off, %co{c} : index")
        e(f"    %qo{c} = index.add %q_off, %co{c} : index")
        e(f"    %k{c} = vector.load %conv_view[%ko{c}] : view<[%conv_total]xf32> -> {VT}")
        e(f"    %q{c} = vector.load %conv_view[%qo{c}] : view<[%conv_total]xf32> -> {VT}")

    def rd_prod(c):
        e(f"    %sa_{c} = vector.mulf %s{c}, %alpha_v : {VT}")
        e(f"    %uk{c} = vector.mulf %sa_{c}, %k{c} : {VT}")
        e(f"    %pq{c} = vector.mulf %sa_{c}, %q{c} : {VT}")

    def rd_sum(c, u, p):
        for i in range(W):
            n = c * W + i
            e(f"    %ue{n} = vector.extract %uk{c}[{i}] : {VT} -> f32")
            e(f"    %pe{n} = vector.extract %pq{c}[{i}] : {VT} -> f32")
            e(f"    %u{n} = scalar.addf {u}, %ue{n} : f32")
            e(f"    %p{n} = scalar.addf {p}, %pe{n} : f32")
            u, p = f"%u{n}", f"%p{n}"
        return u, p

    if G == 0:
        for c in range(CH):
            rd_load(c)
            rd_prod(c)
            u, p = rd_sum(c, u, p)
    else:
        # k/q are wave-uniform, so they are scalar (SMEM) loads, and SMEM results
        # return out of order: a use waits for ALL outstanding scalar loads
        # (lgkmcnt(0)). Loaded chunk by chunk that was 39 full drains per token,
        # and issuing the next group before consuming this one only merged the
        # waits. So per group: the vector products touch the group's k/q (one
        # drain, only this group outstanding), THEN the next group's loads go
        # out, and the long dependent add chain runs while they are in flight.
        # Same ops, same order of the sums: bit-identical.
        groups = [list(range(c, min(c + G, CH))) for c in range(0, CH, G)]
        for c in groups[0]:
            rd_load(c)
        for gi, grp in enumerate(groups):
            e("    scf.schedule.fence")
            for c in grp:
                rd_prod(c)
            e("    scf.schedule.fence")
            if gi + 1 < len(groups):
                for c in groups[gi + 1]:
                    rd_load(c)
            e("    scf.schedule.fence")
            for c in grp:
                u, p = rd_sum(c, u, p)
    tail = f"""\
    %u_inv = scalar.mulf {u}, %inv_k : f32
    %v_minus = scalar.subf %v, %u_inv : f32
    %d = scalar.mulf %v_minus, %beta : f32
    %p_scaled = scalar.mulf {p}, %q_scale : f32
    %d_kq = scalar.mulf %d, %kq_dot2 : f32
    %o = scalar.addf %p_scaled, %d_kq : f32
    %out_t = index.mul %t, %inner_size : index
    %out_h = index.mul %h, %c128 : index
    %out_base = index.add %out_t, %out_h : index
    %out_idx = index.add %out_base, %row : index
    view.store %o, %out_view[%out_idx] : f32, view<[%out_total]xf32>
    %dk = scalar.mulf %d, %inv_k : f32
    %dk_v = vector.splat %dk : {VT}"""
    L.extend(tail.split("\n"))
    def up_load(c):
        e(f"    %kr{c} = vector.load %conv_view[%ko{c}] : view<[%conv_total]xf32> -> {VT}")

    def up_math(c):
        # s' = (s*alpha) + (dk*k). k is reloaded and s*alpha recomputed, as the
        # rowsplit update loop does: keeping the readout's copies live across the
        # scalar sums costs 256 extra VGPRs on top of the 128-register state and
        # the allocator gives up (spill-materialization-iteration-limit).
        e(f"    %sja{c} = vector.mulf %s{c}, %alpha_v : {VT}")
        e(f"    %kdk{c} = vector.mulf %dk_v, %kr{c} : {VT}")
        e(f"    %sn{c} = vector.addf %sja{c}, %kdk{c} : {VT}")

    if G == 0:
        for c in range(CH):
            up_load(c)
            up_math(c)
    else:
        # same discipline for the update: consume a group's k (one drain), then
        # issue the next group's loads before the rest of the arithmetic
        GU = max(G, 4)
        groups = [list(range(c, min(c + GU, CH))) for c in range(0, CH, GU)]
        for c in groups[0]:
            up_load(c)
        for gi, grp in enumerate(groups):
            e("    scf.schedule.fence")
            for c in grp:
                e(f"    %kdk{c} = vector.mulf %dk_v, %kr{c} : {VT}")
            e("    scf.schedule.fence")
            if gi + 1 < len(groups):
                for c in groups[gi + 1]:
                    up_load(c)
            e("    scf.schedule.fence")
            for c in grp:
                e(f"    %sja{c} = vector.mulf %s{c}, %alpha_v : {VT}")
                e(f"    %sn{c} = vector.addf %sja{c}, %kdk{c} : {VT}")
    e(f"    scf.yield {', '.join(f'%sn{c}' for c in range(CH))} : {types}")
    e("  }")
    for c in range(CH):
        e(f"  vector.store %f{c}, %state_view[%sa{c}] : {VT}, view<[%state_total]xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def cases():
    """The rowsplit kernel's check cases, verbatim: same ABI, same expectations."""
    text = open(SRC).read()
    start = text.index("// Requires --config=yah_deltanet.batch=2")
    return "\n" + text[start:]


def main():
    open(OUT, "w").write(HEADER + gen() + cases())
    print(OUT)


if __name__ == "__main__":
    main()
