#!/usr/bin/env python3
"""Generate the causal prefill attention kernel with H query heads per workgroup.

usage: gen_attn_heads.py <H> [out.loom]

Same ABI, symbol, config and per-row arithmetic as yah_attn_wmma_qb.loom, so the
output is bit-identical to it: every query head still gets its own 16-token
tile, the same QK WMMA chain over head tiles (K lhs, Q rhs), the same wave64
softmax over 64-key blocks (lane = key, the same subgroup reductions), the same
f16 P*V chain over key tiles and the same f16 running output, the same
full-block / 16-key tail split, the same epilogue.

What changes is what is shared. The source kernel ran one head per workgroup,
so each workgroup streamed its whole causal K/V range for 16 query rows: ~3.2 GB
of K/V reads per call at pp2048, served from MALL (the 8 MB of K/V does not fit
in L2). HIP's kernel shares each K/V tile across 64 rows. Here the H heads of a
workgroup belong to one GQA group (H divides gqa), so they read the same K/V:
each K fragment feeds H QK WMMAs and each staged V tile H P*V chains, and the
traffic falls by H. (More query tokens per workgroup would share K/V too, but it
moves the full-block / tail boundary for some tiles and so the softmax
numerics; heads do not.)

The full-block V tiles are staged transposed through LDS (vt[channel][key],
8 f16 of padding): a P*V value fragment is two contiguous ds_load_b128 per lane
instead of 16 two-byte global gathers from the row-major cache. The tail's
key/value stage aliases the V tile buffer: the tail loop only starts after the
last full-block barrier that orders the V tile's readers.

The launch grid is ((tokens+15)/16, num_heads/H); emit_prefill_pp.py records H in
dispatch.txt ("wmma.hal 16 <H> <tiles>") and loom_forward_pp reads it.
"""
import os
import sys

V4F = "vector<4xf32>"
V4H = "vector<4xf16>"
V8H = "vector<8xf16>"
V16H = "vector<16xf16>"


# PROW=1: probabilities staged row-major (row pitch 72 f16) so a P*V lhs
# fragment is two contiguous ds_load_b128 per lane; the key-major form (pitch 18,
# cheap softmax stores) made every fragment 16 ds_load_u16 gathers, re-read for
# each of the four output tiles: 32% of wave time at H=3. Same values.
PROW = os.environ.get("YAH_ATTN_PROW", "1") == "1"
# VPRE=1: V tile t+1 is loaded while tile t computes (tile 0 before QK)
VPRE = os.environ.get("YAH_ATTN_VPRE", "1") == "1"
PVIEW = "view<16x72xf16>" if PROW else "view<16x64xf16, %probability_transposed_layout>"


def gen(H):
    assert H in (1, 2, 3, 6)
    L = []
    e = L.append
    R = range(H)
    heads = ", ".join
    e(f"// GENERATED by tools/gen_attn_heads.py {H} -- edit the generator.")
    e(f"// Causal prefill attention, {H} query head(s) of one GQA group per workgroup,")
    e("// same per-row arithmetic as yah_attn_wmma_qb.loom. See the generator.")
    e("")
    e("amdgpu.target<gfx11-generic> @attention_prefill_gfx11_wave64 {subgroup_size = 64}")
    e("")
    e("config.def @attention_prefill.cache_capacity = 2048 : index")
    e("config.decl @attention_prefill.token_count : %value: index where [range(%value, 1, 2048)]")
    e("config.decl @attention_prefill.num_heads : %value: index where [range(%value, 1, 4096)]")
    e("config.decl @attention_prefill.num_kv_heads : %value: index where [range(%value, 1, 4096)]")
    e("config.decl @attention_prefill.gqa : %value: index where [range(%value, 1, 4096)]")
    e("config.decl @attention_prefill.head_dim : %value: index where [range(%value, 1, 1024)]")
    e("config.decl @attention_prefill.start_pos : %value: index where [range(%value, 0, 1073741824)]")
    e("")
    e("kernel.def target(@attention_prefill_gfx11_wave64) @yah_attn_wmma() {")
    e("  %token_count = config.get @attention_prefill.token_count : index")
    e("  %c1 = index.constant 1 : index")
    e("  %c15 = index.constant 15 : index")
    e("  %c16 = index.constant 16 : index")
    e("  %c24 = config.get @attention_prefill.num_heads : index")
    e(f"  %chpw = index.constant {H} : index")
    e("  %head_groups = index.div %c24, %chpw : index")
    e("  %c256 = config.get @attention_prefill.head_dim : index")
    e("  %padded_token_count = index.add %token_count, %c15 : index")
    e("  %query_tile_count = index.div %padded_token_count, %c16 : index")
    e("  kernel.launch.config workgroups(%query_tile_count, %head_groups, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%query: buffer, %gate: buffer, %key_cache: buffer, %value_cache: buffer, %output: buffer, %lse: buffer) {")
    e("  %cache_capacity = config.get @attention_prefill.cache_capacity : index")
    e("  %query_tile = kernel.workgroup.id<x> : index")
    e("  %head_group = kernel.workgroup.id<y> : index")
    e("  %workitem = kernel.workitem.id<x> : index")
    e("  %subgroup0 = kernel.subgroup.id : index")
    e("  %subgroup = index.assume %subgroup0 [range(%subgroup0, 0, 3)] : index")
    e("  %lane = kernel.subgroup.lane.id : index")
    for v in (0, 1, 2, 3, 4, 8, 15, 16, 32, 64, 1024):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %c6 = config.get @attention_prefill.gqa : index")
    e("  %c256 = config.get @attention_prefill.head_dim : index")
    e(f"  %chpw = index.constant {H} : index")
    e("  %c0_offset = index.constant 0 : offset")
    e("  %query_stage_bytes = index.constant 8448 : offset")
    e("  %score_stage_bytes = index.constant 4352 : offset")
    e("  %probability_stage_bytes = index.constant 2304 : offset")
    e("  %product_stage_bytes = index.constant 2048 : offset")
    e("  %vt_stage_bytes = index.constant 9216 : offset")
    e("  %c0_f16 = scalar.constant 0.0 : f16")
    e("  %c1_f32 = scalar.constant 1.0 : f32")
    e("  %attention_scale = scalar.constant 0.0625 : f32")
    e("  %negative_large = scalar.constant -1e+30 : f32")
    for r in range(4):
        e(f"  %output_zero{r} = vector.constant 0.0 : {V4H}")
    e(f"  %c0_f16x8 = vector.constant 0.0 : {V8H}")
    e(f"  %c0_f32x4 = vector.constant 0.0 : {V4F}")
    e(f"  %negative_f32x4 = vector.constant -1e+30 : {V4F}")
    e(f"  %one_f32x4 = vector.constant 1.0 : {V4F}")
    e(f"  %negone_f32x4 = vector.constant -1.0 : {V4F}")
    e("  %m = index.constant 16 : index")
    e("  %n = index.constant 16 : index")
    e("  %k = index.constant 16 : index")
    e("")
    e("  %token_count0 = config.get @attention_prefill.token_count : index")
    e("  %token_count = index.assume %token_count0 [range(%token_count0, 1, 2048)] : index")
    e("  %position_base0 = config.get @attention_prefill.start_pos : index")
    e("  %position_base = index.assume %position_base0 [range(%position_base0, 0, 262143)] : index")
    e("  %query_origin = index.mul %query_tile, %c16 : index")
    e("  %maximum_query_token0 = index.add %query_origin, %c15 : index")
    e("  %last_query_token = index.sub %token_count, %c1 : index")
    e("  %maximum_query_token = index.min %maximum_query_token0, %last_query_token : index")
    e("  %maximum_position = index.add %position_base, %maximum_query_token : index")
    e("  %context_count0 = index.add %maximum_position, %c1 : index")
    e("  %context_count = index.assume %context_count0 [range(%context_count0, 1, 262144), le(%context_count0, %cache_capacity)] : index")
    e("  %full_block_count = index.div %context_count, %c64 : index")
    e("  %full_context_count0 = index.mul %full_block_count, %c64 : index")
    e("  %full_context_count = index.assume %full_context_count0 [range(%full_context_count0, 0, 262144), mul(%full_context_count0, 64)] : index")
    e("  %first_head = index.mul %head_group, %chpw : index")
    for i in R:
        e(f"  %query_head_raw_{i} = index.add %first_head, %c{i} : index")
        e(f"  %query_head_{i} = index.assume %query_head_raw_{i} [range(%query_head_raw_{i}, 0, 23)] : index")
        e(f"  %query_head_base_{i} = index.mul %query_head_{i}, %c256 : index")
    e("  %key_value_head = index.div %query_head_0, %c6 : index")
    e("  %key_value_head_base = index.mul %key_value_head, %c256 : index")
    e("  %subgroup_score_column = index.mul %subgroup, %c16 : index")
    e("  %subgroup_query_row = index.mul %subgroup, %c4 : index")
    for r in range(4):
        e(f"  %query_row{r} = index.add %subgroup_query_row, %c{r} : index")
    for r in range(4):
        e(f"  %query_token{r} = index.add %query_origin, %query_row{r} : index")
    for r in range(4):
        e(f"  %query_valid{r} = index.cmp ult, %query_token{r}, %token_count : index")
    for r in range(4):
        e(f"  %query_position{r} = index.add %position_base, %query_token{r} : index")
    e("  %subgroup_product_channel = index.mul %subgroup, %c16 : index")
    e("  %lane_output_tile = index.div %lane, %c16 : index")
    e("  %lane_product_channel0 = index.rem %lane, %c16 : index")
    e("  %lane_product_channel = index.mul %lane_product_channel0, %c4 : index")
    e("  %lane_output_channel = index.mul %lane, %c4 : index")
    e("")
    e("  %query_transposed_layout = encoding.layout.strided [1, 264] : encoding<layout>")
    e("  %probability_transposed_layout = encoding.layout.strided [1, 18] : encoding<layout>")
    e("  %vt_layout = encoding.layout.strided [1, 72] : encoding<layout>")
    e("  %query_noalias, %gate_noalias, %key_noalias, %value_noalias, %output_noalias = buffer.assume.noalias %query, %gate, %key_cache, %value_cache, %output : buffer, buffer, buffer, buffer, buffer")
    e("  %query_view = buffer.view %query_noalias[%c0_offset] : buffer -> view<[%token_count]x6144xf32>")
    e("  %gate_view = buffer.view %gate_noalias[%c0_offset] : buffer -> view<[%token_count]x6144xf32>")
    e("  %key_view = buffer.view %key_noalias[%c0_offset] : buffer -> view<[%cache_capacity]x1024xf16>")
    e("  %value_view = buffer.view %value_noalias[%c0_offset] : buffer -> view<[%cache_capacity]x1024xf16>")
    e("  %output_view = buffer.view %output_noalias[%c0_offset] : buffer -> view<[%token_count]x6144xf32>")
    for i in R:
        e(f"  %query_stage_{i} = buffer.alloca<workgroup> align(16) %query_stage_bytes : buffer")
        e(f"  %score_stage_{i} = buffer.alloca<workgroup> align(16) %score_stage_bytes : buffer")
        e(f"  %probability_stage_{i} = buffer.alloca<workgroup> align(16) %probability_stage_bytes : buffer")
        e(f"  %product_stage_{i} = buffer.alloca<workgroup> align(16) %product_stage_bytes : buffer")
        e(f"  %query_stage_view_{i} = buffer.view %query_stage_{i}[%c0_offset] : buffer -> view<16x264xf16>")
        e(f"  %query_transposed_view_{i} = buffer.view %query_stage_{i}[%c0_offset] : buffer -> view<256x16xf16, %query_transposed_layout>")
        e(f"  %score_stage_view_{i} = buffer.view %score_stage_{i}[%c0_offset] : buffer -> view<64x17xf32>")
        e(f"  %probability_stage_view_{i} = buffer.view %probability_stage_{i}[%c0_offset] : buffer -> {PVIEW}")
        e(f"  %product_stage_view_{i} = buffer.view %product_stage_{i}[%c0_offset] : buffer -> view<16x64xf16>")
    e("  %vt_stage = buffer.alloca<workgroup> align(16) %vt_stage_bytes : buffer")
    e("  %vt_store_view = buffer.view %vt_stage[%c0_offset] : buffer -> view<64x72xf16>")
    e("  %vt_fragment_view = buffer.view %vt_stage[%c0_offset] : buffer -> view<64x64xf16, %vt_layout>")
    e("  %tail_key_value_stage_view = buffer.view %vt_stage[%c0_offset] : buffer -> view<16x264xf16>")
    e("  %vt_pair = index.rem %workitem, %c32 : index")
    e("  %vt_key0 = index.mul %vt_pair, %c2 : index")
    e("  %vt_segment = index.div %workitem, %c32 : index")
    e("  %vt_channel0 = index.mul %vt_segment, %c8 : index")
    for c in range(8):
        e(f"  %vc{c} = index.constant {c} : index")
    e("")
    # Q: scale and truncate once, per head
    for i in R:
        e("  scf.for %load_iteration = [%c0 to %c16 step %c1] unroll {")
        e("    %linear = index.madd %load_iteration, %c256, %workitem : index")
        e("    %local_query_row = index.div %linear, %c256 : index")
        e("    %query_channel = index.rem %linear, %c256 : index")
        e("    %query_token = index.add %query_origin, %local_query_row : index")
        e("    %query_valid = index.cmp ult, %query_token, %token_count : index")
        e("    %query_value = scf.if %query_valid -> (f16) {")
        e("      %bounded_query_token = index.assume %query_token [lt(%query_token, %token_count)] : index")
        e(f"      %global_query_channel = index.add %query_head_base_{i}, %query_channel : index")
        e("      %loaded = view.load %query_view[%bounded_query_token, %global_query_channel] : view<[%token_count]x6144xf32> -> f32")
        e("      %scaled = scalar.mulf<reassoc|nnan|ninf|nsz|contract> %loaded, %attention_scale : f32")
        e("      %truncated = scalar.fptrunc %scaled : f32 to f16")
        e("      scf.yield %truncated : f16")
        e("    } else {")
        e("      scf.yield %c0_f16 : f16")
        e("    }")
        e(f"    view.store %query_value, %query_stage_view_{i}[%local_query_row, %query_channel] : f16, view<16x264xf16>")
        e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("")

    def state_names(prefix):
        out = []
        for i in R:
            out += [f"%{prefix}max_{i}", f"%{prefix}sum_{i}"] + [f"%{prefix}output{r}_{i}" for r in range(4)]
        return out

    def state_types():
        return ", ".join(([V4F, V4F] + [V4H] * 4) * H)

    def softmax(i, score_view, valid, sfx):
        """Per head: masked scores -> online max/sum update, P to LDS. Emits the
        same ops as the source kernel's full-block (sfx='') / tail ('tail_') form."""
        for r in range(4):
            e(f"    %{sfx}raw_score{r}_{i} = view.load {score_view}[%lane, %query_row{r}] : view<64x17xf32> -> f32")
        e(f"    %{sfx}raw_scores_{i} = vector.from_elements " + ", ".join(f"%{sfx}raw_score{r}_{i}" for r in range(4)) + f" : {V4F}")
        e(f"    %{sfx}masked_scores_{i} = vector.select {valid}, %{sfx}raw_scores_{i}, %negative_f32x4 : {V4F}")
        e(f"    %{sfx}block_max_{i} = kernel.subgroup.reduce<maxnumf> %{sfx}masked_scores_{i} : {V4F}")
        e(f"    %{sfx}next_max_{i} = vector.maxnumf %current_max_{i}, %{sfx}block_max_{i} : {V4F}")
        e(f"    %{sfx}score_delta_{i} = vector.subf<reassoc|nnan|nsz> %{sfx}masked_scores_{i}, %{sfx}next_max_{i} : {V4F}")
        e(f"    %{sfx}raw_probability_{i} = vector.expf<afn> %{sfx}score_delta_{i} : {V4F}")
        e(f"    %{sfx}probability_{i} = vector.select {valid}, %{sfx}raw_probability_{i}, %c0_f32x4 : {V4F}")
        e(f"    %{sfx}block_sum_{i} = kernel.subgroup.reduce<addf> %{sfx}probability_{i} : {V4F}")
        e(f"    %{sfx}old_delta_{i} = vector.subf<reassoc|nnan|ninf|nsz> %current_max_{i}, %{sfx}next_max_{i} : {V4F}")
        e(f"    %{sfx}old_scale_{i} = vector.expf<afn> %{sfx}old_delta_{i} : {V4F}")
        e(f"    %{sfx}scaled_current_sum_{i} = vector.mulf<reassoc|nnan|ninf|nsz|contract> %current_sum_{i}, %{sfx}old_scale_{i} : {V4F}")
        e(f"    %{sfx}next_sum_{i} = vector.addf<reassoc|nnan|ninf|nsz> %{sfx}scaled_current_sum_{i}, %{sfx}block_sum_{i} : {V4F}")
        e(f"    %{sfx}probability_f16_{i} = vector.fptrunc %{sfx}probability_{i} : {V4F} to {V4H}")
        for r in range(4):
            e(f"    %{sfx}probability{r}_{i} = vector.extract %{sfx}probability_f16_{i}[{r}] : {V4H} -> f16")
        for r in range(4):
            e(f"    view.store %{sfx}probability{r}_{i}, %probability_stage_view_{i}[%query_row{r}, %lane] : f16, {PVIEW}")

    def rescale(i, sfx):
        e(f"    %{sfx}old_scale_f16_{i} = vector.fptrunc %{sfx}old_scale_{i} : {V4F} to {V4H}")
        for r in range(4):
            e(f"    %{sfx}old_scale{r}_scalar_{i} = vector.extract %{sfx}old_scale_f16_{i}[{r}] : {V4H} -> f16")
        for r in range(4):
            e(f"    %{sfx}old_scale{r}_{i} = vector.splat %{sfx}old_scale{r}_scalar_{i} : {V4H}")
        for r in range(4):
            e(f"    %{sfx}scaled_current_output{r}_{i} = vector.mulf<reassoc|nnan|ninf|nsz|contract> %current_output{r}_{i}, %{sfx}old_scale{r}_{i} : {V4H}")

    def accumulate(sfx):
        """Owners of this output tile add the block products of every head."""
        outs = [f"%{sfx}updated_output{r}_{i}" for i in R for r in range(4)]
        e("      %owns_output_tile = index.cmp eq, %lane_output_tile, %output_tile : index")
        e(f"      {heads(outs)} = scf.if %owns_output_tile -> ({', '.join([V4H] * 4 * H)}) {{")
        ys = []
        for i in R:
            for r in range(4):
                e(f"        %block_output{r}_{i} = vector.load %product_stage_view_{i}[%query_row{r}, %lane_product_channel] : view<16x64xf16> -> {V4H}")
            for r in range(4):
                e(f"        %updated_tile_output{r}_{i} = vector.addf<reassoc|nnan|ninf|nsz> %tile_output{r}_{i}, %block_output{r}_{i} : {V4H}")
                ys.append(f"%updated_tile_output{r}_{i}")
        e(f"        scf.yield {heads(ys)} : {', '.join([V4H] * 4 * H)}")
        e("      } else {")
        e(f"        scf.yield {heads(f'%tile_output{r}_{i}' for i in R for r in range(4))} : {', '.join([V4H] * 4 * H)}")
        e("      }")
        return outs

    def vt_load(tile, p):
        """This lane's two 16-byte rows of V tile `tile` of the block at %key_origin."""
        e(f"      %{p}ch_t = index.mul {tile}, %c64 : index")
        e(f"      %{p}ch_b = index.add %key_value_head_base, %{p}ch_t : index")
        e(f"      %{p}ch = index.add %{p}ch_b, %vt_channel0 : index")
        e(f"      %{p}a = vector.load %value_view[%vt_token_a, %{p}ch] : view<[%cache_capacity]x1024xf16> -> {V8H}")
        e(f"      %{p}b = vector.load %value_view[%vt_token_b, %{p}ch] : view<[%cache_capacity]x1024xf16> -> {V8H}")

    # ---- full 64-key blocks
    init = []
    for i in R:
        init += [f"%current_max_{i} = %negative_f32x4 : {V4F}", f"%current_sum_{i} = %c0_f32x4 : {V4F}"]
        init += [f"%current_output{r}_{i} = %output_zero{r} : {V4H}" for r in range(4)]
    e(f"  {heads(state_names('full_'))} = scf.for %key_origin = [%c0 to %full_context_count step %c64]({heads(init)}) -> ({state_types()}) {{")
    e("    %vt_token_a = index.add %key_origin, %vt_key0 : index")
    e("    %vt_token_b = index.add %vt_token_a, %c1 : index")
    # V tile 0 of this block goes out before QK and softmax, which cover it;
    # each tile then prefetches the next (VPRE=0: load at the tile, as before)
    if VPRE:
        vt_load("%c0", "vpre0_")
    e("    %score_key_origin0 = index.add %key_origin, %subgroup_score_column : index")
    e("    %last_full_key_tile_start = index.sub %context_count, %c15 : index")
    e("    %score_key_origin = index.assume %score_key_origin0 [lt(%score_key_origin0, %last_full_key_tile_start)] : index")
    e(f"    %score_init_values = vector.constant 0.0 : {V4F}")
    e(f"    %score_init = vector.fragment<init> %score_init_values shape [%m, %n] : {V4F}")
    accs = ", ".join(f"%score_accumulator_{i} = %score_init : {V4F}" for i in R)
    e(f"    {heads(f'%score_fragment_{i}' for i in R)} = scf.for %head_tile = [%c0 to %c256 step %c16]({accs}) -> ({', '.join([V4F] * H)}) unroll schedule(recurrence) {{")
    e("      %key_channel = index.add %key_value_head_base, %head_tile : index")
    e(f"      %key_fragment = vector.fragment.load<lhs> %key_view[%score_key_origin, %key_channel] shape [%m, %k] : view<[%cache_capacity]x1024xf16> -> {V16H}")
    for i in R:
        e(f"      %query_fragment_{i} = vector.fragment.load<rhs> %query_transposed_view_{i}[%head_tile, %c0] shape [%k, %n] : view<256x16xf16, %query_transposed_layout> -> {V16H}")
        e(f"      %next_score_accumulator_{i} = vector.mma %key_fragment, %query_fragment_{i}, %score_accumulator_{i} : {V16H}, {V16H}, {V4F}")
    e(f"      scf.yield {heads(f'%next_score_accumulator_{i}' for i in R)} : {', '.join([V4F] * H)}")
    e("    }")
    for i in R:
        e(f"    vector.fragment.store<result> %score_fragment_{i}, %score_stage_view_{i}[%subgroup_score_column, %c0] shape [%m, %n] : {V4F}, view<64x17xf32>")
    e("    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("    %key_token = index.add %key_origin, %lane : index")
    for r in range(4):
        e(f"    %causal{r} = index.cmp ule, %key_token, %query_position{r} : index")
    for r in range(4):
        e(f"    %valid{r} = scalar.andi %query_valid{r}, %causal{r} : i1")
    e("    %valid = vector.from_elements %valid0, %valid1, %valid2, %valid3 : vector<4xi1>")
    for i in R:
        softmax(i, f"%score_stage_view_{i}", "%valid", "")
    e("    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    for i in R:
        rescale(i, "")
    tinit = heads(f"%tile_output{r}_{i} = %scaled_current_output{r}_{i} : {V4H}" for i in R for r in range(4))
    touts = [f"%next_output{r}_{i}" for i in R for r in range(4)]
    if VPRE:
        tinit += f", %vt_a = %vpre0_a : {V8H}, %vt_b = %vpre0_b : {V8H}"
        ttypes = ", ".join([V4H] * 4 * H + [V8H, V8H])
        touts_all = touts + ["%vt_a_last", "%vt_b_last"]
    else:
        ttypes = ", ".join([V4H] * 4 * H)
        touts_all = touts
    e(f"    {heads(touts_all)} = scf.for %output_tile = [%c0 to %c4 step %c1]({tinit}) -> ({ttypes}) unroll {{")
    if not VPRE:
        vt_load("%output_tile", "vt_")
    for c in range(8):
        e(f"      %vt_a{c} = vector.extract %vt_a[{c}] : {V8H} -> f16")
        e(f"      %vt_b{c} = vector.extract %vt_b[{c}] : {V8H} -> f16")
        e(f"      %vt_p{c} = vector.from_elements %vt_a{c}, %vt_b{c} : vector<2xf16>")
        e(f"      %vt_row{c} = index.add %vt_channel0, %vc{c} : index")
        e(f"      vector.store %vt_p{c}, %vt_store_view[%vt_row{c}, %vt_key0] : vector<2xf16>, view<64x72xf16>")
    e("      kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    if VPRE:
        e("      %vt_next0 = index.add %output_tile, %c1 : index")
        e("      %vt_next = index.min %vt_next0, %c3 : index")
        vt_load("%vt_next", "vtn_")
    e(f"      %product_init = vector.fragment<init> %c0_f16x8 shape [%m, %n] : {V8H}")
    pacc = ", ".join(f"%product_accumulator_{i} = %product_init : {V8H}" for i in R)
    e(f"      {heads(f'%product_fragment_{i}' for i in R)} = scf.for %key_tile = [%c0 to %c64 step %c16]({pacc}) -> ({', '.join([V8H] * H)}) unroll schedule(recurrence) {{")
    e(f"        %value_fragment = vector.fragment.load<rhs> %vt_fragment_view[%key_tile, %subgroup_product_channel] shape [%k, %n] : view<64x64xf16, %vt_layout> -> {V16H}")
    for i in R:
        e(f"        %probability_fragment_{i} = vector.fragment.load<lhs> %probability_stage_view_{i}[%c0, %key_tile] shape [%m, %k] : {PVIEW} -> {V16H}")
        e(f"        %next_product_accumulator_{i} = vector.mma %probability_fragment_{i}, %value_fragment, %product_accumulator_{i} : {V16H}, {V16H}, {V8H}")
    e(f"        scf.yield {heads(f'%next_product_accumulator_{i}' for i in R)} : {', '.join([V8H] * H)}")
    e("      }")
    for i in R:
        e(f"      vector.fragment.store<result> %product_fragment_{i}, %product_stage_view_{i}[%c0, %subgroup_product_channel] shape [%m, %n] : {V8H}, view<16x64xf16>")
    e("      kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    outs = accumulate("")
    # no barrier here: the next tile's staging barrier orders the product and
    # V-tile reuse (every reader passed the product-store barrier first)
    if VPRE:
        e(f"      scf.yield {heads(outs + ['%vtn_a', '%vtn_b'])} : {ttypes}")
    else:
        e(f"      scf.yield {heads(outs)} : {ttypes}")
    e("    }")
    ys = []
    for i in R:
        ys += [f"%next_max_{i}", f"%next_sum_{i}"] + [f"%next_output{r}_{i}" for r in range(4)]
    e(f"    scf.yield {heads(ys)} : {state_types()}")
    e("  }")
    e("")
    # ---- 16-key tail
    e("  %tail_score_wave = index.cmp eq, %subgroup, %c0 : index")
    tinit = []
    for i in R:
        tinit += [f"%current_max_{i} = %full_max_{i} : {V4F}", f"%current_sum_{i} = %full_sum_{i} : {V4F}"]
        tinit += [f"%current_output{r}_{i} = %full_output{r}_{i} : {V4H}" for r in range(4)]
    e(f"  {heads(state_names('final_'))} = scf.for %tail_key_origin = [%full_context_count to %context_count step %c16]({heads(tinit)}) -> ({state_types()}) {{")
    e("    %tail_remaining = index.sub %context_count, %tail_key_origin : index")
    e("    %tail_key_count = index.min %tail_remaining, %c16 : index")
    for what, view in (("key", "%key_view"),):
        pass
    e("    scf.for %load_iteration = [%c0 to %c16 step %c1] unroll {")
    e("      %linear = index.madd %load_iteration, %c256, %workitem : index")
    e("      %tail_key_row = index.div %linear, %c256 : index")
    e("      %tail_key_channel = index.rem %linear, %c256 : index")
    e("      %tail_key_valid = index.cmp ult, %tail_key_row, %tail_key_count : index")
    e("      %tail_key_value = scf.if %tail_key_valid -> (f16) {")
    e("        %tail_key_token0 = index.add %tail_key_origin, %tail_key_row : index")
    e("        %tail_key_token = index.assume %tail_key_token0 [lt(%tail_key_token0, %context_count)] : index")
    e("        %global_key_channel = index.add %key_value_head_base, %tail_key_channel : index")
    e("        %loaded = view.load %key_view[%tail_key_token, %global_key_channel] : view<[%cache_capacity]x1024xf16> -> f16")
    e("        scf.yield %loaded : f16")
    e("      } else {")
    e("        scf.yield %c0_f16 : f16")
    e("      }")
    e("      view.store %tail_key_value, %tail_key_value_stage_view[%tail_key_row, %tail_key_channel] : f16, view<16x264xf16>")
    e("    }")
    e("    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("    scf.if %tail_score_wave {")
    e(f"      %tail_score_init_values = vector.constant 0.0 : {V4F}")
    e(f"      %tail_score_init = vector.fragment<init> %tail_score_init_values shape [%m, %n] : {V4F}")
    accs = ", ".join(f"%score_accumulator_{i} = %tail_score_init : {V4F}" for i in R)
    e(f"      {heads(f'%tail_score_fragment_{i}' for i in R)} = scf.for %head_tile = [%c0 to %c256 step %c16]({accs}) -> ({', '.join([V4F] * H)}) unroll schedule(recurrence) {{")
    e(f"        %key_fragment = vector.fragment.load<lhs> %tail_key_value_stage_view[%c0, %head_tile] shape [%m, %k] : view<16x264xf16> -> {V16H}")
    for i in R:
        e(f"        %query_fragment_{i} = vector.fragment.load<rhs> %query_transposed_view_{i}[%head_tile, %c0] shape [%k, %n] : view<256x16xf16, %query_transposed_layout> -> {V16H}")
        e(f"        %next_score_accumulator_{i} = vector.mma %key_fragment, %query_fragment_{i}, %score_accumulator_{i} : {V16H}, {V16H}, {V4F}")
    e(f"        scf.yield {heads(f'%next_score_accumulator_{i}' for i in R)} : {', '.join([V4F] * H)}")
    e("      }")
    for i in R:
        e(f"      vector.fragment.store<result> %tail_score_fragment_{i}, %score_stage_view_{i}[%c0, %c0] shape [%m, %n] : {V4F}, view<64x17xf32>")
    e("    }")
    e("    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("    %tail_lane_valid = index.cmp ult, %lane, %tail_key_count : index")
    e("    %tail_key_token = index.add %tail_key_origin, %lane : index")
    for r in range(4):
        e(f"    %tail_causal{r} = index.cmp ule, %tail_key_token, %query_position{r} : index")
    for r in range(4):
        e(f"    %tail_valid_query{r} = scalar.andi %query_valid{r}, %tail_causal{r} : i1")
    for r in range(4):
        e(f"    %tail_valid{r} = scalar.andi %tail_lane_valid, %tail_valid_query{r} : i1")
    e("    %tail_valid = vector.from_elements %tail_valid0, %tail_valid1, %tail_valid2, %tail_valid3 : vector<4xi1>")
    for i in R:
        softmax(i, f"%score_stage_view_{i}", "%tail_valid", "tail_")
    e("    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("    scf.for %load_iteration = [%c0 to %c16 step %c1] unroll {")
    e("      %linear = index.madd %load_iteration, %c256, %workitem : index")
    e("      %tail_value_row = index.div %linear, %c256 : index")
    e("      %tail_value_channel = index.rem %linear, %c256 : index")
    e("      %tail_value_valid = index.cmp ult, %tail_value_row, %tail_key_count : index")
    e("      %tail_value = scf.if %tail_value_valid -> (f16) {")
    e("        %tail_value_token0 = index.add %tail_key_origin, %tail_value_row : index")
    e("        %tail_value_token = index.assume %tail_value_token0 [lt(%tail_value_token0, %context_count)] : index")
    e("        %global_value_channel = index.add %key_value_head_base, %tail_value_channel : index")
    e("        %loaded = view.load %value_view[%tail_value_token, %global_value_channel] : view<[%cache_capacity]x1024xf16> -> f16")
    e("        scf.yield %loaded : f16")
    e("      } else {")
    e("        scf.yield %c0_f16 : f16")
    e("      }")
    e("      view.store %tail_value, %tail_key_value_stage_view[%tail_value_row, %tail_value_channel] : f16, view<16x264xf16>")
    e("    }")
    e("    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    for i in R:
        rescale(i, "tail_")
    tinit = heads(f"%tile_output{r}_{i} = %tail_scaled_current_output{r}_{i} : {V4H}" for i in R for r in range(4))
    touts = [f"%tail_next_output{r}_{i}" for i in R for r in range(4)]
    e(f"    {heads(touts)} = scf.for %output_tile = [%c0 to %c4 step %c1]({tinit}) -> ({', '.join([V4H] * 4 * H)}) unroll {{")
    e("      %output_tile_channel = index.mul %output_tile, %c64 : index")
    e("      %value_channel = index.add %output_tile_channel, %subgroup_product_channel : index")
    e(f"      %product_init = vector.fragment<init> %c0_f16x8 shape [%m, %n] : {V8H}")
    pacc = ", ".join(f"%product_accumulator_{i} = %product_init : {V8H}" for i in R)
    e(f"      {heads(f'%product_fragment_{i}' for i in R)} = scf.for %key_tile = [%c0 to %c16 step %c16]({pacc}) -> ({', '.join([V8H] * H)}) unroll schedule(recurrence) {{")
    e(f"        %value_fragment = vector.fragment.load<rhs> %tail_key_value_stage_view[%key_tile, %value_channel] shape [%k, %n] : view<16x264xf16> -> {V16H}")
    for i in R:
        e(f"        %probability_fragment_{i} = vector.fragment.load<lhs> %probability_stage_view_{i}[%c0, %key_tile] shape [%m, %k] : {PVIEW} -> {V16H}")
        e(f"        %next_product_accumulator_{i} = vector.mma %probability_fragment_{i}, %value_fragment, %product_accumulator_{i} : {V16H}, {V16H}, {V8H}")
    e(f"        scf.yield {heads(f'%next_product_accumulator_{i}' for i in R)} : {', '.join([V8H] * H)}")
    e("      }")
    for i in R:
        e(f"      vector.fragment.store<result> %product_fragment_{i}, %product_stage_view_{i}[%c0, %subgroup_product_channel] shape [%m, %n] : {V8H}, view<16x64xf16>")
    e("      kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    outs = accumulate("tail_")
    e("      kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e(f"      scf.yield {heads(outs)} : {', '.join([V4H] * 4 * H)}")
    e("    }")
    ys = []
    for i in R:
        ys += [f"%tail_next_max_{i}", f"%tail_next_sum_{i}"] + [f"%tail_next_output{r}_{i}" for r in range(4)]
    e(f"    scf.yield {heads(ys)} : {state_types()}")
    e("  }")
    e("")
    # ---- epilogue
    for i in R:
        for r in range(4):
            e(f"  %sum{r}_scalar_{i} = vector.extract %final_sum_{i}[{r}] : {V4F} -> f32")
        for r in range(4):
            e(f"  %inverse_sum{r}_f32_{i} = scalar.divf<nnan|ninf|nsz|arcp> %c1_f32, %sum{r}_scalar_{i} : f32")
        for r in range(4):
            e(f"  %inverse_sum{r}_f16_{i} = scalar.fptrunc %inverse_sum{r}_f32_{i} : f32 to f16")
        for r in range(4):
            e(f"  %inverse_sum{r}_{i} = vector.splat %inverse_sum{r}_f16_{i} : {V4H}")
        for r in range(4):
            e(f"  %normalized{r}_f16_{i} = vector.mulf<reassoc|nnan|ninf|nsz|contract> %final_output{r}_{i}, %inverse_sum{r}_{i} : {V4H}")
        for r in range(4):
            e(f"  %normalized{r}_{i} = vector.extf %normalized{r}_f16_{i} : {V4H} to {V4F}")
        e(f"  %output_channel_{i} = index.add %query_head_base_{i}, %lane_output_channel : index")
    for r in range(4):
        e(f"  scf.if %query_valid{r} {{")
        e(f"    %bounded_query_token = index.assume %query_token{r} [lt(%query_token{r}, %token_count)] : index")
        for i in R:
            e(f"    %gate_values_{i} = vector.load %gate_view[%bounded_query_token, %output_channel_{i}] : view<[%token_count]x6144xf32> -> {V4F}")
            e(f"    %gate_neg{r}_{i} = vector.mulf %gate_values_{i}, %negone_f32x4 : {V4F}")
            e(f"    %gate_exp{r}_{i} = vector.expf<afn> %gate_neg{r}_{i} : {V4F}")
            e(f"    %gate_den{r}_{i} = vector.addf %gate_exp{r}_{i}, %one_f32x4 : {V4F}")
            e(f"    %gate_sig{r}_{i} = vector.divf %one_f32x4, %gate_den{r}_{i} : {V4F}")
            e(f"    %gated_{i} = vector.mulf<nnan|ninf|nsz> %normalized{r}_{i}, %gate_sig{r}_{i} : {V4F}")
            e(f"    vector.store %gated_{i}, %output_view[%bounded_query_token, %output_channel_{i}] : {V4F}, view<[%token_count]x6144xf32>")
        e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def main():
    H = int(sys.argv[1])
    out = sys.argv[2] if len(sys.argv) > 2 else f"yah_attn_wmma_h{H}.loom"
    open(out, "w").write(gen(H))
    print(out)


if __name__ == "__main__":
    main()
