#!/usr/bin/env python3
"""Generate the KV-cache quantizers for the quantized attention configs.

usage: gen_kvq.py kmean|kq8 [out.loom]

yah_kmean: per-channel mean of this layer's f16 K over the prompt tokens,
  m[kv_head * 256 + d] (f32). Subtracting any per-channel constant from K
  shifts every score of a query row by the same q . m, so softmax is unchanged
  (exact); the mean centres K before quantization (SageAttention's smoothing:
  K's outlier channels are mostly a per-channel offset). Deterministic: one
  workgroup per KV head, 32 column chunks x 8 row groups, fixed-order LDS sum.
  grid (4, 1, 1) x 256.

yah_kq8: int8 K with one scale per (token, kv head, 128-dim half), the split
  the attention's wave pairs use: k8 = rne((k - m) / s), s = amax / 127
  (amax 0 -> s = 1). Output kq8[token][256 dwords] (bytes u = k8 + 128 in an
  f16-decode order, see gen_kq8), ks[token][8] = f16x2 (256 s, -384 s), index
  head * 2 + half. 16 lanes per half, 8 dims per lane, amax by xor
  shuffles. grid (ceil(cap / 2), 1, 1) x 256 (two tokens per workgroup);
  tokens >= token_count are written as zeros.
"""
import os
import sys

# YAH_KV_PAGED=1: the caches are paged (256-token pages, gen_attn_fa PAGED).
# Writers read the chunk's token_count rows of the f16 scratch and write
# physical row ptab[t / 256] * 256 + t % 256 (t = start_pos + local) of a
# pool of pool_rows rows (V^T tiles: ptab[tile / 16] * 16 + tile % 16).
PAGED = os.environ.get("YAH_KV_PAGED", "0") == "1"
V8 = "vector<8xf32>"


PAGE_DECLS = ("config.decl @yah_kvq.start_pos : %value: index where [range(%value, 0, 1048576)]\n"
              "config.decl @yah_kvq.pool_rows : %value: index where [range(%value, 256, 1048576)]")


def page_setup(e):
    e("  %start0 = config.get @yah_kvq.start_pos : index")
    e("  %start = index.assume %start0 [mul(%start0, 256)] : index")   # chunks start on a page
    e("  %prows = config.get @yah_kvq.pool_rows : index")
    e("  %c255g = index.constant 255 : index")
    e("  %c256g = index.constant 256 : index")
    e("  %npg0 = index.add %prows, %c255g : index")
    e("  %npages = index.div %npg0, %c256g : index")
    e("  %pt_flat = buffer.view %ptab[%base] : buffer -> view<[%npages]xi32>")
    e("  %prow_cap = index.mul %npages, %c256g : index")    # pool rows in whole pages


def page_row(e, tok, out):
    """physical pool row of chunk-local token `tok` (needs page_setup)"""
    e(f"  %{out}l = index.add %start, {tok} : index")
    e(f"  %{out}lp = index.div %{out}l, %c256g : index")
    e(f"  %{out}g0 = view.load %pt_flat[%{out}lp] : view<[%npages]xi32> -> i32")
    e(f"  %{out}gu = index.cast %{out}g0 : i32 to index")
    e(f"  %{out}npm = index.sub %npages, %c1 : index")
    e(f"  %{out}gr = index.min %{out}gu, %{out}npm : index")      # clamp into the pool
    e(f"  %{out}g = index.assume %{out}gr [range(%{out}gr, 0, 65535), lt(%{out}gr, %npages)] : index")
    e(f"  %{out}b = index.mul %{out}g, %c256g : index")
    e(f"  %{out}o = index.rem %{out}l, %c256g : index")
    e(f"  %{out} = index.add %{out}b, %{out}o : index")


def paged_quantizer(text, rows_per_tok, scales_per_tok):
    """yah_kq8 / yah_kq4 -> paged form: destination rows remapped, pool-sized views"""
    t = text.replace("config.decl @yah_kvq.cache_capacity", PAGE_DECLS + "\nconfig.decl @yah_kvq.cache_capacity", 1)
    t = t.replace("launch(%src: buffer, %mean: buffer, %dst: buffer, %scale: buffer) {",
                  "launch(%src: buffer, %mean: buffer, %dst: buffer, %scale: buffer, %ptab: buffer) {", 1)
    out = []
    for l in t.split("\n"):
        out.append(l)
        if l.strip().startswith("%ntok = index.min %ntok0, %cap"):
            page_setup(out.append)
        if l.strip().startswith("%tokc = index.min %tok, %cap1"):
            page_row(out.append, "%tokc", "prow")
    t = "\n".join(out)
    for a, b in ((f"%dtot = index.mul %cap, %c{rows_per_tok} :", f"%dtot = index.mul %prow_cap, %c{rows_per_tok} :"),
                 (f"%d32tot = index.mul %cap, %c{rows_per_tok} :", f"%d32tot = index.mul %prow_cap, %c{rows_per_tok} :"),
                 (f"%sctot = index.mul %cap, %c{scales_per_tok} :", f"%sctot = index.mul %prow_cap, %c{scales_per_tok} :"),
                 (f"%bda0 = index.mul %tokc, %c{rows_per_tok} :", f"%bda0 = index.mul %prow, %c{rows_per_tok} :"),
                 (f"%da0 = index.mul %tokc, %c{rows_per_tok} :", f"%da0 = index.mul %prow, %c{rows_per_tok} :"),
                 (f"%sa0 = index.mul %tokc, %c{scales_per_tok} :", f"%sa0 = index.mul %prow, %c{scales_per_tok} :")):
        t = t.replace(a, b)
    return t
V8H = "vector<8xf16>"
V8I = "vector<8xi8>"


def gen_kmean():
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (kmean) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@kvq_w32) @yah_kmean() {")
    e("  %c1 = index.constant 1 : index")
    e("  %c4 = index.constant 4 : index")
    e("  %c256 = index.constant 256 : index")
    e("  kernel.launch.config workgroups(%c4, %c1, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %mean: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 8, 32, 256, 1024):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok0 = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %ntok = index.min %ntok0, %cap : index")
    e("  %stot = index.mul %cap, %c1024 : index")
    e("  %s_na, %m_na = buffer.assume.noalias %src, %mean : buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %m_flat = buffer.view %m_na[%base] : buffer -> view<1024xf32>")
    e("  %pb = index.constant 8192 : offset")
    e("  %pool = buffer.alloca<workgroup> align(16) %pb : buffer")
    e("  %pv = buffer.view %pool[%base] : buffer -> view<8x256xf32>")
    e("  %head = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %chunk = index.rem %tid, %c32 : index")
    e("  %grp = index.div %tid, %c32 : index")
    e("  %col8 = index.mul %chunk, %c8 : index")
    e("  %hb = index.mul %head, %c256 : index")
    e("  %col = index.add %hb, %col8 : index")
    e(f"  %z8 = vector.constant 0.0 : {V8}")
    e(f"  %acc = scf.for %r = [%grp to %ntok step %c8](%a = %z8 : {V8}) -> ({V8}) {{")
    e("    %ra = index.mul %r, %c1024 : index")
    e("    %ad = index.add %ra, %col : index")
    e(f"    %x = vector.load %s_flat[%ad] : view<[%stot]xf16> -> {V8H}")
    e(f"    %xf = vector.extf %x : {V8H} to {V8}")
    e(f"    %an = vector.addf %a, %xf : {V8}")
    e(f"    scf.yield %an : {V8}")
    e("  }")
    e(f"  vector.store %acc, %pv[%grp, %col8] : {V8}, view<8x256xf32>")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("  %zero = scalar.constant 0.0 : f32")
    cur = "%zero"
    for g in range(8):
        e(f"  %gi{g} = index.constant {g} : index")
        e(f"  %gv{g} = view.load %pv[%gi{g}, %tid] : view<8x256xf32> -> f32")
        e(f"  %gs{g} = scalar.addf {cur}, %gv{g} : f32")
        cur = f"%gs{g}"
    e("  %ntoki = index.cast %ntok : index to i32")
    e("  %ntokf = scalar.sitofp %ntoki : i32 to f32")
    e(f"  %mv = scalar.divf {cur}, %ntokf : f32")
    e("  %mo = index.add %hb, %tid : index")
    e("  view.store %mv, %m_flat[%mo] : f32, view<1024xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_kq8():
    """yah_kq8 (kv8a16, K decoded to f16 at staging; see the module doc for
    the scale split): bytes u = q + 128 in the order d0, d2, d1, d3 per dword,
    so ((w << 2), (w >> 6)) & 0x03fc03fc | 0x3c003c00 are the f16 pairs
    1 + u/256 in dim order; ks[token][8] = f16x2 (256 s, -384 s), so one fused
    fma gives s q = (1 + u/256) 256 s - 384 s."""
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (kq8) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@kvq_w32) @yah_kq8() {")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %c1 = index.constant 1 : index")
    e("  %c2 = index.constant 2 : index")
    e("  %c256 = index.constant 256 : index")
    e("  %t0 = index.add %cap, %c1 : index")
    e("  %wgs = index.div %t0, %c2 : index")
    e("  kernel.launch.config workgroups(%wgs, %c1, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %mean: buffer, %dst: buffer, %scale: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 4, 8, 16, 128, 256, 1024):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok0 = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %ntok = index.min %ntok0, %cap : index")
    e("  %stot = index.mul %cap, %c1024 : index")
    e("  %sctot = index.mul %cap, %c8 : index")
    e("  %s_na, %m_na, %d_na, %c_na = buffer.assume.noalias %src, %mean, %dst, %scale : buffer, buffer, buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %m_flat = buffer.view %m_na[%base] : buffer -> view<1024xf32>")
    e("  %d_flat = buffer.view %d_na[%base] : buffer -> view<[%stot]xi8>")
    e("  %c_flat = buffer.view %c_na[%base] : buffer -> view<[%sctot]xf32>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %tsub = index.div %tid, %c128 : index")           # token within the workgroup
    e("  %t2 = index.mul %wg, %c2 : index")
    e("  %tok = index.add %t2, %tsub : index")
    e("  %cap1 = index.sub %cap, %c1 : index")
    e("  %tokc = index.min %tok, %cap1 : index")
    e("  %live = index.cmp ult, %tok, %ntok : index")
    e("  %lt = index.rem %tid, %c128 : index")
    e("  %col = index.mul %lt, %c8 : index")              # 8 dims per lane
    e("  %ra = index.mul %tokc, %c1024 : index")
    e("  %ad = index.add %ra, %col : index")
    e(f"  %x = vector.load %s_flat[%ad] : view<[%stot]xf16> -> {V8H}")
    e(f"  %xf = vector.extf %x : {V8H} to {V8}")
    e(f"  %m = vector.load %m_flat[%col] : view<1024xf32> -> {V8}")
    e(f"  %xc = vector.subf %xf, %m : {V8}")
    e(f"  %xa = vector.absf %xc : {V8}")
    e("  %zero = scalar.constant 0.0 : f32")
    e(f"  %amax0 = vector.reduce<maxnumf> %xa, %zero : {V8}, f32")
    cur = "%amax0"
    e("  %x32 = scalar.constant 32 : i32")
    for k in (1, 2, 4, 8):   # 16 lanes per (head, half): lanes 16j..16j+15
        e(f"  %xk{k} = scalar.constant {k} : i32")
        e(f"  %ab{k} = scalar.bitcast {cur} : f32 to i32")
        e(f"  %as{k}, %av{k} = kernel.subgroup.shuffle<xor> %ab{k}, %xk{k}, %x32 : i32, i32, i32")
        e(f"  %af{k} = scalar.bitcast %as{k} : i32 to f32")
        e(f"  %am{k} = scalar.maxnumf {cur}, %af{k} : f32")
        cur = f"%am{k}"
    e("  %r127 = scalar.constant 127.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e(f"  %s0 = scalar.divf {cur}, %r127 : f32")
    e("  %spos = scalar.cmpf ogt, %s0, %zero : f32")
    e("  %s = scf.select %spos, %s0, %one : f32")
    e("  %inv = scalar.divf %one, %s : f32")
    e(f"  %inv8 = vector.splat %inv : {V8}")
    e(f"  %xq = vector.mulf %xc, %inv8 : {V8}")
    e(f"  %xr = vector.roundevenf %xq : {V8}")
    e("  %d32tot = index.mul %cap, %c256 : index")
    e("  %d32_flat = buffer.view %d_na[%base] : buffer -> view<[%d32tot]xi32>")
    e("  %c128f = scalar.constant 128.0 : f32")
    us = []
    for i in range(8):
        e(f"  %xe{i} = vector.extract %xr[{i}] : {V8} -> f32")
        e(f"  %xu{i} = scalar.addf %xe{i}, %c128f : f32")
        e(f"  %xw{i} = scalar.fptosi %xu{i} : f32 to i32")
        us.append(f"%xw{i}")
    words = []
    for w in range(2):
        acc = None
        for slot, d in enumerate((0, 2, 1, 3)):
            e(f"  %bs{w}_{slot}c = scalar.constant {8 * slot} : i32")
            e(f"  %bs{w}_{slot} = scalar.shli {us[4 * w + d]}, %bs{w}_{slot}c : i32")
            if acc is None:
                acc = f"%bs{w}_{slot}"
            else:
                e(f"  %bo{w}_{slot} = scalar.ori {acc}, %bs{w}_{slot} : i32")
                acc = f"%bo{w}_{slot}"
        words.append(acc)
    e(f"  %bw = vector.from_elements {words[0]}, {words[1]} : vector<2xi32>")
    e("  %bz = vector.constant 0 : vector<2xi32>")
    e("  %bwo = scf.select %live, %bw, %bz : vector<2xi32>")
    e("  %bda0 = index.mul %tokc, %c256 : index")
    e("  %bda1 = index.mul %lt, %c2 : index")
    e("  %bda = index.add %bda0, %bda1 : index")
    e("  vector.store %bwo, %d32_flat[%bda] : vector<2xi32>, view<[%d32tot]xi32>")
    # scale: lane 16j of each half writes ks[token][head * 2 + half]
    e("  %hh = index.div %lt, %c16 : index")             # head * 2 + half
    e("  %first = index.rem %lt, %c16 : index")
    e("  %isf = index.cmp eq, %first, %c0 : index")
    e("  %so = scf.select %live, %s, %zero : f32")
    e("  %sa0 = index.mul %tokc, %c8 : index")
    e("  %sa = index.add %sa0, %hh : index")
    e("  %r256 = scalar.constant 256.0 : f32")
    e("  %rm384 = scalar.constant -384.0 : f32")
    e("  %S0 = scalar.mulf %so, %r256 : f32")
    e("  %C0 = scalar.mulf %so, %rm384 : f32")
    e("  %SC = vector.from_elements %S0, %C0 : vector<2xf32>")
    e("  %SCh = vector.fptrunc %SC : vector<2xf32> to vector<2xf16>")
    e("  %SCw = vector.bitcast %SCh : vector<2xf16> to vector<1xi32>")
    e("  %SCi = vector.extract %SCw[0] : vector<1xi32> -> i32")
    e("  %ci_flat = buffer.view %c_na[%base] : buffer -> view<[%sctot]xi32>")
    e("  scf.if %isf {")
    e("    view.store %SCi, %ci_flat[%sa] : i32, view<[%sctot]xi32>")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_kq4():
    """yah_kq4 (kv4a16, engine/run/kvq/README.md): H256 (k - m), the
    orthonormal Walsh-Hadamard transform of the whole head (the attention
    rotates Q the same way, so q.k is unchanged), quantized asymmetrically to
    16 levels with one min/max range per 32-dim group. Codes u: dims 2j / 2j+1
    of each 8 at bits 4j / 16 + 4j of the lane's dword (so (w << 6, w << 2,
    w >> 2, w >> 6) & 0x03c003c0 | 0x3c003c00 are the f16 pairs 1 + u/16 in dim
    order); kq4[token][128 dwords] (lane = head*32 + half*16 + 8-dim chunk);
    ks[token][32] = f16x2 (16 s, lo - 16 s) per group (head*8 + group): the
    attention decodes k = (1 + u/16) * 16 s + lo - 16 s with one fma."""
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (kq4) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@kvq_w32) @yah_kq4() {")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %c1 = index.constant 1 : index")
    e("  %c2 = index.constant 2 : index")
    e("  %c256 = index.constant 256 : index")
    e("  %t0 = index.add %cap, %c1 : index")
    e("  %wgs = index.div %t0, %c2 : index")
    e("  kernel.launch.config workgroups(%wgs, %c1, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %mean: buffer, %dst: buffer, %scale: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 4, 8, 16, 32, 128, 1024):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok0 = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %ntok = index.min %ntok0, %cap : index")
    e("  %stot = index.mul %cap, %c1024 : index")
    e("  %dtot = index.mul %cap, %c128 : index")
    e("  %sctot = index.mul %cap, %c32 : index")
    e("  %s_na, %m_na, %d_na, %c_na = buffer.assume.noalias %src, %mean, %dst, %scale : buffer, buffer, buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %m_flat = buffer.view %m_na[%base] : buffer -> view<1024xf32>")
    e("  %d_flat = buffer.view %d_na[%base] : buffer -> view<[%dtot]xi32>")
    e("  %c_flat = buffer.view %c_na[%base] : buffer -> view<[%sctot]xf32>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %tsub = index.div %tid, %c128 : index")
    e("  %t2 = index.mul %wg, %c2 : index")
    e("  %tok = index.add %t2, %tsub : index")
    e("  %cap1 = index.sub %cap, %c1 : index")
    e("  %tokc = index.min %tok, %cap1 : index")
    e("  %live = index.cmp ult, %tok, %ntok : index")
    e("  %lt = index.rem %tid, %c128 : index")
    e("  %l16 = index.rem %lt, %c16 : index")
    e("  %l32 = index.rem %lt, %c32 : index")
    e("  %col = index.mul %lt, %c8 : index")
    e("  %ra = index.mul %tokc, %c1024 : index")
    e("  %ad = index.add %ra, %col : index")
    e(f"  %x = vector.load %s_flat[%ad] : view<[%stot]xf16> -> {V8H}")
    e(f"  %xf = vector.extf %x : {V8H} to {V8}")
    e(f"  %m = vector.load %m_flat[%col] : view<1024xf32> -> {V8}")
    e(f"  %xc = vector.subf %xf, %m : {V8}")
    e(f"  %zero8 = vector.constant 0.0 : {V8}")
    # in-lane butterflies (dims 1, 2, 4 apart)
    xs = []
    for i in range(8):
        e(f"  %h0_{i} = vector.extract %xc[{i}] : {V8} -> f32")
        xs.append(f"%h0_{i}")
    st = 0
    for h in (1, 2, 4):
        st += 1
        nx = []
        for i in range(8):
            j = i ^ h
            if i & h:
                e(f"  %h{st}_{i} = scalar.subf {xs[j]}, {xs[i]} : f32")
            else:
                e(f"  %h{st}_{i} = scalar.addf {xs[i]}, {xs[j]} : f32")
            nx.append(f"%h{st}_{i}")
        xs = nx
    e(f"  %hv{st} = vector.from_elements {', '.join(xs)} : {V8}")
    cur = f"%hv{st}"
    e("  %x32 = scalar.constant 32 : i32")
    # cross-lane butterflies (dims 8, 16, 32, 64 apart = lane xor 1, 2, 4, 8)
    for k in (1, 2, 4, 8, 16):
        e(f"  %xk{k} = scalar.constant {k} : i32")
        e(f"  %sh{k}, %shv{k} = kernel.subgroup.shuffle<xor> {cur}, %xk{k}, %x32 : {V8}, i32, i32")
        e(f"  %ck{k}c = index.constant {k} : index")
        e(f"  %lb{k}a = index.div {'%l32' if k == 16 else '%l16'}, %ck{k}c : index")
        e(f"  %lb{k}b = index.rem %lb{k}a, %c2 : index")
        e(f"  %up{k} = index.cmp eq, %lb{k}b, %c1 : index")
        e(f"  %bs{k} = vector.addf {cur}, %sh{k} : {V8}")
        e(f"  %bd{k} = vector.subf %sh{k}, {cur} : {V8}")
        e(f"  %bf{k} = scf.select %up{k}, %bd{k}, %bs{k} : {V8}")
        cur = f"%bf{k}"
    e("  %rsq = scalar.constant 0.0625 : f32")   # 1 / sqrt(256)
    e(f"  %rsq8 = vector.splat %rsq : {V8}")
    e(f"  %xr = vector.mulf {cur}, %rsq8 : {V8}")
    gen_kq4_asym(e)
    return "\n".join(L) + "\n"


def gen_kq4_asym(e):
    """quantize %xr (this lane's 8 rotated dims) asymmetrically, one range per
    32-dim group (4 lanes: xor 1, 2); see gen_kq4."""
    red = (1, 2)
    e("  %zero = scalar.constant 0.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")


    # exact min/max: seed with element 0 instead of 0.0
    e(f"  %xr0 = vector.extract %xr[0] : {V8} -> f32")
    e(f"  %lo0x = vector.reduce<minnumf> %xr, %xr0 : {V8}, f32")
    e(f"  %hi0x = vector.reduce<maxnumf> %xr, %xr0 : {V8}, f32")
    lo, hi = "%lo0x", "%hi0x"
    for k in red:
        for nm, op in (("lo", "minnumf"), ("hi", "maxnumf")):
            cur = lo if nm == "lo" else hi
            e(f"  %{nm}b{k} = scalar.bitcast {cur} : f32 to i32")
            e(f"  %{nm}s{k}, %{nm}v{k} = kernel.subgroup.shuffle<xor> %{nm}b{k}, %xk{k}, %x32 : i32, i32, i32")
            e(f"  %{nm}f{k} = scalar.bitcast %{nm}s{k} : i32 to f32")
            e(f"  %{nm}m{k} = scalar.{op} {cur}, %{nm}f{k} : f32")
            if nm == "lo":
                lo = f"%lom{k}"
            else:
                hi = f"%him{k}"
    e("  %r15 = scalar.constant 15.0 : f32")
    e(f"  %rng = scalar.subf {hi}, {lo} : f32")
    e("  %s0 = scalar.divf %rng, %r15 : f32")
    e("  %spos = scalar.cmpf ogt, %s0, %zero : f32")
    e("  %s = scf.select %spos, %s0, %one : f32")
    e("  %inv = scalar.divf %one, %s : f32")
    e(f"  %inv8 = vector.splat %inv : {V8}")
    e(f"  %lo8 = vector.splat {lo} : {V8}")
    e(f"  %xs = vector.subf %xr, %lo8 : {V8}")
    e(f"  %xq = vector.mulf %xs, %inv8 : {V8}")
    e(f"  %xn0 = vector.roundevenf %xq : {V8}")
    e(f"  %z8f = vector.constant 0.0 : {V8}")
    e(f"  %f15 = vector.constant 15.0 : {V8}")
    e(f"  %xn1 = vector.maxnumf %xn0, %z8f : {V8}")
    e(f"  %xn = vector.minnumf %xn1, %f15 : {V8}")
    e("  %m15 = scalar.constant 15 : i32")
    e("  %i8c = scalar.constant 8 : i32")
    nib = []
    for i in range(8):
        e(f"  %qe{i} = vector.extract %xn[{i}] : {V8} -> f32")
        e(f"  %qi{i} = scalar.fptosi %qe{i} : f32 to i32")
        e(f"  %qn{i} = scalar.andi %qi{i}, %m15 : i32")
        nib.append(f"%qn{i}")
    acc = None
    for i in range(8):
        sh = 4 * (i // 2) + (16 if i % 2 else 0)   # dim 2j at 4j, dim 2j+1 at 16 + 4j
        e(f"  %ps{i}c = scalar.constant {sh} : i32")
        e(f"  %ps{i} = scalar.shli {nib[i]}, %ps{i}c : i32")
        if acc is None:
            acc = f"%ps{i}"
        else:
            e(f"  %po{i} = scalar.ori {acc}, %ps{i} : i32")
            acc = f"%po{i}"
    e("  %zi = scalar.constant 0 : i32")
    e(f"  %wo = scf.select %live, {acc}, %zi : i32")
    e("  %da0 = index.mul %tokc, %c128 : index")
    e("  %da = index.add %da0, %lt : index")
    e("  view.store %wo, %d_flat[%da] : i32, view<[%dtot]xi32>")
    e("  %sa0 = index.mul %tokc, %c32 : index")
    e("  %r16 = scalar.constant 16.0 : f32")
    e("  %S0 = scalar.mulf %s, %r16 : f32")
    e(f"  %C0 = scalar.subf {lo}, %S0 : f32")
    e("  %So = scf.select %live, %S0, %zero : f32")
    e("  %Co = scf.select %live, %C0, %zero : f32")
    e("  %SC = vector.from_elements %So, %Co : vector<2xf32>")
    e("  %SCh = vector.fptrunc %SC : vector<2xf32> to vector<2xf16>")
    e("  %SCw = vector.bitcast %SCh : vector<2xf16> to vector<1xi32>")
    e("  %SCi = vector.extract %SCw[0] : vector<1xi32> -> i32")
    e("  %ci_flat = buffer.view %c_na[%base] : buffer -> view<[%sctot]xi32>")
    e("  %grp = index.div %lt, %c4 : index")
    e("  %l4 = index.rem %lt, %c4 : index")
    e("  %isf = index.cmp eq, %l4, %c0 : index")
    e("  %sa = index.add %sa0, %grp : index")
    e("  scf.if %isf {")
    e("    view.store %SCi, %ci_flat[%sa] : i32, view<[%sctot]xi32>")
    e("  }")
    e("  kernel.return")
    e("}")


def gen_vq4():
    return gen_vqt(4)


def gen_vq8():
    return gen_vqt(8)


def gen_vqt(bits):
    """yah_vq4 / yah_vq8: V^T quantized per channel per 16-token tile around
    the tile's midrange c with step s (per-channel per-tile range: attention
    error 3.5e-2 -> 2.1e-2 vs per-channel over the prompt at 4 bits).
      4 bits: u = rne((v - c) / s) + 7 in [0, 14], s = range / 14; in each of
        the lane's 2 dwords nibble p holds key 2p (p < 4) or 2(p - 4) + 1, so
        (w >> 4k ...) & 0x03c003c0 | 0x3c003c00 are f16 1 + u/16 for keys 2k,
        2k + 1; stats (S, C') = (16 s, c - 23 s).
      8 bits: u = rne((v - c) / s) + 128 in [1, 255], s = range / 254; each of
        the lane's 4 dwords holds keys (k0, k2, k1, k3) of its 4, so (w << 2,
        w >> 6) & 0x03fc03fc | 0x3c003c00 are f16 1 + u/256 for keys (k0, k1),
        (k2, k3); stats (S, C') = (256 s, c - 384 s).
    Either way the attention dequantizes with one fma f * S + C' while staging.
    Output [kv head][tile][256 dims] x (2 or 4) dwords, stats [kv head][tile][256]
    f16 pairs. Chunked prefill: src is the chunk's token_count rows of f16 V
    (a slice of the cache), written at tiles start_pos / 16 + tile of a cache of
    cache_capacity tokens. Tokens past token_count repeat the last one (keys
    the softmax masks). grid (4, ceil(token_count / 16)) x 256 (lane = dim)."""
    nw = 2 if bits == 4 else 4
    lv = 14 if bits == 4 else 254              # range / s
    off = 7 if bits == 4 else 128              # u offset
    umax = 14 if bits == 4 else 255
    smul, cmul = (16.0, -23.0) if bits == 4 else (256.0, -384.0)
    L = []
    e = L.append
    e(f"// GENERATED by tools/gen_kvq.py (vq{bits}) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.cache_capacity : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_kvq.start_pos : %value: index where [range(%value, 0, 1048576)]")
    e("")
    e(f"kernel.def target(@kvq_w32) @yah_vq{bits}() {{")
    e("  %ntk = config.get @yah_kvq.token_count : index")
    e("  %c1 = index.constant 1 : index")
    e("  %c4 = index.constant 4 : index")
    e("  %c15 = index.constant 15 : index")
    e("  %c16 = index.constant 16 : index")
    e("  %c256 = index.constant 256 : index")
    e("  %t0 = index.add %ntk, %c15 : index")
    e("  %tiles = index.div %t0, %c16 : index")
    e("  kernel.launch.config workgroups(%c4, %tiles, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %dst: buffer, %stat: buffer" + (", %ptab: buffer" if PAGED else "") + ") {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 4, 15, 16, 256, 1024):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok = config.get @yah_kvq.token_count : index")
    e("  %cap = config.get @yah_kvq.cache_capacity : index")
    e("  %start = config.get @yah_kvq.start_pos : index")
    e("  %p15 = index.add %cap, %c15 : index")
    e("  %tiles = index.div %p15, %c16 : index")          # tiles of the whole cache
    e("  %stot = index.mul %ntok, %c1024 : index")         # the chunk's rows
    e("  %ttot0 = index.mul %tiles, %c1024 : index")      # 4 heads x 256 dims per tile
    e(f"  %dtot = index.mul %ttot0, %c{nw} : index")
    e("  %s_na, %d_na, %t_na = buffer.assume.noalias %src, %dst, %stat : buffer, buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %d_flat = buffer.view %d_na[%base] : buffer -> view<[%dtot]xi32>")
    e("  %t_flat = buffer.view %t_na[%base] : buffer -> view<[%ttot0]xi32>")
    e("  %head = kernel.workgroup.id<x> : index")
    e("  %ltile = kernel.workgroup.id<y> : index")
    e("  %d = kernel.workitem.id<x> : index")
    e("  %st16 = index.div %start, %c16 : index")
    if PAGED:   # physical tile = ptab[tile / 16] * 16 + tile % 16
        e("  %c255g = index.constant 255 : index")
        e("  %npg0 = index.add %cap, %c255g : index")
        e("  %npages = index.div %npg0, %c256 : index")
        e("  %pt_flat = buffer.view %ptab[%base] : buffer -> view<[%npages]xi32>")
        e("  %ltl = index.add %st16, %ltile : index")
        e("  %ltp = index.div %ltl, %c16 : index")
        e("  %ltg0 = view.load %pt_flat[%ltp] : view<[%npages]xi32> -> i32")
        e("  %ltgu = index.cast %ltg0 : i32 to index")
        e("  %ltnpm = index.sub %npages, %c1 : index")
        e("  %ltgr = index.min %ltgu, %ltnpm : index")              # clamp into the pool
        e("  %ltg = index.assume %ltgr [range(%ltgr, 0, 65535), lt(%ltgr, %npages)] : index")
        e("  %ltb = index.mul %ltg, %c16 : index")
        e("  %lto = index.rem %ltl, %c16 : index")
        e("  %tile = index.add %ltb, %lto : index")
    else:
        e("  %tile = index.add %st16, %ltile : index")
    e("  %hb = index.mul %head, %c256 : index")
    e("  %col = index.add %hb, %d : index")
    e("  %t16 = index.mul %ltile, %c16 : index")
    e("  %ntok1 = index.sub %ntok, %c1 : index")
    vals = []
    for j in range(16):
        e(f"  %tk{j}c = index.constant {j} : index")
        e(f"  %tk{j} = index.add %t16, %tk{j}c : index")
        e(f"  %tl{j} = index.min %tk{j}, %ntok1 : index")      # past the chunk: repeat its last token
        e(f"  %tm{j} = index.mul %tl{j}, %c1024 : index")
        e(f"  %ta{j} = index.add %tm{j}, %col : index")
        e(f"  %vh{j} = view.load %s_flat[%ta{j}] : view<[%stot]xf16> -> f16")
        e(f"  %v{j} = scalar.extf %vh{j} : f16 to f32")
        vals.append(f"%v{j}")
    mx, mn = vals[0], vals[0]
    for j in range(1, 16):
        e(f"  %mx{j} = scalar.maxnumf {mx}, {vals[j]} : f32")
        e(f"  %mn{j} = scalar.minnumf {mn}, {vals[j]} : f32")
        mx, mn = f"%mx{j}", f"%mn{j}"
    e("  %half = scalar.constant 0.5 : f32")
    e(f"  %rlv = scalar.constant {float(lv)} : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e("  %zero = scalar.constant 0.0 : f32")
    e(f"  %sm = scalar.addf {mx}, {mn} : f32")
    e("  %cen = scalar.mulf %sm, %half : f32")
    e(f"  %rg = scalar.subf {mx}, {mn} : f32")
    e("  %s0 = scalar.divf %rg, %rlv : f32")
    e("  %spos = scalar.cmpf ogt, %s0, %zero : f32")
    e("  %s = scf.select %spos, %s0, %one : f32")
    # round the stats to f16 first: the attention dequantizes with the f16 values
    e("  %sh = scalar.fptrunc %s : f32 to f16")
    e("  %ch = scalar.fptrunc %cen : f32 to f16")
    e("  %sf = scalar.extf %sh : f16 to f32")
    e("  %cf = scalar.extf %ch : f16 to f32")
    e("  %inv = scalar.divf %one, %sf : f32")
    e(f"  %roff = scalar.constant {float(off)} : f32")
    e("  %r0 = scalar.constant 0.0 : f32")
    e(f"  %rmax = scalar.constant {float(umax)} : f32")
    us = []
    for j in range(16):
        e(f"  %xc{j} = scalar.subf {vals[j]}, %cf : f32")
        e(f"  %xs{j} = scalar.mulf %xc{j}, %inv : f32")
        e(f"  %xr{j} = scalar.roundevenf %xs{j} : f32")
        e(f"  %xo{j} = scalar.addf %xr{j}, %roff : f32")
        e(f"  %xl{j} = scalar.maxnumf %xo{j}, %r0 : f32")
        e(f"  %xm{j} = scalar.minnumf %xl{j}, %rmax : f32")
        e(f"  %xu{j} = scalar.fptosi %xm{j} : f32 to i32")
        us.append(f"%xu{j}")
    words = []
    for w in range(nw):
        acc = None
        slots = 8 if bits == 4 else 4
        for p in range(slots):
            if bits == 4:
                key = 8 * w + (2 * p if p < 4 else 2 * (p - 4) + 1)
                sh = 4 * p
            else:
                key = 4 * w + (0, 2, 1, 3)[p]
                sh = 8 * p
            e(f"  %np{w}{p}c = scalar.constant {sh} : i32")
            e(f"  %np{w}{p} = scalar.shli {us[key]}, %np{w}{p}c : i32")
            if acc is None:
                acc = f"%np{w}{p}"
            else:
                e(f"  %na{w}{p} = scalar.ori {acc}, %np{w}{p} : i32")
                acc = f"%na{w}{p}"
        words.append(acc)
    e("  %ti0 = index.mul %head, %tiles : index")
    e("  %ti1 = index.add %ti0, %tile : index")
    e("  %ti2 = index.mul %ti1, %c256 : index")
    e("  %ti = index.add %ti2, %d : index")             # [head][tile][dim]
    e(f"  %da0 = index.mul %ti, %c{nw} : index")
    for w in range(nw):
        e(f"  %daw{w}c = index.constant {w} : index")
        e(f"  %daw{w} = index.add %da0, %daw{w}c : index")
        e(f"  view.store {words[w]}, %d_flat[%daw{w}] : i32, view<[%dtot]xi32>")
    e(f"  %rS = scalar.constant {smul} : f32")
    e(f"  %rC = scalar.constant {cmul} : f32")
    e("  %S = scalar.mulf %sf, %rS : f32")
    e("  %Cp = scalar.fmaf %sf, %rC, %cf : f32")
    e("  %Sh = scalar.fptrunc %S : f32 to f16")
    e("  %Cph = scalar.fptrunc %Cp : f32 to f16")
    e("  %pk = vector.from_elements %Sh, %Cph : vector<2xf16>")
    e("  %pkw = vector.bitcast %pk : vector<2xf16> to vector<1xi32>")
    e("  %pkd = vector.extract %pkw[0] : vector<1xi32> -> i32")
    e("  view.store %pkd, %t_flat[%ti] : i32, view<[%ttot0]xi32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


_gen_kq8, _gen_kq4 = gen_kq8, gen_kq4


def gen_kq8():
    t = _gen_kq8()
    return paged_quantizer(t, 256, 8) if PAGED else t


def gen_kq4():
    t = _gen_kq4()
    return paged_quantizer(t, 128, 32) if PAGED else t


def main():
    which = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else f"yah_{which}.loom"
    open(out, "w").write({"kmean": gen_kmean, "kq8": gen_kq8, "vq8": gen_vq8,
                          "kq4": gen_kq4, "vq4": gen_vq4, "vtpage": gen_vtpage}[which]())
    print(out)


def gen_vtpage():
    """yah_vtpage (paged fp16 V^T): the chunk's token_count f16 V rows (scratch)
    -> V^T tiles [kv head][pool tiles][256 dims][16 keys] of the paged pool
    (pool tiles = pool_rows / 16), physical tile ptab[tile / 16] * 16 + tile % 16
    for logical tile (start_pos + local) / 16. 32 x 32 tiles through LDS (as
    yah_transpose_v16); grid (1024 / 32, ceil(token_count / 32))."""
    L = []
    e = L.append
    e("// GENERATED by tools/gen_kvq.py (vtpage) -- edit the generator.")
    e("amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}")
    e("config.decl @yah_kvq.token_count : %value: index where [range(%value, 1, 1048576)]")
    e(PAGE_DECLS)
    e("")
    e("kernel.def target(@kvq_w32) @yah_vtpage() {")
    e("  %ntk = config.get @yah_kvq.token_count : index")
    e("  %c1 = index.constant 1 : index")
    e("  %c31 = index.constant 31 : index")
    e("  %c32 = index.constant 32 : index")
    e("  %c256 = index.constant 256 : index")
    e("  %t0 = index.add %ntk, %c31 : index")
    e("  %tiles = index.div %t0, %c32 : index")
    e("  kernel.launch.config workgroups(%c32, %tiles, %c1) workgroup_size(%c256, %c1, %c1) : index")
    e("} launch(%src: buffer, %dst: buffer, %ptab: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 4, 8, 15, 16, 32, 256, 1024, 4096):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %ntok = config.get @yah_kvq.token_count : index")
    page_setup(e)
    e("  %ptiles = index.mul %npages, %c16 : index")          # tiles per kv head in the pool
    e("  %stot = index.mul %ntok, %c1024 : index")
    e("  %dtot = index.mul %prow_cap, %c1024 : index")
    e("  %s_na, %d_na = buffer.assume.noalias %src, %dst : buffer, buffer")
    e("  %s_flat = buffer.view %s_na[%base] : buffer -> view<[%stot]xf16>")
    e("  %d_flat = buffer.view %d_na[%base] : buffer -> view<[%dtot]xf16>")
    e("  %tb = index.constant 2304 : offset")
    e("  %tile = buffer.alloca<workgroup> align(16) %tb : buffer")
    e("  %tv = buffer.view %tile[%base] : buffer -> view<32x36xf16>")
    e("  %cb = kernel.workgroup.id<x> : index")
    e("  %tbk = kernel.workgroup.id<y> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %col0 = index.mul %cb, %c32 : index")
    e("  %tok0 = index.mul %tbk, %c32 : index")
    e("  %r = index.div %tid, %c8 : index")
    e("  %sg0 = index.rem %tid, %c8 : index")
    e("  %sg = index.mul %sg0, %c4 : index")
    e("  %zh4 = vector.constant 0.0 : vector<4xf16>")
    e("  %tok = index.add %tok0, %r : index")
    e("  %live = index.cmp ult, %tok, %ntok : index")
    e("  %ntok1 = index.sub %ntok, %c1 : index")
    e("  %tokc = index.min %tok, %ntok1 : index")
    e("  %sa0 = index.mul %tokc, %c1024 : index")
    e("  %sa1 = index.add %sa0, %col0 : index")
    e("  %sa = index.add %sa1, %sg : index")
    e("  %raw = vector.load %s_flat[%sa] : view<[%stot]xf16> -> vector<4xf16>")
    e("  %val = scf.select %live, %raw, %zh4 : vector<4xf16>")
    e("  vector.store %val, %tv[%r, %sg] : vector<4xf16>, view<32x36xf16>")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    els = []
    for j in range(4):
        e(f"  %tj{j}c = index.constant {j} : index")
        e(f"  %tj{j} = index.add %sg, %tj{j}c : index")
        e(f"  %x{j} = view.load %tv[%tj{j}, %r] : view<32x36xf16> -> f16")
        els.append(f"%x{j}")
    e(f"  %ov = vector.from_elements {', '.join(els)} : vector<4xf16>")
    e("  %col = index.add %col0, %r : index")
    e("  %dtl0 = index.add %tok0, %sg : index")                # chunk-local token of this group of 4
    e("  %dlive = index.cmp ult, %dtl0, %ntok : index")
    e("  %kvh = index.div %col, %c256 : index")
    e("  %dd = index.rem %col, %c256 : index")
    e("  %dt = index.add %start, %dtl0 : index")               # logical token
    e("  %ltile = index.div %dt, %c16 : index")
    # start is page-aligned and tok0 a multiple of 32: dt % 16 = (sg0 % 4) * 4
    e("  %sg4 = index.rem %sg0, %c4 : index")
    e("  %dj = index.mul %sg4, %c4 : index")
    e("  %ltp = index.div %ltile, %c16 : index")
    e("  %ltg0 = view.load %pt_flat[%ltp] : view<[%npages]xi32> -> i32")
    e("  %ltgu = index.cast %ltg0 : i32 to index")
    e("  %ltnpm = index.sub %npages, %c1 : index")
    e("  %ltgr = index.min %ltgu, %ltnpm : index")                  # clamp into the pool
    e("  %ltg = index.assume %ltgr [range(%ltgr, 0, 65535), lt(%ltgr, %npages)] : index")
    e("  %ltb = index.mul %ltg, %c16 : index")
    e("  %lto = index.rem %ltile, %c16 : index")
    e("  %ptile = index.add %ltb, %lto : index")
    e("  %da0 = index.mul %kvh, %ptiles : index")
    e("  %da1 = index.add %da0, %ptile : index")
    e("  %da2 = index.mul %da1, %c4096 : index")
    e("  %da3 = index.mul %dd, %c16 : index")
    e("  %da4 = index.add %da2, %da3 : index")
    e("  %da = index.add %da4, %dj : index")
    e("  scf.if %dlive {")
    e("    vector.store %ov, %d_flat[%da] : vector<4xf16>, view<[%dtot]xf16>")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    main()
