#!/usr/bin/env python3
"""Generate yah_half_norm, the fully unrolled RMS norm with f16 output, for one row width.

usage: gen_half_norm.py [out.loom] [dim=5120]

Grid (rows) x 32: one wave32 per row; lane l owns elements l, l+32, ...
Bindings: x (f32 [rows][dim]), weight (f32 [dim]), out (f16 [rows][dim]); residual and sum_out are not read.
Per lane the sum of squares is ((0 + v0*v0) + v1*v1) + ... (mulf then addf, not fma), then a subgroup reduction.
The output is f16((v * inv) * w).

Fully unrolled: each lane issues all dim/32 loads up front and keeps the values in registers,
so the second pass reads mostly the weight (a loop form makes ~160 dependent round trips per lane).
"""
import sys


def gen(dim=5120, wpr=1, tiled=False, resadd=False, keep=None, wlds=False):
    """tiled: the output fragment-major for the afrag GEMMs (gen_gemm_tile Tile.atiled): 16 x 16 tiles (row / 16,
    col / 16) of 256 halves, column fastest inside. Lane l's column l + 32k is tile column 2k + l / 16, offset l % 16.
    tiled="both": the row-major output to out and the fragment-major one to a sixth binding out_t.
    resadd: the residual add of the GEMM before it moves here: v = x + residual (the GEMM's f32 output, the same f32
    add the kres epilogue did), v is stored to sum_out (the new residual stream; x and residual are only read) and
    normalized as x was. Rows past `keep` reload x and residual and add again (no read of the stored v).
    wlds: the workgroup stages the weight vector in LDS once (16-byte loads); the output pass reads it from LDS
    instead of every row walking it through L2 two loads at a time."""
    both = tiled == "both"
    assert dim % 32 == 0
    n = dim // 32
    L = []
    e = L.append
    e(f"// GENERATED by tools/gen_half_norm.py (dim={dim}) -- edit the generator.")
    e("// Fully unrolled fp16 RMS norm (fused=0); see the generator.")
    e("amdgpu.target<gfx1151> @yah_wave32 {subgroup_size = 32}")
    e("")
    e("config.decl @yah_half_norm.rows : %value: index where [range(%value, 1, 65536)]")
    e(f"config.decl @yah_half_norm.dim : %value: index where [range(%value, {dim}, {dim})]")
    e("config.def @yah_half_norm.eps = 0.0 : f32")
    e("config.def @yah_half_norm.fused = 0 : index")
    e("")
    e("kernel.def target(@yah_wave32) @yah_half_norm() {")
    e("  %unit = index.constant 1 : index")
    e("  %rows = config.get @yah_half_norm.rows : index")
    e("  %c32 = index.constant 32 : index")
    if wpr == 1:
        e("  kernel.launch.config workgroups(%rows, %unit, %unit) workgroup_size(%c32, %unit, %unit) : index")
    else:
        # wpr rows per workgroup, one wave each; the driver launches rows / wpr workgroups
        e(f"  %cwpr = index.constant {wpr} : index")
        e(f"  %cwgs = index.constant {32 * wpr} : index")
        e("  %wgs = index.div %rows, %cwpr : index")
        e("  kernel.launch.config workgroups(%wgs, %unit, %unit) workgroup_size(%cwgs, %unit, %unit) : index")
    e("} launch(%x: buffer, %residual: buffer, %weight: buffer, %sum_out: buffer, %out: buffer"
      + (", %out_t: buffer" if both else "") + ") {")
    e("  %base = index.constant 0 : offset")
    e("  %zero = scalar.constant 0.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e(f"  %dim = index.constant {dim} : index")
    e("  %eps = config.get @yah_half_norm.eps : f32")
    e("  %rows = config.get @yah_half_norm.rows : index")
    e("  %total_elems = index.mul %rows, %dim : index")
    if resadd:
        assert not both
        e("  %x_na, %res_na, %weight_na, %nres_na, %out_na = buffer.assume.noalias %x, %residual, %weight, %sum_out, %out : buffer, buffer, buffer, buffer, buffer")
    elif both:
        e("  %x_na, %weight_na, %out_na, %out_t_na = buffer.assume.noalias %x, %weight, %out, %out_t : buffer, buffer, buffer, buffer")
    else:
        e("  %x_na, %weight_na, %out_na = buffer.assume.noalias %x, %weight, %out : buffer, buffer, buffer")
    e("  %x_view = buffer.view %x_na[%base] : buffer -> view<[%total_elems]xf32>")
    e("  %weight_view = buffer.view %weight_na[%base] : buffer -> view<[%dim]xf32>")
    if resadd:
        e("  %res_view = buffer.view %res_na[%base] : buffer -> view<[%total_elems]xf32>")
        e("  %nres_view = buffer.view %nres_na[%base] : buffer -> view<[%total_elems]xf32>")
    e("  %out_view = buffer.view %out_na[%base] : buffer -> view<[%total_elems]xf16>")
    if both:
        e("  %out_t_view = buffer.view %out_t_na[%base] : buffer -> view<[%total_elems]xf16>")
    if wpr == 1:
        e("  %row = kernel.workgroup.id<x> : index")
        e("  %lane = kernel.workitem.id<x> : index")
    else:
        e("  %wg = kernel.workgroup.id<x> : index")
        e("  %tid = kernel.workitem.id<x> : index")
        e("  %c32w = index.constant 32 : index")
        e(f"  %cwpr2 = index.constant {wpr} : index")
        e("  %wave = index.div %tid, %c32w : index")
        e("  %lane = index.rem %tid, %c32w : index")
        e("  %wgrow = index.mul %wg, %cwpr2 : index")
        e("  %row = index.add %wgrow, %wave : index")
    e("  %row_base = index.mul %row, %dim : index")
    e("  %lane_base = index.add %row_base, %lane : index")
    if tiled:
        e("  %c16t = index.constant 16 : index")
        e("  %c256t = index.constant 256 : index")
        e(f"  %ctiles = index.constant {dim // 16} : index")
        e("  %trow = index.div %row, %c16t : index")
        e("  %trr = index.rem %row, %c16t : index")
        e("  %tlh = index.div %lane, %c16t : index")
        e("  %tll = index.rem %lane, %c16t : index")
        e("  %tt0 = index.mul %trow, %ctiles : index")
        e("  %tt1 = index.add %tt0, %tlh : index")
        e("  %tt2 = index.mul %tt1, %c256t : index")
        e("  %tt3 = index.mul %trr, %c16t : index")
        e("  %tt4 = index.add %tt2, %tt3 : index")
        e("  %tbase = index.add %tt4, %tll : index")
    if wlds:
        assert wpr > 1 and dim % (4 * 32 * wpr) == 0
        e(f"  %wl_bytes = index.constant {dim * 4} : offset")
        e("  %wl_buf = buffer.alloca<workgroup> align(16) %wl_bytes : buffer")
        e(f"  %wl_view = buffer.view %wl_buf[%base] : buffer -> view<{dim}xf32>")
        e("  %wl_c4 = index.constant 4 : index")
        e("  %wl_t4 = index.mul %tid, %wl_c4 : index")
        for c in range(dim // (4 * 32 * wpr)):
            e(f"  %wl_o{c} = index.constant {c * 4 * 32 * wpr} : index")
            e(f"  %wl_i{c} = index.add %wl_t4, %wl_o{c} : index")
            e(f"  %wl_v{c} = vector.load %weight_view[%wl_i{c}] : view<[%dim]xf32> -> vector<4xf32>")
            e(f"  vector.store %wl_v{c}, %wl_view[%wl_i{c}] : vector<4xf32>, view<{dim}xf32>")
        e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    for k in range(n):
        e(f"  %o{k} = index.constant {32 * k} : index")
        e(f"  %a{k} = index.add %lane_base, %o{k} : index")
        if resadd:
            e(f"  %xa{k} = view.load %x_view[%a{k}] : view<[%total_elems]xf32> -> f32")
            e(f"  %ga{k} = view.load %res_view[%a{k}] : view<[%total_elems]xf32> -> f32")
            e(f"  %x{k} = scalar.addf %xa{k}, %ga{k} : f32")
            e(f"  view.store %x{k}, %nres_view[%a{k}] : f32, view<[%total_elems]xf32>")
        else:
            e(f"  %x{k} = view.load %x_view[%a{k}] : view<[%total_elems]xf32> -> f32")
    s = "%zero"
    for k in range(n):
        e(f"  %q{k} = scalar.mulf %x{k}, %x{k} : f32")
        e(f"  %s{k} = scalar.addf {s}, %q{k} : f32")
        s = f"%s{k}"
    e(f"  %sum_sq = kernel.subgroup.reduce<addf> {s} : f32")
    e(f"  %dim_i = scalar.constant {dim} : i32")
    e("  %dim_f = scalar.sitofp %dim_i : i32 to f32")
    e("  %mean = scalar.divf %sum_sq, %dim_f : f32")
    e("  %shifted = scalar.addf %mean, %eps : f32")
    e("  %root = scalar.sqrtf %shifted : f32")
    e("  %inv = scalar.divf %one, %root : f32")
    # Hold the first `keep` row values across the reduction and reload the rest for the output pass.
    # Fewer VGPRs give one more wave per SIMD: 56 is 8% faster than holding all 160 at dim 5120.
    if keep is None:
        keep = 56 if dim == 5120 else n
    for k in range(n):
        e(f"  %wi{k} = index.add %lane, %o{k} : index")
        if wlds:
            e(f"  %w{k} = view.load %wl_view[%wi{k}] : view<{dim}xf32> -> f32")
        else:
            e(f"  %w{k} = view.load %weight_view[%wi{k}] : view<[%dim]xf32> -> f32")
        xk = f"%x{k}"
        if k >= keep:
            if resadd:
                e(f"  %xra{k} = view.load %x_view[%a{k}] : view<[%total_elems]xf32> -> f32")
                e(f"  %gra{k} = view.load %res_view[%a{k}] : view<[%total_elems]xf32> -> f32")
                e(f"  %xr{k} = scalar.addf %xra{k}, %gra{k} : f32")
            else:
                e(f"  %xr{k} = view.load %x_view[%a{k}] : view<[%total_elems]xf32> -> f32")
            xk = f"%xr{k}"
        e(f"  %nm{k} = scalar.mulf {xk}, %inv : f32")
        e(f"  %wt{k} = scalar.mulf %nm{k}, %w{k} : f32")
        e(f"  %h{k} = scalar.fptrunc %wt{k} : f32 to f16")
        if tiled:
            e(f"  %to{k} = index.constant {512 * k} : index")
            e(f"  %ta{k} = index.add %tbase, %to{k} : index")
            if both:
                e(f"  view.store %h{k}, %out_view[%a{k}] : f16, view<[%total_elems]xf16>")
            e(f"  view.store %h{k}, %{'out_t_view' if both else 'out_view'}[%ta{k}] : f16, view<[%total_elems]xf16>")
        else:
            e(f"  view.store %h{k}, %out_view[%a{k}] : f16, view<[%total_elems]xf16>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "yah_half_norm_unrolled.loom"
    dim = int(sys.argv[2]) if len(sys.argv) > 2 else 5120
    open(out, "w").write(gen(dim))
    print(out)


if __name__ == "__main__":
    main()
