#!/usr/bin/env python3
"""Generate the DeltaNet recurrence in HIP's arithmetic order.

usage: gen_deltanet_hip.py [out.loom]

The prefill's fallback when the token count is not a multiple of 32 (the
chunked tools/gen_gdn_chunk.py needs whole chunks); same ABI and grid.

A port of BatchedDeltaNetRowSplitKernel<float, 16, 2, false, false>, the tile
the HIP engine runs at pp2048 (ssm_row_split.hip), meant to be bit-identical to
it: same inputs in, same raw output and final state out. The op sequence is
taken from its compiled ISA (hipcc -O3, default FP contraction), not from the
C++ source, because the fused multiply-adds decide the rounding:

  8 lanes per state row, 16 keys per lane (keys 16*seg .. +15), 2 rows per lane
  (row0 and row0 + 4); 256 lanes = 64 rows per workgroup, grid (2, num_heads).
  per token:   kq_dot = (inv_k * q_scale) * kq            (scalar unit)
  per row:     s    <- s * alpha                           (each element)
               t_g   = fma(s.w,k.w, fma(s.z,k.z, fma(s.x,k.x, s.y*k.y)))
                       for each of the lane's 4 groups of 4 keys
               u     = (((0 + t0) + t1) + t2) + t3; p the same with q
               u    += xor-1, xor-2, xor-4 partner (DPP butterfly, 8 lanes)
               d     = beta * fma(-inv_k, u, v)
               out   = fma(q_scale, p, d * kq_dot)          (all 8 lanes store it)
               dk    = inv_k * d;  s <- fma(dk, k, s)

IEEE addition is commutative, so the butterfly's operand order (partner +
own) does not matter; the association does and is kept. The k/q loads depend
on the lane, so they are vector loads (no SMEM drains).
"""
import sys

# Wave64: each 64-lane wave takes 16 rows (8 lane groups of 8, second row 8
# below); every row's arithmetic, including the xor-1/2/4 butterfly inside its
# 8 lanes, is the same as in wave32. Wave64 runs FP32 VALU on both ALU halves
# without VOPD pairing, and this kernel's v_fma_f32 cannot pair in wave32.
WSZ = 64

V4 = "vector<4xf32>"


def gen():
    L = []
    e = L.append
    e("// GENERATED by tools/gen_deltanet_hip.py -- edit the generator.")
    e("// DeltaNet recurrence in HIP's BatchedDeltaNetRowSplitKernel<float,16,2> order.")
    e(f"amdgpu.target<gfx1151> @yah_wave32 {{subgroup_size = {WSZ}}}")
    e("")
    e("config.decl @yah_deltanet.batch : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_deltanet.qkv_size : %value: index where [range(%value, 128, 1048576)]")
    e("config.decl @yah_deltanet.inner_size : %value: index where [range(%value, 128, 1048576)]")
    e("config.decl @yah_deltanet.num_key_heads : %value: index where [range(%value, 1, 4096)]")
    e("config.decl @yah_deltanet.num_heads : %value: index where [range(%value, 1, 4096)]")
    e("")
    e("kernel.def target(@yah_wave32) @yah_deltanet() {")
    e("  %unit = index.constant 1 : index")
    e("  %c2 = index.constant 2 : index")
    e("  %c256 = index.constant 256 : index")
    e("  %num_heads = config.get @yah_deltanet.num_heads : index")
    e("  kernel.launch.config workgroups(%c2, %num_heads, %unit) workgroup_size(%c256, %unit, %unit) : index")
    e("} launch(%conv: buffer, %kq: buffer, %ab: buffer, %state: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 3, 4, 8, 16, 32, 64, 128, 16384):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %zero = scalar.constant 0.0 : f32")
    e("  %negzero = scalar.constant -0.0 : f32")
    for v in (1, 2, 4, 32):
        e(f"  %x{v} = scalar.constant {v} : i32")
    e("  %batch = config.get @yah_deltanet.batch : index")
    e("  %qkv_size = config.get @yah_deltanet.qkv_size : index")
    e("  %inner_size = config.get @yah_deltanet.inner_size : index")
    e("  %num_key_heads = config.get @yah_deltanet.num_key_heads : index")
    e("  %num_heads = config.get @yah_deltanet.num_heads : index")
    e("  %conv_total = index.mul %batch, %qkv_size : index")
    e("  %kq_total = index.mul %batch, %num_key_heads : index")
    e("  %kq_total3 = index.mul %kq_total, %c3 : index")
    e("  %ab_total = index.mul %batch, %num_heads : index")
    e("  %ab_total2 = index.mul %ab_total, %c2 : index")
    e("  %state_total = index.mul %num_heads, %c16384 : index")
    e("  %out_total = index.mul %batch, %inner_size : index")
    e("  %conv_na, %kq_na, %ab_na, %state_na, %out_na = buffer.assume.noalias %conv, %kq, %ab, %state, %out : buffer, buffer, buffer, buffer, buffer")
    e("  %conv_view = buffer.view %conv_na[%base] : buffer -> view<[%conv_total]xf32>")
    e("  %kq_view = buffer.view %kq_na[%base] : buffer -> view<[%kq_total3]xf32>")
    e("  %ab_view = buffer.view %ab_na[%base] : buffer -> view<[%ab_total2]xf32>")
    e("  %state_view = buffer.view %state_na[%base] : buffer -> view<[%state_total]xf32>")
    e("  %out_view = buffer.view %out_na[%base] : buffer -> view<[%out_total]xf32>")
    e("  %blk = kernel.workgroup.id<x> : index")
    e("  %h = kernel.workgroup.id<y> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e(f"  %wave = index.div %tid, %c{WSZ} : index")
    e(f"  %lane = index.rem %tid, %c{WSZ} : index")
    e("  %seg = index.rem %lane, %c8 : index")
    e("  %grp = index.div %lane, %c8 : index")
    e("  %blk64 = index.mul %blk, %c64 : index")
    e(f"  %wave8 = index.mul %wave, %c{WSZ // 4} : index")
    e("  %row0a = index.add %blk64, %wave8 : index")
    e("  %row0 = index.add %row0a, %grp : index")
    e(f"  %row1 = index.add %row0, %c{WSZ // 8} : index")
    e("  %kh = index.rem %h, %num_key_heads : index")
    e("  %key0 = index.mul %seg, %c16 : index")
    e("  %s_head = index.mul %h, %c16384 : index")
    # state: rows r, groups g (keys key0 + 4g .. +3)
    for r in range(2):
        e(f"  %srow{r} = index.mul %row{r}, %c128 : index")
        e(f"  %sbase{r}0 = index.add %s_head, %srow{r} : index")
        e(f"  %sbase{r} = index.add %sbase{r}0, %key0 : index")
        for g in range(4):
            e(f"  %sa{r}{g}c = index.constant {4 * g} : index")
            e(f"  %sa{r}{g} = index.add %sbase{r}, %sa{r}{g}c : index")
            e(f"  %si{r}{g} = vector.load %state_view[%sa{r}{g}] : view<[%state_total]xf32> -> {V4}")
    e("  %q_rel0 = index.mul %kh, %c128 : index")
    e("  %q_rel = index.add %q_rel0, %key0 : index")
    e("  %k_head = index.add %num_key_heads, %kh : index")
    e("  %k_rel0 = index.mul %k_head, %c128 : index")
    e("  %k_rel = index.add %k_rel0, %key0 : index")
    e("  %v_heads = index.mul %num_key_heads, %c2 : index")
    e("  %v_head = index.add %v_heads, %h : index")
    e("  %v_rel0 = index.mul %v_head, %c128 : index")
    e("  %o_rel0 = index.mul %h, %c128 : index")
    e("  %last_t = index.sub %batch, %c1 : index")

    def fetch(tok, p, ind):
        """This lane's k, q (4 groups of 4) and the two rows' v of token tok."""
        e(f"{ind}%{p}ct = index.mul {tok}, %qkv_size : index")
        e(f"{ind}%{p}qo = index.add %{p}ct, %q_rel : index")
        e(f"{ind}%{p}ko = index.add %{p}ct, %k_rel : index")
        for g in range(4):
            e(f"{ind}%{p}gq{g}c = index.constant {4 * g} : index")
            e(f"{ind}%{p}qa{g} = index.add %{p}qo, %{p}gq{g}c : index")
            e(f"{ind}%{p}ka{g} = index.add %{p}ko, %{p}gq{g}c : index")
            e(f"{ind}%{p}k{g} = vector.load %conv_view[%{p}ka{g}] : view<[%conv_total]xf32> -> {V4}")
            e(f"{ind}%{p}q{g} = vector.load %conv_view[%{p}qa{g}] : view<[%conv_total]xf32> -> {V4}")
        e(f"{ind}%{p}vt = index.add %{p}ct, %v_rel0 : index")
        for r in range(2):
            e(f"{ind}%{p}vi{r} = index.add %{p}vt, %row{r} : index")
            e(f"{ind}%{p}v{r} = view.load %conv_view[%{p}vi{r}] : view<[%conv_total]xf32> -> f32")
        return [f"%{p}k{g}" for g in range(4)] + [f"%{p}q{g}" for g in range(4)] + [f"%{p}v{r}" for r in range(2)]

    pre = fetch("%c0", "f0_", "  ")
    names = [f"%k{g}" for g in range(4)] + [f"%q{g}" for g in range(4)] + ["%v0", "%v1"]
    ptypes = [V4] * 8 + ["f32", "f32"]
    carried = ", ".join(f"%s{r}{g} = %si{r}{g} : {V4}" for r in range(2) for g in range(4))
    carried += ", " + ", ".join(f"{n} = {v} : {t}" for n, v, t in zip(names, pre, ptypes))
    types = ", ".join([V4] * 8)
    ltypes = types + ", " + ", ".join(ptypes)
    res = ", ".join(f"%sf{r}{g}" for r in range(2) for g in range(4)) + ", " + ", ".join(f"%pf_{i}" for i in range(10))
    # unroll(4) schedule(recurrence): the rolled loop copied the carried state
    # and the prefetched k/q/v back into place on every backedge (compile
    # report move_causes branch_edge, 60 v_mov per token against HIP's none);
    # unrolled, the iterations alternate registers.
    pol = "unroll(%c8) schedule(recurrence)"
    e(f"  {res} = scf.for %t = [%c0 to %batch step %c1]({carried}) -> ({ltypes}) {pol} {{")
    # next token's loads go out first; this token computes on the carried values
    e("    %t_n0 = index.add %t, %c1 : index")
    e("    %t_n = index.min %t_n0, %last_t : index")
    nxt = fetch("%t_n", "nx_", "    ")
    e("    %ct = index.mul %t, %qkv_size : index")
    e("    %abt = index.mul %t, %num_heads : index")
    e("    %abh = index.add %abt, %h : index")
    e("    %abo = index.mul %abh, %c2 : index")
    e("    %abo1 = index.add %abo, %c1 : index")
    e("    %alpha = view.load %ab_view[%abo] : view<[%ab_total2]xf32> -> f32")
    e("    %beta = view.load %ab_view[%abo1] : view<[%ab_total2]xf32> -> f32")
    e("    %kqt = index.mul %t, %num_key_heads : index")
    e("    %kqb = index.add %kqt, %kh : index")
    e("    %kqo = index.mul %kqb, %c3 : index")
    e("    %kqo1 = index.add %kqo, %c1 : index")
    e("    %kqo2 = index.add %kqo, %c2 : index")
    e("    %inv_k = view.load %kq_view[%kqo] : view<[%kq_total3]xf32> -> f32")
    e("    %q_scale = view.load %kq_view[%kqo1] : view<[%kq_total3]xf32> -> f32")
    e("    %kq3 = view.load %kq_view[%kqo2] : view<[%kq_total3]xf32> -> f32")
    e("    %kq_iq = scalar.mulf %inv_k, %q_scale : f32")
    e("    %kq_dot = scalar.mulf %kq_iq, %kq3 : f32")
    e("    %neg_inv_k = scalar.negf %inv_k : f32")
    e(f"    %alpha_v = vector.splat %alpha : {V4}")
    e("    %ot0 = index.mul %t, %inner_size : index")
    e("    %ot = index.add %ot0, %o_rel0 : index")
    # extract k, q elements once
    for g in range(4):
        for i in range(4):
            e(f"    %ke{g}{i} = vector.extract %k{g}[{i}] : {V4} -> f32")
            e(f"    %qe{g}{i} = vector.extract %q{g}[{i}] : {V4} -> f32")
    ys = []
    for r in range(2):
        for g in range(4):
            e(f"    %sa_{r}{g} = vector.mulf %s{r}{g}, %alpha_v : {V4}")
            for i in range(4):
                e(f"    %se{r}{g}{i} = vector.extract %sa_{r}{g}[{i}] : {V4} -> f32")

        def dot(tag, v):
            acc = "%zero"
            for g in range(4):
                s = [f"%se{r}{g}{i}" for i in range(4)]
                x = [f"%{v}e{g}{i}" for i in range(4)]
                n = f"{tag}{r}{g}"
                # HIP's chain fma(s3,x3, fma(s2,x2, fma(s0,x0, s1*x1)))
                e(f"    %{n}m = scalar.mulf {s[1]}, {x[1]} : f32")
                e(f"    %{n}a = scalar.fmaf {s[0]}, {x[0]}, %{n}m : f32")
                e(f"    %{n}b = scalar.fmaf {s[2]}, {x[2]}, %{n}a : f32")
                e(f"    %{n}c = scalar.fmaf {s[3]}, {x[3]}, %{n}b : f32")
                e(f"    %{n}s = scalar.addf {acc}, %{n}c : f32")
                acc = f"%{n}s"
            for m in (1, 2, 4):
                e(f"    %{tag}{r}i{m} = scalar.bitcast {acc} : f32 to i32")
                e(f"    %{tag}{r}x{m}, %{tag}{r}v{m} = kernel.subgroup.shuffle<xor> %{tag}{r}i{m}, %x{m}, %x32 : i32, i32, i32")
                e(f"    %{tag}{r}f{m} = scalar.bitcast %{tag}{r}x{m} : i32 to f32")
                e(f"    %{tag}{r}r{m} = scalar.addf {acc}, %{tag}{r}f{m} : f32")
                acc = f"%{tag}{r}r{m}"
            return acc
        u = dot("u", "k")
        p = dot("p", "q")
        e(f"    %vm{r} = scalar.fmaf %neg_inv_k, {u}, %v{r} : f32")
        e(f"    %d{r} = scalar.mulf %beta, %vm{r} : f32")
        e(f"    %dkq{r} = scalar.mulf %d{r}, %kq_dot : f32")
        e(f"    %o{r} = scalar.fmaf %q_scale, {p}, %dkq{r} : f32")
        e(f"    %oi{r} = index.add %ot, %row{r} : index")
        e(f"    view.store %o{r}, %out_view[%oi{r}] : f32, view<[%out_total]xf32>")
        e(f"    %dk{r} = scalar.mulf %inv_k, %d{r} : f32")
        e(f"    %dkv{r} = vector.splat %dk{r} : {V4}")
        for g in range(4):
            # componentwise, as the dot products already read k: then no
            # consumer needs the whole k bank and the loop-carried k/q
            # banks project to registers. Same fmas.
            cs = []
            for i in range(4):
                e(f"    %snc{r}{g}{i} = scalar.fmaf %dk{r}, %ke{g}{i}, %se{r}{g}{i} : f32")
                cs.append(f"%snc{r}{g}{i}")
            e(f"    %sn{r}{g} = vector.from_elements {', '.join(cs)} : {V4}")
            ys.append(f"%sn{r}{g}")
    e(f"    scf.yield {', '.join(ys + nxt)} : {ltypes}")
    e("  }")
    for r in range(2):
        for g in range(4):
            e(f"  vector.store %sf{r}{g}, %state_view[%sa{r}{g}] : {V4}, view<[%state_total]xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "yah_deltanet_hip_f32.loom"
    open(out, "w").write(gen())
    print(out)


if __name__ == "__main__":
    main()
