#!/usr/bin/env python3
"""Decode (one query token) attention over the paged KV cache of one layer.

Layout (the prefill's paged pools):
  K pool    [pool_rows][1024] f16; logical position p is in row ptab[p / 256] * 256 + p % 256.
  V^T pool  [4 kv heads][pool_rows / 16 tiles][256 dims][16 keys] f16, same physical row (tile = row / 16, key = row % 16).
The current position comes from a device i32 (pos); keys 0..pos are visible.

Kernels (gen(which, T), T = pool rows, a multiple of 256):
  kvappend  write the new token's K (roped, f32) and V (f32) into its row. Grid 4 x 256.
  part      one workgroup per (kv head, page s): the page's 256 keys against the 6 query heads of the GQA group.
            Scores (thread = key), per-head block max / sum, p in LDS, then P.V (thread = dim).
            The page's V^T slab (16 tiles x 256 dims x 16 keys) is contiguous per kv head.
            Writes acc[s][head][256], m[s][head], l[s][head]. Grid (4, pages used).
  reduce    one workgroup per head, thread = dim: merge the pages,
            out = (sum_s e^(m_s - M) acc_s) / (sum_s e^(m_s - M) l_s) * sigmoid(gate).
score = q.k / 16 (1 / sqrt(256)). The softmax has two levels (per page, then across pages), not an online one.
"""
import sys

KVW = 1024          # 4 kv heads x 256
# Loom read-ahead depth on the K-row and V^T-tile loops of part (V depth 3+ spills).
PIPE_K, PIPE_V = 3, 2
NH, NKV, HD = 24, 4, 256
G = NH // NKV       # query heads per kv head


def gen_kvappend(T):
    npg = T // 256
    L = []
    e = L.append
    e("// GENERATED by tools/gen_decode_attn.py (kvappend) -- edit the generator.")
    e("amdgpu.target<gfx1151> @da32 {subgroup_size = 32}")
    e("kernel.def target(@da32) @yah_dattn_kvappend() {")
    e("  %u1 = index.constant 1 : index")
    e("  %c4 = index.constant 4 : index")
    e("  %c256 = index.constant 256 : index")
    e("  kernel.launch.config workgroups(%c4, %u1, %u1) workgroup_size(%c256, %u1, %u1) : index")
    e("} launch(%k: buffer, %v: buffer, %kp: buffer, %vtp: buffer, %ptab: buffer, %pos: buffer) {")
    e("  %base = index.constant 0 : offset")
    e("  %c0 = index.constant 0 : index")
    e("  %c16 = index.constant 16 : index")
    e("  %c256 = index.constant 256 : index")
    e(f"  %cT = index.constant {T} : index")
    e(f"  %cpg = index.constant {npg - 1} : index")
    e(f"  %ctl = index.constant {T // 16} : index")
    e(f"  %ckw = index.constant {KVW} : index")
    e("  %k_na, %v_na, %kp_na, %vtp_na, %pt_na, %pos_na = buffer.assume.noalias %k, %v, %kp, %vtp, %ptab, %pos : buffer, buffer, buffer, buffer, buffer, buffer")
    e(f"  %kv = buffer.view %k_na[%base] : buffer -> view<{KVW}xf32>")
    e(f"  %vv = buffer.view %v_na[%base] : buffer -> view<{KVW}xf32>")
    e(f"  %kpv = buffer.view %kp_na[%base] : buffer -> view<{T * KVW}xf16>")
    e(f"  %vtv = buffer.view %vtp_na[%base] : buffer -> view<{T * KVW}xf16>")
    e(f"  %ptv = buffer.view %pt_na[%base] : buffer -> view<{npg}xi32>")
    e("  %posv = buffer.view %pos_na[%base] : buffer -> view<1xi32>")
    e("  %h = kernel.workgroup.id<x> : index")
    e("  %d = kernel.workitem.id<x> : index")
    e("  %pi = view.load %posv[%c0] : view<1xi32> -> i32")
    e("  %p0 = index.cast %pi : i32 to index")
    e(f"  %pz = index.max %p0, %c0 : index")
    e(f"  %pmax = index.constant {T - 1} : index")
    e("  %p = index.min %pz, %pmax : index")
    e("  %lp0 = index.div %p, %c256 : index")
    e("  %lp = index.min %lp0, %cpg : index")
    e("  %pgi = view.load %ptv[%lp] : view<" + str(npg) + "xi32> -> i32")
    e("  %pg0 = index.cast %pgi : i32 to index")
    e("  %pgz = index.max %pg0, %c0 : index")
    e("  %pg = index.min %pgz, %cpg : index")
    e("  %pgb = index.mul %pg, %c256 : index")
    e("  %po = index.rem %p, %c256 : index")
    e("  %row = index.add %pgb, %po : index")
    e("  %hd0 = index.mul %h, %c256 : index")
    e("  %col = index.add %hd0, %d : index")
    e("  %kx = view.load %kv[%col] : view<" + str(KVW) + "xf32> -> f32")
    e("  %vx = view.load %vv[%col] : view<" + str(KVW) + "xf32> -> f32")
    e("  %kh = scalar.fptrunc %kx : f32 to f16")
    e("  %vh = scalar.fptrunc %vx : f32 to f16")
    e("  %ka0 = index.mul %row, %ckw : index")
    e("  %ka = index.add %ka0, %col : index")
    e(f"  view.store %kh, %kpv[%ka] : f16, view<{T * KVW}xf16>")
    # V^T: ((h * tiles + row / 16) * 256 + d) * 16 + row % 16
    e("  %vt0 = index.mul %h, %ctl : index")
    e("  %tile = index.div %row, %c16 : index")
    e("  %vt1 = index.add %vt0, %tile : index")
    e("  %vt2 = index.mul %vt1, %c256 : index")
    e("  %vt3 = index.add %vt2, %d : index")
    e("  %vt4 = index.mul %vt3, %c16 : index")
    e("  %key = index.rem %row, %c16 : index")
    e("  %va = index.add %vt4, %key : index")
    e(f"  view.store %vh, %vtv[%va] : f16, view<{T * KVW}xf16>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_part(T):
    npg = T // 256
    L = []
    e = L.append
    e("// GENERATED by tools/gen_decode_attn.py (part) -- edit the generator.")
    e("amdgpu.target<gfx1151> @da32 {subgroup_size = 32}")
    e("kernel.def target(@da32) @yah_dattn_part() {")
    e("  %u1 = index.constant 1 : index")
    e("  %c4 = index.constant 4 : index")
    e("  %c256 = index.constant 256 : index")
    e(f"  %cnp = index.constant {npg} : index")
    # Grid (4 kv heads, pages): the 4 kv heads of a page run together, so each 2 KB K row is read in full at once.
    # The host dispatches only the pages in use, ceil((pos + 1) / 256).
    e("  kernel.launch.config workgroups(%c4, %cnp, %u1) workgroup_size(%c256, %u1, %u1) : index")
    e("} launch(%q: buffer, %kp: buffer, %vtp: buffer, %ptab: buffer, %pos: buffer, %acc: buffer, %ml: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 4, 8, 16, 32, 256):
        e(f"  %c{v} = index.constant {v} : index")
    e(f"  %cpg = index.constant {npg - 1} : index")
    e(f"  %ctl = index.constant {T // 16} : index")
    e(f"  %ckw = index.constant {KVW} : index")
    e(f"  %cG = index.constant {G} : index")
    e("  %zf = scalar.constant 0.0 : f32")
    e("  %ninf = scalar.constant -3.4028234663852886e+38 : f32")
    e("  %scl = scalar.constant 0.0625 : f32")
    e("  %q_na, %kp_na, %vtp_na, %pt_na, %pos_na, %acc_na, %ml_na = buffer.assume.noalias %q, %kp, %vtp, %ptab, %pos, %acc, %ml : buffer, buffer, buffer, buffer, buffer, buffer, buffer")
    e(f"  %qv = buffer.view %q_na[%base] : buffer -> view<{NH * HD}xf32>")
    e(f"  %kpv = buffer.view %kp_na[%base] : buffer -> view<{T * KVW}xf16>")
    e(f"  %vtv = buffer.view %vtp_na[%base] : buffer -> view<{T * KVW}xf16>")
    e(f"  %ptv = buffer.view %pt_na[%base] : buffer -> view<{npg}xi32>")
    e("  %posv = buffer.view %pos_na[%base] : buffer -> view<1xi32>")
    e(f"  %accv = buffer.view %acc_na[%base] : buffer -> view<{npg * NH * HD}xf32>")
    e(f"  %mlv = buffer.view %ml_na[%base] : buffer -> view<{npg * NH * 2}xf32>")
    # LDS: q [6][256] f32 | p [6][256] f32 | wave partials [8][6] f32 (max), [8][6] (sum)
    nlds = G * HD * 2 + 8 * G * 2
    e(f"  %ldsb = index.constant {nlds * 4} : offset")
    e("  %ldsp = buffer.alloca<workgroup> align(16) %ldsb : buffer")
    e(f"  %lds = buffer.view %ldsp[%base] : buffer -> view<{nlds}xf32>")
    e("  %h = kernel.workgroup.id<x> : index")
    e("  %s = kernel.workgroup.id<y> : index")
    e("  %t = kernel.workitem.id<x> : index")
    e("  %wv = index.div %t, %c32 : index")
    e("  %ln = index.rem %t, %c32 : index")
    e("  %pi = view.load %posv[%c0] : view<1xi32> -> i32")
    e("  %p0 = index.cast %pi : i32 to index")
    e("  %pz = index.max %p0, %c0 : index")
    e(f"  %pmax = index.constant {T - 1} : index")
    e("  %posx = index.min %pz, %pmax : index")
    e("  %n = index.add %posx, %c1 : index")
    e("  %sc = index.min %s, %cpg : index")
    e(f"  %pgi = view.load %ptv[%sc] : view<{npg}xi32> -> i32")
    e("  %pg0 = index.cast %pgi : i32 to index")
    e("  %pgz = index.max %pg0, %c0 : index")
    e("  %pg = index.min %pgz, %cpg : index")
    # q of the G heads of kv head h -> LDS (thread t: dims t of each head)
    e("  %qh0 = index.mul %h, %cG : index")
    for j in range(G):
        e(f"  %cj{j} = index.constant {j} : index")
        e(f"  %qhh{j} = index.add %qh0, %cj{j} : index")
        e(f"  %qa{j}a = index.mul %qhh{j}, %c256 : index")
        e(f"  %qa{j} = index.add %qa{j}a, %t : index")
        e(f"  %qx{j} = view.load %qv[%qa{j}] : view<{NH * HD}xf32> -> f32")
        e(f"  %ql{j}a = index.constant {j * HD} : index")
        e(f"  %ql{j} = index.add %ql{j}a, %t : index")
        e(f"  view.store %qx{j}, %lds[%ql{j}] : f32, view<{G * HD * 2 + 8 * G * 2}xf32>")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    LV = f"view<{G * HD * 2 + 8 * G * 2}xf32>"
    # ---- scores: thread t = key s*256 + t, physical row pg*256 + t ----
    e("  %key0 = index.mul %s, %c256 : index")
    e("  %key = index.add %key0, %t : index")
    e("  %valid = index.cmp ult, %key, %n : index")
    e("  %row0 = index.mul %pg, %c256 : index")
    e("  %row = index.add %row0, %t : index")
    e("  %kr0 = index.mul %row, %ckw : index")
    e("  %kh0 = index.mul %h, %c256 : index")
    e("  %kr = index.add %kr0, %kh0 : index")
    e(f"  %klim = index.constant {T * KVW - 8} : index")
    e("  %zv8 = vector.constant 0.0 : vector<8xf32>")
    inits = ", ".join(f"%sa{j} = %zv8 : vector<8xf32>" for j in range(G))
    res = ", ".join(f"%sr{j}" for j in range(G))
    e(f"  %cpk = index.constant {PIPE_K} : index")
    e(f"  {res} = scf.for %c = [%c0 to %c32 step %c1]({inits}) -> ({', '.join(['vector<8xf32>'] * G)}) pipeline(%cpk) {{")
    e("    %d8 = index.mul %c, %c8 : index")
    e("    %ka0 = index.add %kr, %d8 : index")
    e("    %ka = index.min %ka0, %klim : index")
    e(f"    %kh = vector.load %kpv[%ka] : view<{T * KVW}xf16> -> vector<8xf16>")
    e("    %kf = vector.extf %kh : vector<8xf16> to vector<8xf32>")
    nxt = []
    for j in range(G):
        e(f"    %qo{j}a = index.constant {j * HD} : index")
        e(f"    %qo{j} = index.add %qo{j}a, %d8 : index")
        e(f"    %qq{j} = vector.load %lds[%qo{j}] : {LV} -> vector<8xf32>")
        e(f"    %sn{j} = vector.fmaf %qq{j}, %kf, %sa{j} : vector<8xf32>")
        nxt.append(f"%sn{j}")
    e(f"    scf.yield {', '.join(nxt)} : {', '.join(['vector<8xf32>'] * G)}")
    e("  }")
    for j in range(G):
        e(f"  %sd{j} = vector.reduce<addf> %sr{j}, %zf : vector<8xf32>, f32")
        e(f"  %ss{j} = scalar.mulf %sd{j}, %scl : f32")
        e(f"  %sc{j} = scf.if %valid -> (f32) {{")
        e(f"    scf.yield %ss{j} : f32")
        e("  } else {")
        e("    scf.yield %ninf : f32")
        e("  }")
    # block max per head: wave reduce -> LDS partials -> every thread reads 8
    mo = G * HD * 2
    for j in range(G):
        e(f"  %wm{j} = kernel.subgroup.reduce<maxnumf> %sc{j} : f32")
    e("  %is_l0 = index.cmp eq, %ln, %c0 : index")
    e("  scf.if %is_l0 {")
    for j in range(G):
        e(f"    %wmo{j}a = index.mul %wv, %cG : index")
        e(f"    %wmo{j}b = index.add %wmo{j}a, %cj{j} : index")
        e(f"    %wmo{j}c = index.constant {mo} : index")
        e(f"    %wmo{j} = index.add %wmo{j}b, %wmo{j}c : index")
        e(f"    view.store %wm{j}, %lds[%wmo{j}] : f32, {LV}")
    e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    for j in range(G):
        cur = "%ninf"
        for w in range(8):
            e(f"    %bmx{j}_{w}i = index.constant {mo + w * G + j} : index")
            e(f"    %bmx{j}_{w} = view.load %lds[%bmx{j}_{w}i] : {LV} -> f32")
            e(f"    %bm{j}_{w} = scalar.maxnumf {cur}, %bmx{j}_{w} : f32")
            cur = f"%bm{j}_{w}"
        e(f"  %M{j} = scalar.addf {cur}, %zf : f32")
        e(f"  %dm{j} = scalar.subf %sc{j}, %M{j} : f32")
        e(f"  %pr{j} = scalar.expf<afn> %dm{j} : f32")
        e(f"  %pl{j} = scf.if %valid -> (f32) {{")
        e(f"    scf.yield %pr{j} : f32")
        e("  } else {")
        e("    scf.yield %zf : f32")
        e("  }")
        e(f"  %po{j}a = index.constant {G * HD + j * HD} : index")
        e(f"  %po{j} = index.add %po{j}a, %t : index")
        e(f"  view.store %pl{j}, %lds[%po{j}] : f32, {LV}")
        e(f"  %ws{j} = kernel.subgroup.reduce<addf> %pl{j} : f32")
    so = mo + 8 * G
    e("  scf.if %is_l0 {")
    for j in range(G):
        e(f"    %wso{j}a = index.mul %wv, %cG : index")
        e(f"    %wso{j}b = index.add %wso{j}a, %cj{j} : index")
        e(f"    %wso{j}c = index.constant {so} : index")
        e(f"    %wso{j} = index.add %wso{j}b, %wso{j}c : index")
        e(f"    view.store %ws{j}, %lds[%wso{j}] : f32, {LV}")
    e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # m, l out (thread 0)
    e("  %is_t0 = index.cmp eq, %t, %c0 : index")
    e("  scf.if %is_t0 {")
    for j in range(G):
        cur = "%zf"
        for w in range(8):
            e(f"    %bsx{j}_{w}i = index.constant {so + w * G + j} : index")
            e(f"    %bsx{j}_{w} = view.load %lds[%bsx{j}_{w}i] : {LV} -> f32")
            e(f"    %bs{j}_{w} = scalar.addf {cur}, %bsx{j}_{w} : f32")
            cur = f"%bs{j}_{w}"
        # ml[s][head][2]
        e(f"    %mlh{j} = index.add %qh0, %cj{j} : index")
        e(f"    %mls{j} = index.constant {NH} : index")
        e(f"    %mlr{j} = index.mul %sc, %mls{j} : index")
        e(f"    %mlx{j} = index.add %mlr{j}, %mlh{j} : index")
        e(f"    %mla{j} = index.mul %mlx{j}, %c2 : index")
        e(f"    %mlb{j} = index.add %mla{j}, %c1 : index")
        e(f"    view.store %M{j}, %mlv[%mla{j}] : f32, view<{npg * NH * 2}xf32>")
        e(f"    view.store {cur}, %mlv[%mlb{j}] : f32, view<{npg * NH * 2}xf32>")
    e("  }")
    # ---- P.V: thread t = dim; the page's 16 tiles of kv head h ----
    # V^T element ((h * tiles + pg * 16 + i) * 256 + t) * 16 + k
    e("  %vt0 = index.mul %h, %ctl : index")
    e("  %vt1 = index.mul %pg, %c16 : index")
    e("  %vtb = index.add %vt0, %vt1 : index")
    e(f"  %vlim = index.constant {T * KVW - 16} : index")
    e("  %zv16 = vector.constant 0.0 : vector<16xf32>")
    inits = ", ".join(f"%oa{j} = %zv16 : vector<16xf32>" for j in range(G))
    res = ", ".join(f"%or{j}" for j in range(G))
    e(f"  %cpv = index.constant {PIPE_V} : index")
    e(f"  {res} = scf.for %i = [%c0 to %c16 step %c1]({inits}) -> ({', '.join(['vector<16xf32>'] * G)}) pipeline(%cpv) {{")
    e("    %ti = index.add %vtb, %i : index")
    e("    %tr = index.mul %ti, %c256 : index")
    e("    %td = index.add %tr, %t : index")
    e("    %va0 = index.mul %td, %c16 : index")
    e("    %va = index.min %va0, %vlim : index")
    e(f"    %vh = vector.load %vtv[%va] : view<{T * KVW}xf16> -> vector<16xf16>")
    e("    %vf = vector.extf %vh : vector<16xf16> to vector<16xf32>")
    e("    %k16 = index.mul %i, %c16 : index")
    nxt = []
    for j in range(G):
        e(f"    %pp{j}a = index.constant {G * HD + j * HD} : index")
        e(f"    %pp{j} = index.add %pp{j}a, %k16 : index")
        e(f"    %pv{j} = vector.load %lds[%pp{j}] : {LV} -> vector<16xf32>")
        e(f"    %on{j} = vector.fmaf %pv{j}, %vf, %oa{j} : vector<16xf32>")
        nxt.append(f"%on{j}")
    e(f"    scf.yield {', '.join(nxt)} : {', '.join(['vector<16xf32>'] * G)}")
    e("  }")
    for j in range(G):
        e(f"  %ov{j} = vector.reduce<addf> %or{j}, %zf : vector<16xf32>, f32")
        e(f"  %ah{j} = index.add %qh0, %cj{j} : index")
        e(f"  %ao{j}a = index.constant {NH} : index")
        e(f"  %ao{j}b = index.mul %sc, %ao{j}a : index")
        e(f"  %ao{j}c = index.add %ao{j}b, %ah{j} : index")
        e(f"  %ao{j}d = index.mul %ao{j}c, %c256 : index")
        e(f"  %ao{j} = index.add %ao{j}d, %t : index")
        e(f"  view.store %ov{j}, %accv[%ao{j}] : f32, view<{npg * NH * HD}xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_reduce(T):
    npg = T // 256
    L = []
    e = L.append
    e("// GENERATED by tools/gen_decode_attn.py (reduce) -- edit the generator.")
    e("amdgpu.target<gfx1151> @da32 {subgroup_size = 32}")
    e("kernel.def target(@da32) @yah_dattn_reduce() {")
    e("  %u1 = index.constant 1 : index")
    e(f"  %cnh = index.constant {NH} : index")
    e("  %c256 = index.constant 256 : index")
    e("  kernel.launch.config workgroups(%cnh, %u1, %u1) workgroup_size(%c256, %u1, %u1) : index")
    e("} launch(%acc: buffer, %ml: buffer, %gate: buffer, %pos: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 256):
        e(f"  %c{v} = index.constant {v} : index")
    e(f"  %cnh = index.constant {NH} : index")
    e(f"  %cpg = index.constant {npg} : index")
    e("  %zf = scalar.constant 0.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e("  %ninf = scalar.constant -3.4028234663852886e+38 : f32")
    e("  %acc_na, %ml_na, %g_na, %pos_na, %o_na = buffer.assume.noalias %acc, %ml, %gate, %pos, %out : buffer, buffer, buffer, buffer, buffer")
    e(f"  %accv = buffer.view %acc_na[%base] : buffer -> view<{npg * NH * HD}xf32>")
    e(f"  %mlv = buffer.view %ml_na[%base] : buffer -> view<{npg * NH * 2}xf32>")
    e(f"  %gv = buffer.view %g_na[%base] : buffer -> view<{NH * HD}xf32>")
    e("  %posv = buffer.view %pos_na[%base] : buffer -> view<1xi32>")
    e(f"  %ov = buffer.view %o_na[%base] : buffer -> view<{NH * HD}xf32>")
    e("  %hh = kernel.workgroup.id<x> : index")
    e("  %t = kernel.workitem.id<x> : index")
    e("  %pi = view.load %posv[%c0] : view<1xi32> -> i32")
    e("  %p0 = index.cast %pi : i32 to index")
    e("  %pz = index.max %p0, %c0 : index")
    e(f"  %pmax = index.constant {T - 1} : index")
    e("  %posx = index.min %pz, %pmax : index")
    e("  %np0 = index.div %posx, %c256 : index")
    e("  %np = index.add %np0, %c1 : index")       # pages in use
    # pass 1: M = max_s m_s
    e("  %M = scf.for %s = [%c0 to %np step %c1](%mc = %ninf : f32) -> (f32) {")
    e("    %r0 = index.mul %s, %cnh : index")
    e("    %r1 = index.add %r0, %hh : index")
    e("    %mi = index.mul %r1, %c2 : index")
    e(f"    %ms = view.load %mlv[%mi] : view<{npg * NH * 2}xf32> -> f32")
    e("    %mn = scalar.maxnumf %mc, %ms : f32")
    e("    scf.yield %mn : f32")
    e("  }")
    e("  %Ls, %As = scf.for %s = [%c0 to %np step %c1](%lc = %zf : f32, %ac = %zf : f32) -> (f32, f32) {")
    e("    %r0 = index.mul %s, %cnh : index")
    e("    %r1 = index.add %r0, %hh : index")
    e("    %mi = index.mul %r1, %c2 : index")
    e("    %li = index.add %mi, %c1 : index")
    e(f"    %ms = view.load %mlv[%mi] : view<{npg * NH * 2}xf32> -> f32")
    e(f"    %ls = view.load %mlv[%li] : view<{npg * NH * 2}xf32> -> f32")
    e("    %dm = scalar.subf %ms, %M : f32")
    e("    %w = scalar.expf<afn> %dm : f32")
    e("    %ai0 = index.mul %r1, %c256 : index")
    e("    %ai = index.add %ai0, %t : index")
    e(f"    %as = view.load %accv[%ai] : view<{npg * NH * HD}xf32> -> f32")
    e("    %ln = scalar.fmaf %w, %ls, %lc : f32")
    e("    %an = scalar.fmaf %w, %as, %ac : f32")
    e("    scf.yield %ln, %an : f32, f32")
    e("  }")
    e("  %inv = scalar.divf %one, %Ls : f32")
    e("  %ctx = scalar.mulf %As, %inv : f32")
    e("  %oi0 = index.mul %hh, %c256 : index")
    e("  %oi = index.add %oi0, %t : index")
    e(f"  %g = view.load %gv[%oi] : view<{NH * HD}xf32> -> f32")
    e("  %ng = scalar.negf %g : f32")
    e("  %eg = scalar.expf<afn> %ng : f32")
    e("  %dg = scalar.addf %eg, %one : f32")
    e("  %sg = scalar.divf %one, %dg : f32")
    e("  %o = scalar.mulf %ctx, %sg : f32")
    e(f"  view.store %o, %ov[%oi] : f32, view<{NH * HD}xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------------------
# Quantized KV (the prefill's kv8a16 / kv4a16 formats, gen_kvq.py), paged.
#   K8: kq [row][256 dwords]: bytes u = rne((k - m) / s) + 128; k - m = s (u - 128).
#       Lane chunk c of 8 dims in 2 dwords, byte slot order (d0, d2, d1, d3).
#       ks [row][8] f16x2 (256 s, -384 s), index head * 2 + half.
#   K4: kq [row][128 dwords]: H256 (k - m) / 16, asymmetric 4-bit per 32-dim group; value = s u + lo.
#       Lane chunk c of 8 rotated dims in one dword: dim 2j at bits 4j, dim 2j+1 at bits 16 + 4j.
#       ks [row][32] f16x2 (16 s, lo - 16 s), index head * 8 + group.
#   V8 / V4: per channel per 16-key tile: vq [kv head][tile][256 dims][4 | 2 dwords].
#       vs [kv head][tile][256] f16x2 (S, C'): v = (1 + u / 256 | 16) S + C'.
#       V8 dword w: keys 4w + (0, 2, 1, 3)[byte].
#       V4 dword w: low nibbles keys 8w + (0, 4, 1, 5), high nibbles keys 8w + (2, 6, 3, 7).
# The current 16-key V tile stays open in f16 ([kv head][256][16]); vappend quantizes it when its 16th key arrives.
# The attention reads the open tile in f16 and every earlier tile quantized.
# ---------------------------------------------------------------------------


def _hdr(e, name):
    e(f"// GENERATED by tools/gen_decode_attn.py ({name}) -- edit the generator.")
    e("amdgpu.target<gfx1151> @da32 {subgroup_size = 32}")


def gen_vappend_q(T, vb):
    """Write the new token's V into the open f16 tile.

    On the tile's 16th key, quantize each channel (gen_kvq gen_vqt arithmetic) into the paged vq / vs pools.
    """
    npg, tiles = T // 256, T // 16
    nw = 2 if vb == 4 else 4
    lv, off, umax = (14, 7, 14) if vb == 4 else (254, 128, 255)
    smul, cmul = (16.0, -23.0) if vb == 4 else (256.0, -384.0)
    L = []
    e = L.append
    _hdr(e, f"vappend_q{vb}")
    e(f"kernel.def target(@da32) @yah_dattn_vappend() {{")
    e("  %u1 = index.constant 1 : index\n  %c4 = index.constant 4 : index\n  %c256 = index.constant 256 : index")
    e("  kernel.launch.config workgroups(%c4, %u1, %u1) workgroup_size(%c256, %u1, %u1) : index")
    e("} launch(%v: buffer, %vopen: buffer, %vq: buffer, %vs: buffer, %ptab: buffer, %pos: buffer) {")
    e("  %base = index.constant 0 : offset")
    for c in (0, 1, 15, 16, 256):
        e(f"  %c{c} = index.constant {c} : index")
    e(f"  %cnw = index.constant {nw} : index")
    e(f"  %cpg = index.constant {npg - 1} : index")
    e(f"  %ctl = index.constant {tiles} : index")
    e("  %v_na, %o_na, %q_na, %s_na, %pt_na, %pos_na = buffer.assume.noalias %v, %vopen, %vq, %vs, %ptab, %pos : buffer, buffer, buffer, buffer, buffer, buffer")
    e(f"  %vv = buffer.view %v_na[%base] : buffer -> view<{KVW}xf32>")
    e(f"  %ov = buffer.view %o_na[%base] : buffer -> view<{KVW * 16}xf16>")
    e(f"  %qv = buffer.view %q_na[%base] : buffer -> view<{4 * tiles * 256 * nw}xi32>")
    e(f"  %sv = buffer.view %s_na[%base] : buffer -> view<{4 * tiles * 256}xi32>")
    e(f"  %ptv = buffer.view %pt_na[%base] : buffer -> view<{npg}xi32>")
    e("  %posv = buffer.view %pos_na[%base] : buffer -> view<1xi32>")
    e("  %h = kernel.workgroup.id<x> : index")
    e("  %d = kernel.workitem.id<x> : index")
    e("  %pi = view.load %posv[%c0] : view<1xi32> -> i32")
    e("  %p0 = index.cast %pi : i32 to index")
    e("  %pz = index.max %p0, %c0 : index")
    e(f"  %pmax = index.constant {T - 1} : index")
    e("  %p = index.min %pz, %pmax : index")
    e("  %key = index.rem %p, %c16 : index")
    e("  %hb = index.mul %h, %c256 : index")
    e("  %col = index.add %hb, %d : index")
    e(f"  %x = view.load %vv[%col] : view<{KVW}xf32> -> f32")
    e("  %xh = scalar.fptrunc %x : f32 to f16")
    e("  %ob = index.mul %col, %c16 : index")
    e("  %oa = index.add %ob, %key : index")
    e(f"  view.store %xh, %ov[%oa] : f16, view<{KVW * 16}xf16>")
    e("  %full = index.cmp eq, %key, %c15 : index")
    e("  scf.if %full {")
    vals = []
    for j in range(16):
        e(f"    %oi{j}c = index.constant {j} : index")
        e(f"    %oi{j} = index.add %ob, %oi{j}c : index")
        e(f"    %vh{j} = view.load %ov[%oi{j}] : view<{KVW * 16}xf16> -> f16")
        e(f"    %v{j} = scalar.extf %vh{j} : f16 to f32")
        vals.append(f"%v{j}")
    mx, mn = vals[0], vals[0]
    for j in range(1, 16):
        e(f"    %mx{j} = scalar.maxnumf {mx}, {vals[j]} : f32")
        e(f"    %mn{j} = scalar.minnumf {mn}, {vals[j]} : f32")
        mx, mn = f"%mx{j}", f"%mn{j}"
    e("    %half = scalar.constant 0.5 : f32")
    e(f"    %rlv = scalar.constant {float(lv)} : f32")
    e("    %one = scalar.constant 1.0 : f32")
    e("    %zero = scalar.constant 0.0 : f32")
    e(f"    %sm = scalar.addf {mx}, {mn} : f32")
    e("    %cen = scalar.mulf %sm, %half : f32")
    e(f"    %rg = scalar.subf {mx}, {mn} : f32")
    e("    %s0 = scalar.divf %rg, %rlv : f32")
    e("    %spos = scalar.cmpf ogt, %s0, %zero : f32")
    e("    %s = scf.select %spos, %s0, %one : f32")
    e("    %sh = scalar.fptrunc %s : f32 to f16")
    e("    %ch = scalar.fptrunc %cen : f32 to f16")
    e("    %sf = scalar.extf %sh : f16 to f32")
    e("    %cf = scalar.extf %ch : f16 to f32")
    e("    %inv = scalar.divf %one, %sf : f32")
    e(f"    %roff = scalar.constant {float(off)} : f32")
    e(f"    %rmax = scalar.constant {float(umax)} : f32")
    us = []
    for j in range(16):
        e(f"    %xc{j} = scalar.subf {vals[j]}, %cf : f32")
        e(f"    %xs{j} = scalar.mulf %xc{j}, %inv : f32")
        e(f"    %xr{j} = scalar.roundevenf %xs{j} : f32")
        e(f"    %xo{j} = scalar.addf %xr{j}, %roff : f32")
        e(f"    %xl{j} = scalar.maxnumf %xo{j}, %zero : f32")
        e(f"    %xm{j} = scalar.minnumf %xl{j}, %rmax : f32")
        e(f"    %xu{j} = scalar.fptosi %xm{j} : f32 to i32")
        us.append(f"%xu{j}")
    words = []
    for w in range(nw):
        acc = None
        for p_ in range(8 if vb == 4 else 4):
            if vb == 4:
                key = 8 * w + (2 * p_ if p_ < 4 else 2 * (p_ - 4) + 1)
                sh = 4 * p_
            else:
                key = 4 * w + (0, 2, 1, 3)[p_]
                sh = 8 * p_
            e(f"    %ps{w}_{p_}c = scalar.constant {sh} : i32")
            e(f"    %ps{w}_{p_} = scalar.shli {us[key]}, %ps{w}_{p_}c : i32")
            if acc is None:
                acc = f"%ps{w}_{p_}"
            else:
                e(f"    %po{w}_{p_} = scalar.ori {acc}, %ps{w}_{p_} : i32")
                acc = f"%po{w}_{p_}"
        words.append(acc)
    # physical tile
    e("    %tl = index.div %p, %c16 : index")
    e("    %lp0 = index.div %tl, %c16 : index")
    e("    %lp = index.min %lp0, %cpg : index")
    e(f"    %pgi = view.load %ptv[%lp] : view<{npg}xi32> -> i32")
    e("    %pg0 = index.cast %pgi : i32 to index")
    e("    %pgz = index.max %pg0, %c0 : index")
    e("    %pg = index.min %pgz, %cpg : index")
    e("    %tb = index.mul %pg, %c16 : index")
    e("    %to = index.rem %tl, %c16 : index")
    e("    %tile = index.add %tb, %to : index")
    e("    %ht = index.mul %h, %ctl : index")
    e("    %htt = index.add %ht, %tile : index")
    e("    %hd0 = index.mul %htt, %c256 : index")
    e("    %hd = index.add %hd0, %d : index")
    for w in range(nw):
        e(f"    %qa{w}0 = index.constant {w} : index")
        e(f"    %qa{w}1 = index.mul %hd, %cnw : index")
        e(f"    %qa{w} = index.add %qa{w}1, %qa{w}0 : index")
        e(f"    view.store {words[w]}, %qv[%qa{w}] : i32, view<{4 * tiles * 256 * nw}xi32>")
    e(f"    %smf = scalar.constant {smul} : f32")
    e(f"    %cmf = scalar.constant {cmul} : f32")
    e("    %S = scalar.mulf %sf, %smf : f32")
    e("    %Cm = scalar.mulf %sf, %cmf : f32")
    e("    %C = scalar.addf %cf, %Cm : f32")
    e("    %Sh = scalar.fptrunc %S : f32 to f16")
    e("    %Chh = scalar.fptrunc %C : f32 to f16")
    e("    %SC = vector.from_elements %Sh, %Chh : vector<2xf16>")
    e("    %SCw = vector.bitcast %SC : vector<2xf16> to vector<1xi32>")
    e("    %SCi = vector.extract %SCw[0] : vector<1xi32> -> i32")
    e(f"    view.store %SCi, %sv[%hd] : i32, view<{4 * tiles * 256}xi32>")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_part_q(T, kb, vb):
    """yah_dattn_part over quantized K (kb 8 | 4) and V (vb 8 | 4); same grid, LDS reductions and outputs as gen_part.

    K: q goes to LDS in the codes' storage order (K4: H256-rotated first, plus per-group sums for the offset term).
    Each key thread dequantizes its own K row.
    V: tiles before the current one come from vq / vs against p in storage order; the current tile from the open f16 buffer.
    """
    npg, tiles = T // 256, T // 16
    nwv = 2 if vb == 4 else 4
    kdw = 64 if kb == 8 else 32          # dwords of one head's K row
    ksn = 2 if kb == 8 else 8            # scales per head
    L = []
    e = L.append
    _hdr(e, f"part_q k{kb} v{vb}")
    e("kernel.def target(@da32) @yah_dattn_part_q() {")
    e("  %u1 = index.constant 1 : index\n  %c4 = index.constant 4 : index\n  %c256 = index.constant 256 : index")
    e(f"  %cnp = index.constant {npg} : index")
    e("  kernel.launch.config workgroups(%c4, %cnp, %u1) workgroup_size(%c256, %u1, %u1) : index")
    e("} launch(%q: buffer, %kq: buffer, %ks: buffer, %vq: buffer, %vs: buffer, %vopen: buffer, %ptab: buffer, %pos: buffer, %acc: buffer, %ml: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 3, 4, 8, 16, 32, 128, 256):
        e(f"  %c{v} = index.constant {v} : index")
    e(f"  %cpg = index.constant {npg - 1} : index")
    e(f"  %ctl = index.constant {tiles} : index")
    e(f"  %cG = index.constant {G} : index")
    e("  %zf = scalar.constant 0.0 : f32")
    e("  %ninf = scalar.constant -3.4028234663852886e+38 : f32")
    e("  %scl = scalar.constant 0.0625 : f32")
    e("  %q_na, %kq_na, %ks_na, %vq_na, %vs_na, %vo_na, %pt_na, %pos_na, %acc_na, %ml_na = buffer.assume.noalias %q, %kq, %ks, %vq, %vs, %vopen, %ptab, %pos, %acc, %ml : buffer, buffer, buffer, buffer, buffer, buffer, buffer, buffer, buffer, buffer")
    KQN, KSN = T * 4 * kdw, T * 4 * ksn * 2
    VQN, VSN = 4 * tiles * 256 * nwv, 4 * tiles * 256 * 2
    e(f"  %qv = buffer.view %q_na[%base] : buffer -> view<{NH * HD}xf32>")
    e(f"  %kqv = buffer.view %kq_na[%base] : buffer -> view<{KQN}xi32>")
    e(f"  %ksv = buffer.view %ks_na[%base] : buffer -> view<{KSN}xf16>")
    e(f"  %vqv = buffer.view %vq_na[%base] : buffer -> view<{VQN}xi32>")
    e(f"  %vsv = buffer.view %vs_na[%base] : buffer -> view<{VSN}xf16>")
    e(f"  %vov = buffer.view %vo_na[%base] : buffer -> view<{KVW * 16}xf16>")
    e(f"  %ptv = buffer.view %pt_na[%base] : buffer -> view<{npg}xi32>")
    e("  %posv = buffer.view %pos_na[%base] : buffer -> view<1xi32>")
    e(f"  %accv = buffer.view %acc_na[%base] : buffer -> view<{npg * NH * HD}xf32>")
    e(f"  %mlv = buffer.view %ml_na[%base] : buffer -> view<{npg * NH * 2}xf32>")
    # LDS: q (storage order) [G][256] | p [G][256] | p storage order [G][256] | qsum [G][16] (K4) | partials
    QO, PO, PSO, QSO = 0, G * HD, 2 * G * HD, 3 * G * HD
    MO = QSO + G * 16
    SO = MO + 8 * G
    NL = SO + 8 * G
    LV = f"view<{NL}xf32>"
    e(f"  %ldsb = index.constant {NL * 4} : offset")
    e("  %ldsp = buffer.alloca<workgroup> align(16) %ldsb : buffer")
    e(f"  %lds = buffer.view %ldsp[%base] : buffer -> {LV}")
    e("  %h = kernel.workgroup.id<x> : index")
    e("  %s = kernel.workgroup.id<y> : index")
    e("  %t = kernel.workitem.id<x> : index")
    e("  %wv = index.div %t, %c32 : index")
    e("  %ln = index.rem %t, %c32 : index")
    e("  %pi = view.load %posv[%c0] : view<1xi32> -> i32")
    e("  %p0 = index.cast %pi : i32 to index")
    e("  %pz = index.max %p0, %c0 : index")
    e(f"  %pmax = index.constant {T - 1} : index")
    e("  %posx = index.min %pz, %pmax : index")
    e("  %n = index.add %posx, %c1 : index")
    e("  %curt = index.div %posx, %c16 : index")
    e("  %sc = index.min %s, %cpg : index")
    e(f"  %pgi = view.load %ptv[%sc] : view<{npg}xi32> -> i32")
    e("  %pg0 = index.cast %pgi : i32 to index")
    e("  %pgz = index.max %pg0, %c0 : index")
    e("  %pg = index.min %pgz, %cpg : index")
    e("  %qh0 = index.mul %h, %cG : index")
    # ---- q -> LDS (natural order; K4 rotates in place, then everything is permuted) ----
    for j in range(G):
        e(f"  %cj{j} = index.constant {j} : index")
        e(f"  %qhh{j} = index.add %qh0, %cj{j} : index")
        e(f"  %qa{j}a = index.mul %qhh{j}, %c256 : index")
        e(f"  %qa{j} = index.add %qa{j}a, %t : index")
        e(f"  %qx{j} = view.load %qv[%qa{j}] : view<{NH * HD}xf32> -> f32")
        e(f"  %qn{j}a = index.constant {PO + j * HD} : index")
        e(f"  %qn{j} = index.add %qn{j}a, %t : index")
        e(f"  view.store %qx{j}, %lds[%qn{j}] : f32, {LV}")        # natural order in the p region (scratch)
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    if kb == 4:   # H256 per head (Sylvester order, (a + b, a - b)), 8 stages over the scratch
        for st in range(8):
            hh = 1 << st
            for k in range(3):        # 768 pairs / 256 threads
                tg = f"f{st}_{k}"
                e(f"  %{tg}P0 = index.constant {256 * k} : index")
                e(f"  %{tg}P = index.add %t, %{tg}P0 : index")
                e(f"  %{tg}j = index.div %{tg}P, %c128 : index")
                e(f"  %{tg}r = index.rem %{tg}P, %c128 : index")
                e(f"  %{tg}hh = index.constant {hh} : index")
                e(f"  %{tg}hi = index.div %{tg}r, %{tg}hh : index")
                e(f"  %{tg}lo = index.rem %{tg}r, %{tg}hh : index")
                e(f"  %{tg}h2 = index.constant {2 * hh} : index")
                e(f"  %{tg}i0 = index.mul %{tg}hi, %{tg}h2 : index")
                e(f"  %{tg}i = index.add %{tg}i0, %{tg}lo : index")
                e(f"  %{tg}jb = index.mul %{tg}j, %c256 : index")
                e(f"  %{tg}pb0 = index.constant {PO} : index")
                e(f"  %{tg}pb = index.add %{tg}jb, %{tg}pb0 : index")
                e(f"  %{tg}ia = index.add %{tg}pb, %{tg}i : index")
                e(f"  %{tg}ib = index.add %{tg}ia, %{tg}hh : index")
                e(f"  %{tg}a = view.load %lds[%{tg}ia] : {LV} -> f32")
                e(f"  %{tg}b = view.load %lds[%{tg}ib] : {LV} -> f32")
                e(f"  %{tg}s = scalar.addf %{tg}a, %{tg}b : f32")
                e(f"  %{tg}d = scalar.subf %{tg}a, %{tg}b : f32")
                e(f"  view.store %{tg}s, %lds[%{tg}ia] : f32, {LV}")
                e(f"  view.store %{tg}d, %lds[%{tg}ib] : f32, {LV}")
            e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # scatter q (dim t of each head) to the K storage order
    e("  %t4 = index.div %t, %c4 : index")
    e("  %tm4 = index.rem %t, %c4 : index")
    if kb == 8:     # pos = 4 (t / 4) + perm(t % 4), perm swaps 1 <-> 2
        e("  %pr1 = index.rem %tm4, %c2 : index")
        e("  %pr2 = index.mul %pr1, %c2 : index")
        e("  %pr3 = index.div %tm4, %c2 : index")
        e("  %prm = index.add %pr2, %pr3 : index")
        e("  %qp0 = index.mul %t4, %c4 : index")
        e("  %qpos = index.add %qp0, %prm : index")
    else:           # chunk = t / 8, r = t % 8: pos = (chunk / 4) 32 + hi 16 + 4 (chunk % 4) + b
        e("  %ck = index.div %t, %c8 : index")
        e("  %cr = index.rem %t, %c8 : index")
        e("  %cr2 = index.div %cr, %c2 : index")
        e("  %chi = index.rem %cr2, %c2 : index")             # (r >> 1) & 1
        e("  %cb0 = index.rem %cr, %c2 : index")
        e("  %cb1 = index.mul %cb0, %c2 : index")
        e("  %cb2 = index.div %cr, %c4 : index")
        e("  %cb = index.add %cb1, %cb2 : index")             # ((r & 1) << 1) | (r >> 2)
        e("  %cc = index.div %ck, %c4 : index")
        e("  %cd = index.rem %ck, %c4 : index")
        e("  %qp0 = index.mul %cc, %c32 : index")
        e("  %qp1 = index.mul %chi, %c16 : index")
        e("  %qp2 = index.mul %cd, %c4 : index")
        e("  %qp3 = index.add %qp0, %qp1 : index")
        e("  %qp4 = index.add %qp3, %qp2 : index")
        e("  %qpos = index.add %qp4, %cb : index")
    for j in range(G):
        e(f"  %qr{j} = view.load %lds[%qn{j}] : {LV} -> f32")
        if kb == 4:
            e(f"  %qs{j} = scalar.mulf %qr{j}, %scl : f32")       # H256 / 16 (orthonormal)
        else:
            e(f"  %qs{j} = scalar.addf %qr{j}, %zf : f32")
        e(f"  %qd{j}a = index.constant {QO + j * HD} : index")
        e(f"  %qd{j} = index.add %qd{j}a, %qpos : index")
        e(f"  view.store %qs{j}, %lds[%qd{j}] : f32, {LV}")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    if kb == 4:     # per (head, half group) sums of the rotated q: threads 0..95
        # half group c (16 per head) = storage positions g 32 + hf 8 + [0, 8) and + 16
        e("  %c96 = index.constant 96 : index")
        e("  %gsel = index.cmp ult, %t, %c96 : index")
        e("  scf.if %gsel {")
        e("    %gj = index.div %t, %c16 : index")
        e("    %gc = index.rem %t, %c16 : index")
        e("    %gg = index.div %gc, %c2 : index")
        e("    %ghf = index.rem %gc, %c2 : index")
        e("    %gb0 = index.mul %gj, %c256 : index")
        e("    %gb1 = index.mul %gg, %c32 : index")
        e("    %gb2 = index.mul %ghf, %c8 : index")
        e("    %gb3 = index.add %gb0, %gb1 : index")
        e("    %gb = index.add %gb3, %gb2 : index")
        cur = "%zf"
        for k in range(16):
            e(f"    %gk{k}c = index.constant {k if k < 8 else k + 8} : index")
            e(f"    %gk{k} = index.add %gb, %gk{k}c : index")
            e(f"    %gx{k} = view.load %lds[%gk{k}] : {LV} -> f32")
            e(f"    %gs{k} = scalar.addf {cur}, %gx{k} : f32")
            cur = f"%gs{k}"
        e(f"    %gqo = index.constant {QSO} : index")
        e("    %gq1 = index.mul %gj, %c16 : index")
        e("    %gq2 = index.add %gq1, %gc : index")
        e("    %gq = index.add %gq2, %gqo : index")
        e(f"    view.store {cur}, %lds[%gq] : f32, {LV}")
        e("  }")
        e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # ---- scores: thread t = key s*256 + t, physical row pg*256 + t ----
    e("  %key0 = index.mul %s, %c256 : index")
    e("  %key = index.add %key0, %t : index")
    e("  %valid = index.cmp ult, %key, %n : index")
    e("  %row0 = index.mul %pg, %c256 : index")
    e("  %row = index.add %row0, %t : index")
    e(f"  %kdw = index.constant {4 * kdw} : index")
    e("  %kr0 = index.mul %row, %kdw : index")
    e(f"  %khw = index.constant {kdw} : index")
    e("  %kh0 = index.mul %h, %khw : index")
    e("  %kr = index.add %kr0, %kh0 : index")
    e(f"  %klim = index.constant {KQN - (4 if kb == 8 else 2)} : index")   # the loop's load width
    e(f"  %ksr = index.constant {4 * ksn * 2} : index")
    e("  %ks0 = index.mul %row, %ksr : index")
    e(f"  %ksh = index.constant {ksn * 2} : index")
    e("  %ks1 = index.mul %h, %ksh : index")
    e("  %ksb = index.add %ks0, %ks1 : index")
    e("  %w15 = scalar.constant 252645135 : i32")
    e("  %w4 = scalar.constant 4 : i32")
    e(f"  %w15v = vector.splat %w15 : vector<{4 if kb == 8 else 2}xi32>")
    e(f"  %w4v = vector.splat %w4 : vector<{4 if kb == 8 else 2}xi32>")
    e("  %f128 = scalar.constant 128.0 : f32")
    e("  %f128v = vector.splat %f128 : vector<16xf32>")
    e(f"  %cpk = index.constant {PIPE_K} : index")
    nit = 16
    # Per iteration: K8 4 dwords = 16 dims (scale half: iterations 0-7 / 8-15).
    # K4 2 dwords = half a 32-dim group (storage positions g 32 + hf 8 + [0, 8) low nibbles, + 16 high nibbles).
    inits = ", ".join(f"%sa{j} = %zf : f32" for j in range(G))
    res = ", ".join(f"%sr{j}" for j in range(G))
    e(f"  %cit = index.constant {nit} : index")
    e(f"  {res} = scf.for %c = [%c0 to %cit step %c1]({inits}) -> ({', '.join(['f32'] * G)}) pipeline(%cpk) {{")
    kvw = 4 if kb == 8 else 2
    e(f"    %ckvw = index.constant {kvw} : index")
    e("    %d4 = index.mul %c, %ckvw : index")
    e("    %ka0 = index.add %kr, %d4 : index")
    e("    %ka = index.min %ka0, %klim : index")
    e(f"    %kw = vector.load %kqv[%ka] : view<{KQN}xi32> -> vector<{kvw}xi32>")
    if kb == 8:
        e("    %kb8 = vector.bitcast %kw : vector<4xi32> to vector<16xi8>")
        e("    %ku = vector.uitofp %kb8 : vector<16xi8> to vector<16xf32>")
        e("    %kc = vector.subf %ku, %f128v : vector<16xf32>")
        e("    %hf = index.div %c, %c8 : index")
        e("    %ksa0 = index.mul %hf, %c2 : index")
        e("    %ksa = index.add %ksb, %ksa0 : index")
        e(f"    %kS = view.load %ksv[%ksa] : view<{KSN}xf16> -> f16")
        e("    %kSf = scalar.extf %kS : f16 to f32")
        e("    %k256 = scalar.constant 0.00390625 : f32")
        e("    %ksc = scalar.mulf %kSf, %k256 : f32")            # s = S / 256
        e("    %d16 = index.mul %c, %c16 : index")
        nxt = []
        for j in range(G):
            e(f"    %qo{j}a = index.constant {QO + j * HD} : index")
            e(f"    %qo{j} = index.add %qo{j}a, %d16 : index")
            e(f"    %qq{j} = vector.load %lds[%qo{j}] : {LV} -> vector<16xf32>")
            e(f"    %pr{j} = vector.mulf %qq{j}, %kc : vector<16xf32>")
            e(f"    %dt{j} = vector.reduce<addf> %pr{j}, %zf : vector<16xf32>, f32")
            e(f"    %sn{j} = scalar.fmaf %dt{j}, %ksc, %sa{j} : f32")
            nxt.append(f"%sn{j}")
    else:
        e("    %klo = vector.andi %kw, %w15v : vector<2xi32>")
        e("    %khs = vector.shrui %kw, %w4v : vector<2xi32>")
        e("    %khi = vector.andi %khs, %w15v : vector<2xi32>")
        e("    %klb = vector.bitcast %klo : vector<2xi32> to vector<8xi8>")
        e("    %khb = vector.bitcast %khi : vector<2xi32> to vector<8xi8>")
        e("    %kul = vector.uitofp %klb : vector<8xi8> to vector<8xf32>")
        e("    %kuh = vector.uitofp %khb : vector<8xi8> to vector<8xf32>")
        e("    %kg = index.div %c, %c2 : index")
        e("    %khf = index.rem %c, %c2 : index")
        e("    %ksa0 = index.mul %kg, %c2 : index")
        e("    %ksa = index.add %ksb, %ksa0 : index")
        e("    %ksa1 = index.add %ksa, %c1 : index")
        e(f"    %kS = view.load %ksv[%ksa] : view<{KSN}xf16> -> f16")
        e(f"    %kC = view.load %ksv[%ksa1] : view<{KSN}xf16> -> f16")
        e("    %kSf = scalar.extf %kS : f16 to f32")
        e("    %kCf = scalar.extf %kC : f16 to f32")
        e("    %kr16 = scalar.constant 0.0625 : f32")
        e("    %ksc = scalar.mulf %kSf, %kr16 : f32")             # s = S / 16
        e("    %klo0 = scalar.addf %kCf, %kSf : f32")             # lo = C' + S
        e("    %kq0 = index.mul %kg, %c32 : index")
        e("    %kq1 = index.mul %khf, %c8 : index")
        e("    %d32 = index.add %kq0, %kq1 : index")
        nxt = []
        for j in range(G):
            e(f"    %qo{j}a = index.constant {QO + j * HD} : index")
            e(f"    %qo{j} = index.add %qo{j}a, %d32 : index")
            e(f"    %qhp{j} = index.add %qo{j}, %c16 : index")
            e(f"    %ql{j} = vector.load %lds[%qo{j}] : {LV} -> vector<8xf32>")
            e(f"    %qh{j} = vector.load %lds[%qhp{j}] : {LV} -> vector<8xf32>")
            e(f"    %pl{j} = vector.mulf %ql{j}, %kul : vector<8xf32>")
            e(f"    %ph{j} = vector.fmaf %qh{j}, %kuh, %pl{j} : vector<8xf32>")
            e(f"    %dt{j} = vector.reduce<addf> %ph{j}, %zf : vector<8xf32>, f32")
            e(f"    %qsx{j}a = index.constant {QSO + j * 16} : index")
            e(f"    %qsx{j} = index.add %qsx{j}a, %c : index")
            e(f"    %qg{j} = view.load %lds[%qsx{j}] : {LV} -> f32")
            e(f"    %sl{j} = scalar.fmaf %dt{j}, %ksc, %sa{j} : f32")
            e(f"    %sn{j} = scalar.fmaf %qg{j}, %klo0, %sl{j} : f32")
            nxt.append(f"%sn{j}")
    e(f"    scf.yield {', '.join(nxt)} : {', '.join(['f32'] * G)}")
    e("  }")
    for j in range(G):
        e(f"  %ss{j} = scalar.mulf %sr{j}, %scl : f32")
        e(f"  %sc{j} = scf.if %valid -> (f32) {{")
        e(f"    scf.yield %ss{j} : f32")
        e("  } else {")
        e("    scf.yield %ninf : f32")
        e("  }")
    # block max / sum as gen_part; p natural at PO, storage order at PSO
    for j in range(G):
        e(f"  %wm{j} = kernel.subgroup.reduce<maxnumf> %sc{j} : f32")
    e("  %is_l0 = index.cmp eq, %ln, %c0 : index")
    e("  scf.if %is_l0 {")
    for j in range(G):
        e(f"    %wmo{j}a = index.mul %wv, %cG : index")
        e(f"    %wmo{j}b = index.add %wmo{j}a, %cj{j} : index")
        e(f"    %wmo{j}c = index.constant {MO} : index")
        e(f"    %wmo{j} = index.add %wmo{j}b, %wmo{j}c : index")
        e(f"    view.store %wm{j}, %lds[%wmo{j}] : f32, {LV}")
    e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # storage position of key t in its tile (V codes)
    e("  %kt16 = index.div %t, %c16 : index")
    e("  %kk = index.rem %t, %c16 : index")
    e("  %ktb = index.mul %kt16, %c16 : index")
    if vb == 8:
        e("  %vk4 = index.div %kk, %c4 : index")
        e("  %vkm = index.rem %kk, %c4 : index")
        e("  %vr1 = index.rem %vkm, %c2 : index")
        e("  %vr2 = index.mul %vr1, %c2 : index")
        e("  %vr3 = index.div %vkm, %c2 : index")
        e("  %vrp = index.add %vr2, %vr3 : index")
        e("  %vp0 = index.mul %vk4, %c4 : index")
        e("  %vpp = index.add %vp0, %vrp : index")
    else:
        e("  %vw = index.div %kk, %c8 : index")
        e("  %vr = index.rem %kk, %c8 : index")
        e("  %vr2 = index.div %vr, %c2 : index")
        e("  %vhi = index.rem %vr2, %c2 : index")
        e("  %vb0 = index.rem %vr, %c2 : index")
        e("  %vb1 = index.mul %vb0, %c2 : index")
        e("  %vb2 = index.div %vr, %c4 : index")
        e("  %vbb = index.add %vb1, %vb2 : index")
        e("  %vp0 = index.mul %vhi, %c8 : index")
        e("  %vp1 = index.mul %vw, %c4 : index")
        e("  %vp2 = index.add %vp0, %vp1 : index")
        e("  %vpp = index.add %vp2, %vbb : index")
    e("  %vpos = index.add %ktb, %vpp : index")
    for j in range(G):
        cur = "%ninf"
        for w in range(8):
            e(f"    %bmx{j}_{w}i = index.constant {MO + w * G + j} : index")
            e(f"    %bmx{j}_{w} = view.load %lds[%bmx{j}_{w}i] : {LV} -> f32")
            e(f"    %bm{j}_{w} = scalar.maxnumf {cur}, %bmx{j}_{w} : f32")
            cur = f"%bm{j}_{w}"
        e(f"  %M{j} = scalar.addf {cur}, %zf : f32")
        e(f"  %dm{j} = scalar.subf %sc{j}, %M{j} : f32")
        e(f"  %prx{j} = scalar.expf<afn> %dm{j} : f32")
        e(f"  %pv{j} = scf.if %valid -> (f32) {{")
        e(f"    scf.yield %prx{j} : f32")
        e("  } else {")
        e("    scf.yield %zf : f32")
        e("  }")
        e(f"  %po{j}a = index.constant {PO + j * HD} : index")
        e(f"  %po{j} = index.add %po{j}a, %t : index")
        e(f"  view.store %pv{j}, %lds[%po{j}] : f32, {LV}")
        e(f"  %pq{j}a = index.constant {PSO + j * HD} : index")
        e(f"  %pq{j} = index.add %pq{j}a, %vpos : index")
        e(f"  view.store %pv{j}, %lds[%pq{j}] : f32, {LV}")
        e(f"  %ws{j} = kernel.subgroup.reduce<addf> %pv{j} : f32")
    e("  scf.if %is_l0 {")
    for j in range(G):
        e(f"    %wso{j}a = index.mul %wv, %cG : index")
        e(f"    %wso{j}b = index.add %wso{j}a, %cj{j} : index")
        e(f"    %wso{j}c = index.constant {SO} : index")
        e(f"    %wso{j} = index.add %wso{j}b, %wso{j}c : index")
        e(f"    view.store %ws{j}, %lds[%wso{j}] : f32, {LV}")
    e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("  %is_t0 = index.cmp eq, %t, %c0 : index")
    e("  scf.if %is_t0 {")
    for j in range(G):
        cur = "%zf"
        for w in range(8):
            e(f"    %bsx{j}_{w}i = index.constant {SO + w * G + j} : index")
            e(f"    %bsx{j}_{w} = view.load %lds[%bsx{j}_{w}i] : {LV} -> f32")
            e(f"    %bs{j}_{w} = scalar.addf {cur}, %bsx{j}_{w} : f32")
            cur = f"%bs{j}_{w}"
        e(f"    %mlh{j} = index.add %qh0, %cj{j} : index")
        e(f"    %mls{j} = index.constant {NH} : index")
        e(f"    %mlr{j} = index.mul %sc, %mls{j} : index")
        e(f"    %mlx{j} = index.add %mlr{j}, %mlh{j} : index")
        e(f"    %mla{j} = index.mul %mlx{j}, %c2 : index")
        e(f"    %mlb{j} = index.add %mla{j}, %c1 : index")
        e(f"    view.store %M{j}, %mlv[%mla{j}] : f32, view<{npg * NH * 2}xf32>")
        e(f"    view.store {cur}, %mlv[%mlb{j}] : f32, view<{npg * NH * 2}xf32>")
    e("  }")
    # ---- P.V: thread t = dim, the page's 16 tiles ----
    e("  %vt0 = index.mul %h, %ctl : index")
    e("  %vt1 = index.mul %pg, %c16 : index")
    e("  %vtb = index.add %vt0, %vt1 : index")
    e("  %gt0 = index.mul %sc, %c16 : index")                 # logical tile of i = 0
    e(f"  %vlim = index.constant {VQN - nwv} : index")
    e(f"  %slim = index.constant {VSN - 2} : index")
    e("  %oh0 = index.mul %h, %c256 : index")
    e("  %oh1 = index.add %oh0, %t : index")
    e("  %oo = index.mul %oh1, %c16 : index")                 # open tile row of dim t
    e("  %zv16 = vector.constant 0.0 : vector<16xf32>")
    e(f"  %vsm = scalar.constant {1.0 / 256 if vb == 8 else 1.0 / 16} : f32")
    inits = ", ".join(f"%oa{j} = %zv16 : vector<16xf32>" for j in range(G))
    res = ", ".join(f"%or{j}" for j in range(G))
    e(f"  %cpv = index.constant {PIPE_V} : index")
    e(f"  {res} = scf.for %i = [%c0 to %c16 step %c1]({inits}) -> ({', '.join(['vector<16xf32>'] * G)}) pipeline(%cpv) {{")
    e("    %gt = index.add %gt0, %i : index")
    e("    %older = index.cmp ult, %gt, %curt : index")
    e("    %ti = index.add %vtb, %i : index")
    e("    %tr = index.mul %ti, %c256 : index")
    e("    %td = index.add %tr, %t : index")
    e(f"    %cnwv = index.constant {nwv} : index")
    e("    %va0 = index.mul %td, %cnwv : index")
    e("    %va = index.min %va0, %vlim : index")
    e("    %sa0 = index.mul %td, %c2 : index")
    e("    %sa = index.min %sa0, %slim : index")
    e("    %k16 = index.mul %i, %c16 : index")
    # Quantized tile (storage order): always loaded, used only if older than the current tile.
    e(f"    %vw = vector.load %vqv[%va] : view<{VQN}xi32> -> vector<{nwv}xi32>")
    e(f"    %vS = view.load %vsv[%sa] : view<{VSN}xf16> -> f16")
    e("    %sa1 = index.add %sa, %c1 : index")
    e(f"    %vC = view.load %vsv[%sa1] : view<{VSN}xf16> -> f16")
    e("    %vSf = scalar.extf %vS : f16 to f32")
    e("    %vCf = scalar.extf %vC : f16 to f32")
    e("    %vmul = scalar.mulf %vSf, %vsm : f32")
    e("    %vadd = scalar.addf %vSf, %vCf : f32")
    e("    %vmv = vector.splat %vmul : vector<16xf32>")
    e("    %vav = vector.splat %vadd : vector<16xf32>")
    if vb == 8:
        e("    %vb8 = vector.bitcast %vw : vector<4xi32> to vector<16xi8>")
        e("    %vu = vector.uitofp %vb8 : vector<16xi8> to vector<16xf32>")
    else:
        e("    %w15b = vector.splat %w15 : vector<2xi32>")
        e("    %w4b = vector.splat %w4 : vector<2xi32>")
        e("    %vlo = vector.andi %vw, %w15b : vector<2xi32>")
        e("    %vhs = vector.shrui %vw, %w4b : vector<2xi32>")
        e("    %vnh = vector.andi %vhs, %w15b : vector<2xi32>")
        for k_, (nm_, ix_) in enumerate((("vlo", 0), ("vlo", 1), ("vnh", 0), ("vnh", 1))):
            e(f"    %vce{k_} = vector.extract %{nm_}[{ix_}] : vector<2xi32> -> i32")
        e("    %vcat = vector.from_elements %vce0, %vce1, %vce2, %vce3 : vector<4xi32>")
        e("    %vb8 = vector.bitcast %vcat : vector<4xi32> to vector<16xi8>")
        e("    %vu = vector.uitofp %vb8 : vector<16xi8> to vector<16xf32>")
    e("    %vq16 = vector.fmaf %vu, %vmv, %vav : vector<16xf32>")
    # Quantized tiles before the current one; zeros at and after it (unwritten pool bytes may decode to NaN, and 0 * NaN = NaN).
    # The open tile is added after the loop.
    e("    %vsel = scf.select %older, %vq16, %zv16 : vector<16xf32>")
    e(f"    %cpso = index.constant {PSO} : index")
    e("    %pbk = index.add %cpso, %k16 : index")
    nxt = []
    for j in range(G):
        e(f"    %pn{j}a = index.constant {j * HD} : index")
        e(f"    %pn{j} = index.add %pbk, %pn{j}a : index")
        e(f"    %pnv{j} = vector.load %lds[%pn{j}] : {LV} -> vector<16xf32>")
        e(f"    %on{j} = vector.fmaf %pnv{j}, %vsel, %oa{j} : vector<16xf32>")
        nxt.append(f"%on{j}")
    e(f"    scf.yield {', '.join(nxt)} : {', '.join(['vector<16xf32>'] * G)}")
    e("  }")
    e("  %curpg = index.div %curt, %c16 : index")
    e("  %hasopen = index.cmp eq, %curpg, %sc : index")
    e(f"  %olim = index.constant {KVW * 16 - 16} : index")
    e("  %ooa = index.min %oo, %olim : index")
    e(f"  {', '.join(f'%ox{j}' for j in range(G))} = scf.if %hasopen -> ({', '.join(['vector<16xf32>'] * G)}) {{")
    e(f"    %oh = vector.load %vov[%ooa] : view<{KVW * 16}xf16> -> vector<16xf16>")
    e("    %of = vector.extf %oh : vector<16xf16> to vector<16xf32>")
    e("    %ctin = index.rem %curt, %c16 : index")
    e("    %ctk = index.mul %ctin, %c16 : index")
    e(f"    %cpo = index.constant {PO} : index")
    e("    %opb = index.add %cpo, %ctk : index")
    for j in range(G):
        e(f"    %op{j}a = index.constant {j * HD} : index")
        e(f"    %op{j} = index.add %opb, %op{j}a : index")
        e(f"    %opv{j} = vector.load %lds[%op{j}] : {LV} -> vector<16xf32>")
        e(f"    %oq{j} = vector.fmaf %opv{j}, %of, %or{j} : vector<16xf32>")
    e(f"    scf.yield {', '.join(f'%oq{j}' for j in range(G))} : {', '.join(['vector<16xf32>'] * G)}")
    e("  } else {")
    e(f"    scf.yield {', '.join(f'%or{j}' for j in range(G))} : {', '.join(['vector<16xf32>'] * G)}")
    e("  }")
    for j in range(G):
        e(f"  %ov{j} = vector.reduce<addf> %ox{j}, %zf : vector<16xf32>, f32")
        e(f"  %ah{j} = index.add %qh0, %cj{j} : index")
        e(f"  %ao{j}a = index.constant {NH} : index")
        e(f"  %ao{j}b = index.mul %sc, %ao{j}a : index")
        e(f"  %ao{j}c = index.add %ao{j}b, %ah{j} : index")
        e(f"  %ao{j}d = index.mul %ao{j}c, %c256 : index")
        e(f"  %ao{j} = index.add %ao{j}d, %t : index")
        e(f"  view.store %ov{j}, %accv[%ao{j}] : f32, view<{npg * NH * HD}xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_kappend_q(T, kb):
    """Quantize the new token's K into the paged kq / ks pools at row ptab[pos / 256] * 256 + pos % 256.

    Arithmetic copied from gen_kvq.py yah_kq8 / yah_kq4 (f16-rounded, minus the layer's channel means).
    One workgroup of 128 lanes, 8 dims each. Bindings (k f32 [1024], mean f32 [1024], kq, ks, ptab, pos).
    """
    import gen_kvq as KQ
    src = KQ._gen_kq8() if kb == 8 else KQ._gen_kq4()
    npg = T // 256
    head, body = src.split("} launch(", 1)
    body = body.split(") {\n", 1)[1]
    out = [f"// GENERATED by tools/gen_decode_attn.py (kappend_q{kb}, from gen_kvq yah_kq{kb}) -- edit the generators.",
           "amdgpu.target<gfx1151> @kvq_w32 {subgroup_size = 32}",
           "kernel.def target(@kvq_w32) @yah_dattn_kappend() {",
           "  %u1 = index.constant 1 : index",
           "  %u128 = index.constant 128 : index",
           "  kernel.launch.config workgroups(%u1, %u1, %u1) workgroup_size(%u128, %u1, %u1) : index",
           "} launch(%kin: buffer, %mean: buffer, %dst: buffer, %scale: buffer, %ptab: buffer, %pos: buffer) {"]
    skip = False
    for ln in body.split("\n"):
        st = ln.strip()
        if st.startswith("%ntok0 = config.get"):
            out.append("  %ntok0 = index.constant 1 : index")
        elif st.startswith("%cap = config.get"):
            out.append(f"  %cap = index.constant {T} : index")
        elif st.startswith("%wg = kernel.workgroup.id"):
            skip = True
            out += [
                "  %tid = kernel.workitem.id<x> : index",
                "  %qa_c0 = index.constant 0 : index",
                "  %qa_c256 = index.constant 256 : index",
                f"  %qa_cpg = index.constant {npg - 1} : index",
                f"  %qa_pmax = index.constant {T - 1} : index",
                f"  %qa_ptv = buffer.view %ptab[%base] : buffer -> view<{npg}xi32>",
                "  %qa_posv = buffer.view %pos[%base] : buffer -> view<1xi32>",
                "  %qa_pi = view.load %qa_posv[%qa_c0] : view<1xi32> -> i32",
                "  %qa_p0 = index.cast %qa_pi : i32 to index",
                "  %qa_pz = index.max %qa_p0, %qa_c0 : index",
                "  %qa_p = index.min %qa_pz, %qa_pmax : index",
                "  %qa_lp0 = index.div %qa_p, %qa_c256 : index",
                "  %qa_lp = index.min %qa_lp0, %qa_cpg : index",
                f"  %qa_pgi = view.load %qa_ptv[%qa_lp] : view<{npg}xi32> -> i32",
                "  %qa_pg0 = index.cast %qa_pgi : i32 to index",
                "  %qa_pgz = index.max %qa_pg0, %qa_c0 : index",
                "  %qa_pg = index.min %qa_pgz, %qa_cpg : index",
                "  %qa_pgb = index.mul %qa_pg, %qa_c256 : index",
                "  %qa_po = index.rem %qa_p, %qa_c256 : index",
                "  %tokc = index.add %qa_pgb, %qa_po : index",
                "  %qa_c128 = index.constant 128 : index",
                "  %live = index.cmp ult, %tid, %qa_c128 : index"]
        elif skip:
            if st.startswith("%live ="):
                skip = False
        elif st.startswith("%s_na, %m_na"):
            out.append("  %s_na, %m_na, %d_na, %c_na = buffer.assume.noalias %kin, %mean, %dst, %scale : buffer, buffer, buffer, buffer")
        elif st.startswith("%s_flat ="):
            out.append("  %s_flat = buffer.view %s_na[%base] : buffer -> view<1024xf32>")
        elif st.startswith("%ra =") or st.startswith("%ad ="):
            continue
        elif st.startswith("%x = vector.load %s_flat"):
            out.append("  %x32v = vector.load %s_flat[%col] : view<1024xf32> -> vector<8xf32>")
            out.append("  %x = vector.fptrunc %x32v : vector<8xf32> to vector<8xf16>")
        else:
            out.append(ln)
    return "\n".join(out)


def gen(which, T):
    assert T % 256 == 0
    return {"kvappend": gen_kvappend, "part": gen_part, "reduce": gen_reduce}[which](T)


if __name__ == "__main__":
    which, T, outp = sys.argv[1], int(sys.argv[2]), sys.argv[3]
    open(outp, "w").write(gen(which, T))
    print(outp)
