// The OpenAI Responses API (POST /v1/responses) on top of model::TextGenerator: request parsing, output parsing, and
// the response object and its stream events.
#ifndef YAH_SERVE_RESPONSES_HPP_
#define YAH_SERVE_RESPONSES_HPP_

#include <cstdint>
#include <functional>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

#include "model/generator.hpp"
#include "nlohmann/json.hpp"
#include "serve/chat_template.hpp"

namespace yah::serve {

using Json = nlohmann::ordered_json;

// Serializes with invalid UTF-8 replaced by U+FFFD instead of throwing.
[[nodiscard]] std::string Dump(const Json& value);

// An OpenAI-style error: an HTTP status and the fields of {"error": {...}}.
struct ApiError : std::runtime_error {
  ApiError(int status, const std::string& message, std::string param = "", std::string code = "",
           std::string type = "invalid_request_error")
      : std::runtime_error(message),
        status(status),
        param(std::move(param)),
        code(std::move(code)),
        type(std::move(type)) {}
  int status;
  std::string param;
  std::string code;
  std::string type;
};

[[nodiscard]] Json ErrorBody(const ApiError& error);

// The text of a message content: a string, or a list of {type: input_text|output_text|text, text} parts.
[[nodiscard]] std::string ContentText(const Json& content, const std::string& param);

struct ResponseRequest {
  std::string model;
  std::vector<ChatMessage> messages;
  ChatOptions chat;
  std::string effort;  // as requested, for the echo
  Json instructions;   // string or null
  Json metadata;       // object
  std::optional<std::uint32_t> max_output_tokens;
  double temperature = 0.6;
  double top_p = 0.95;
  bool stream = false;
};

// none and minimal: thinking off. high, xhigh and max: the template's xhigh. Throws ApiError for other values.
[[nodiscard]] ReasoningEffort ParseEffort(const std::string& effort);

// Throws ApiError for bad or unsupported input.
[[nodiscard]] ResponseRequest ParseResponseRequest(const Json& body);

// Splits generated bytes into reasoning and answer text, one token at a time.
// Never returns a partial UTF-8 sequence or a partial </think>. Reasoning is stripped of surrounding whitespace and
// the whitespace after </think> is dropped, as llama.cpp's reasoning parser does.
class OutputParser {
 public:
  struct Chunk {
    std::string reasoning;
    bool reasoning_ended = false;  // </think> seen; answer follows reasoning
    std::string answer;
  };

  explicit OutputParser(bool thinking) : in_reasoning_(thinking), skip_answer_space_(false) {}
  Chunk Feed(std::string_view bytes);
  Chunk Finish();
  [[nodiscard]] bool in_reasoning() const { return in_reasoning_; }
  // Tokens up to and including the one that completed </think> (all tokens while it never came).
  [[nodiscard]] std::uint32_t reasoning_tokens() const { return reasoning_tokens_; }

 private:
  void Process(std::string text, Chunk* chunk);
  void EmitAnswer(std::string_view text, Chunk* chunk);

  std::string utf8_pending_;
  std::string held_;  // reasoning text that may still be whitespace before </think> or a part of </think>
  bool in_reasoning_;
  bool reasoning_started_ = false;
  bool skip_answer_space_;
  std::uint32_t tokens_ = 0;
  std::uint32_t reasoning_tokens_ = 0;
};

// One /v1/responses generation. Builds the response object and, when emit is set, the stream events.
// emit gets each event already framed as SSE and returns false when the client is gone.
class ResponseStream {
 public:
  ResponseStream(const ResponseRequest& request, std::function<bool(const std::string&)> emit);
  // Each returns false once the client is gone.
  bool Start();
  bool OnToken(std::string_view bytes);
  bool Finish(const model::GenerateResult& result);
  // Sends an error event after a failure in the middle of a stream.
  void Fail(const std::string& message);
  [[nodiscard]] Json Response() const { return ResponseObject(status_); }
  [[nodiscard]] const std::string& id() const { return id_; }
  [[nodiscard]] bool client_alive() const { return alive_; }

 private:
  bool Emit(const std::string& type, Json event);
  void Apply(const OutputParser::Chunk& chunk);
  void OpenReasoning();
  void CloseReasoning();
  void OpenMessage();
  void CloseMessage();
  static Json OutputText(const std::string& text);
  [[nodiscard]] Json ResponseObject(const std::string& status) const;
  [[nodiscard]] Json ReasoningItem() const;
  [[nodiscard]] Json MessageItem() const;

  const ResponseRequest& request_;
  std::function<bool(const std::string&)> emit_;
  OutputParser parser_;
  std::string id_, reasoning_id_, message_id_;
  std::int64_t created_at_;
  std::uint32_t sequence_ = 0;
  std::string status_ = "in_progress";
  std::string reasoning_, answer_;
  int reasoning_index_ = -1, message_index_ = -1;  // output_index, -1 until the item exists
  bool reasoning_open_ = false, message_open_ = false;
  bool alive_ = true;
  Json usage_;
};

}  // namespace yah::serve

#endif  // YAH_SERVE_RESPONSES_HPP_
